// Code generated by protoc-gen-go. DO NOT EDIT.
// source: TNCommandArchives.proto

package TN

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SheetCommandSelectionBehaviorArchive struct {
	SheetSelection       *Reference `protobuf:"bytes,1,opt,name=sheet_selection,json=sheetSelection" json:"sheet_selection,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SheetCommandSelectionBehaviorArchive) Reset()         { *m = SheetCommandSelectionBehaviorArchive{} }
func (m *SheetCommandSelectionBehaviorArchive) String() string { return proto.CompactTextString(m) }
func (*SheetCommandSelectionBehaviorArchive) ProtoMessage()    {}
func (*SheetCommandSelectionBehaviorArchive) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0bf61362014be2a, []int{0}
}

func (m *SheetCommandSelectionBehaviorArchive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SheetCommandSelectionBehaviorArchive.Unmarshal(m, b)
}
func (m *SheetCommandSelectionBehaviorArchive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SheetCommandSelectionBehaviorArchive.Marshal(b, m, deterministic)
}
func (m *SheetCommandSelectionBehaviorArchive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SheetCommandSelectionBehaviorArchive.Merge(m, src)
}
func (m *SheetCommandSelectionBehaviorArchive) XXX_Size() int {
	return xxx_messageInfo_SheetCommandSelectionBehaviorArchive.Size(m)
}
func (m *SheetCommandSelectionBehaviorArchive) XXX_DiscardUnknown() {
	xxx_messageInfo_SheetCommandSelectionBehaviorArchive.DiscardUnknown(m)
}

var xxx_messageInfo_SheetCommandSelectionBehaviorArchive proto.InternalMessageInfo

func (m *SheetCommandSelectionBehaviorArchive) GetSheetSelection() *Reference {
	if m != nil {
		return m.SheetSelection
	}
	return nil
}

type CommandFormChooseTargetTableArchive struct {
	Super                *CommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	TableId              *CFUUIDArchive  `protobuf:"bytes,2,opt,name=table_id,json=tableId" json:"table_id,omitempty"`
	PreviousTableId      *CFUUIDArchive  `protobuf:"bytes,3,opt,name=previous_table_id,json=previousTableId" json:"previous_table_id,omitempty"`
	SheetName            *string         `protobuf:"bytes,4,opt,name=sheet_name,json=sheetName" json:"sheet_name,omitempty"`
	PreviousSheetName    *string         `protobuf:"bytes,5,opt,name=previous_sheet_name,json=previousSheetName" json:"previous_sheet_name,omitempty"`
	Sheet                *Reference      `protobuf:"bytes,6,req,name=sheet" json:"sheet,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CommandFormChooseTargetTableArchive) Reset()         { *m = CommandFormChooseTargetTableArchive{} }
func (m *CommandFormChooseTargetTableArchive) String() string { return proto.CompactTextString(m) }
func (*CommandFormChooseTargetTableArchive) ProtoMessage()    {}
func (*CommandFormChooseTargetTableArchive) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0bf61362014be2a, []int{1}
}

func (m *CommandFormChooseTargetTableArchive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandFormChooseTargetTableArchive.Unmarshal(m, b)
}
func (m *CommandFormChooseTargetTableArchive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandFormChooseTargetTableArchive.Marshal(b, m, deterministic)
}
func (m *CommandFormChooseTargetTableArchive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandFormChooseTargetTableArchive.Merge(m, src)
}
func (m *CommandFormChooseTargetTableArchive) XXX_Size() int {
	return xxx_messageInfo_CommandFormChooseTargetTableArchive.Size(m)
}
func (m *CommandFormChooseTargetTableArchive) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandFormChooseTargetTableArchive.DiscardUnknown(m)
}

var xxx_messageInfo_CommandFormChooseTargetTableArchive proto.InternalMessageInfo

func (m *CommandFormChooseTargetTableArchive) GetSuper() *CommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *CommandFormChooseTargetTableArchive) GetTableId() *CFUUIDArchive {
	if m != nil {
		return m.TableId
	}
	return nil
}

func (m *CommandFormChooseTargetTableArchive) GetPreviousTableId() *CFUUIDArchive {
	if m != nil {
		return m.PreviousTableId
	}
	return nil
}

func (m *CommandFormChooseTargetTableArchive) GetSheetName() string {
	if m != nil && m.SheetName != nil {
		return *m.SheetName
	}
	return ""
}

func (m *CommandFormChooseTargetTableArchive) GetPreviousSheetName() string {
	if m != nil && m.PreviousSheetName != nil {
		return *m.PreviousSheetName
	}
	return ""
}

func (m *CommandFormChooseTargetTableArchive) GetSheet() *Reference {
	if m != nil {
		return m.Sheet
	}
	return nil
}

type CommandSheetInsertDrawablesArchive struct {
	Sheet                *Reference      `protobuf:"bytes,1,req,name=sheet" json:"sheet,omitempty"`
	Drawables            []*Reference    `protobuf:"bytes,2,rep,name=drawables" json:"drawables,omitempty"`
	ProviderUndo         *Reference      `protobuf:"bytes,3,opt,name=provider_undo,json=providerUndo" json:"provider_undo,omitempty"`
	Super                *CommandArchive `protobuf:"bytes,4,req,name=super" json:"super,omitempty"`
	ForDrag              *bool           `protobuf:"varint,5,opt,name=forDrag" json:"forDrag,omitempty"`
	ForPaste             *bool           `protobuf:"varint,7,opt,name=forPaste" json:"forPaste,omitempty"`
	AtIndex              *int32          `protobuf:"varint,6,opt,name=atIndex" json:"atIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CommandSheetInsertDrawablesArchive) Reset()         { *m = CommandSheetInsertDrawablesArchive{} }
func (m *CommandSheetInsertDrawablesArchive) String() string { return proto.CompactTextString(m) }
func (*CommandSheetInsertDrawablesArchive) ProtoMessage()    {}
func (*CommandSheetInsertDrawablesArchive) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0bf61362014be2a, []int{2}
}

func (m *CommandSheetInsertDrawablesArchive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandSheetInsertDrawablesArchive.Unmarshal(m, b)
}
func (m *CommandSheetInsertDrawablesArchive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandSheetInsertDrawablesArchive.Marshal(b, m, deterministic)
}
func (m *CommandSheetInsertDrawablesArchive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandSheetInsertDrawablesArchive.Merge(m, src)
}
func (m *CommandSheetInsertDrawablesArchive) XXX_Size() int {
	return xxx_messageInfo_CommandSheetInsertDrawablesArchive.Size(m)
}
func (m *CommandSheetInsertDrawablesArchive) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandSheetInsertDrawablesArchive.DiscardUnknown(m)
}

var xxx_messageInfo_CommandSheetInsertDrawablesArchive proto.InternalMessageInfo

func (m *CommandSheetInsertDrawablesArchive) GetSheet() *Reference {
	if m != nil {
		return m.Sheet
	}
	return nil
}

func (m *CommandSheetInsertDrawablesArchive) GetDrawables() []*Reference {
	if m != nil {
		return m.Drawables
	}
	return nil
}

func (m *CommandSheetInsertDrawablesArchive) GetProviderUndo() *Reference {
	if m != nil {
		return m.ProviderUndo
	}
	return nil
}

func (m *CommandSheetInsertDrawablesArchive) GetSuper() *CommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *CommandSheetInsertDrawablesArchive) GetForDrag() bool {
	if m != nil && m.ForDrag != nil {
		return *m.ForDrag
	}
	return false
}

func (m *CommandSheetInsertDrawablesArchive) GetForPaste() bool {
	if m != nil && m.ForPaste != nil {
		return *m.ForPaste
	}
	return false
}

func (m *CommandSheetInsertDrawablesArchive) GetAtIndex() int32 {
	if m != nil && m.AtIndex != nil {
		return *m.AtIndex
	}
	return 0
}

type CommandSheetRemoveDrawablesArchive struct {
	Super                        *CommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	Sheet                        *Reference      `protobuf:"bytes,2,req,name=sheet" json:"sheet,omitempty"`
	SortedDrawables              []*Reference    `protobuf:"bytes,3,rep,name=sortedDrawables" json:"sortedDrawables,omitempty"`
	DrawableIndices              *IndexSet       `protobuf:"bytes,4,req,name=drawableIndices" json:"drawableIndices,omitempty"`
	OldSheetSidebarOrder         []*Reference    `protobuf:"bytes,5,rep,name=old_sheet_sidebar_order,json=oldSheetSidebarOrder" json:"old_sheet_sidebar_order,omitempty"`
	FormulaRewriteCommandForUndo *Reference      `protobuf:"bytes,6,opt,name=formula_rewrite_command_for_undo,json=formulaRewriteCommandForUndo" json:"formula_rewrite_command_for_undo,omitempty"`
	XXX_NoUnkeyedLiteral         struct{}        `json:"-"`
	XXX_unrecognized             []byte          `json:"-"`
	XXX_sizecache                int32           `json:"-"`
}

func (m *CommandSheetRemoveDrawablesArchive) Reset()         { *m = CommandSheetRemoveDrawablesArchive{} }
func (m *CommandSheetRemoveDrawablesArchive) String() string { return proto.CompactTextString(m) }
func (*CommandSheetRemoveDrawablesArchive) ProtoMessage()    {}
func (*CommandSheetRemoveDrawablesArchive) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0bf61362014be2a, []int{3}
}

func (m *CommandSheetRemoveDrawablesArchive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandSheetRemoveDrawablesArchive.Unmarshal(m, b)
}
func (m *CommandSheetRemoveDrawablesArchive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandSheetRemoveDrawablesArchive.Marshal(b, m, deterministic)
}
func (m *CommandSheetRemoveDrawablesArchive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandSheetRemoveDrawablesArchive.Merge(m, src)
}
func (m *CommandSheetRemoveDrawablesArchive) XXX_Size() int {
	return xxx_messageInfo_CommandSheetRemoveDrawablesArchive.Size(m)
}
func (m *CommandSheetRemoveDrawablesArchive) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandSheetRemoveDrawablesArchive.DiscardUnknown(m)
}

var xxx_messageInfo_CommandSheetRemoveDrawablesArchive proto.InternalMessageInfo

func (m *CommandSheetRemoveDrawablesArchive) GetSuper() *CommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *CommandSheetRemoveDrawablesArchive) GetSheet() *Reference {
	if m != nil {
		return m.Sheet
	}
	return nil
}

func (m *CommandSheetRemoveDrawablesArchive) GetSortedDrawables() []*Reference {
	if m != nil {
		return m.SortedDrawables
	}
	return nil
}

func (m *CommandSheetRemoveDrawablesArchive) GetDrawableIndices() *IndexSet {
	if m != nil {
		return m.DrawableIndices
	}
	return nil
}

func (m *CommandSheetRemoveDrawablesArchive) GetOldSheetSidebarOrder() []*Reference {
	if m != nil {
		return m.OldSheetSidebarOrder
	}
	return nil
}

func (m *CommandSheetRemoveDrawablesArchive) GetFormulaRewriteCommandForUndo() *Reference {
	if m != nil {
		return m.FormulaRewriteCommandForUndo
	}
	return nil
}

type CommandSheetMoveDrawableZOrderArchive struct {
	Super                *CommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	Sheet                *Reference      `protobuf:"bytes,2,req,name=sheet" json:"sheet,omitempty"`
	DrawableInfos        []*Reference    `protobuf:"bytes,3,rep,name=drawable_infos,json=drawableInfos" json:"drawable_infos,omitempty"`
	Indexes              *IndexSet       `protobuf:"bytes,4,req,name=indexes" json:"indexes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CommandSheetMoveDrawableZOrderArchive) Reset()         { *m = CommandSheetMoveDrawableZOrderArchive{} }
func (m *CommandSheetMoveDrawableZOrderArchive) String() string { return proto.CompactTextString(m) }
func (*CommandSheetMoveDrawableZOrderArchive) ProtoMessage()    {}
func (*CommandSheetMoveDrawableZOrderArchive) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0bf61362014be2a, []int{4}
}

func (m *CommandSheetMoveDrawableZOrderArchive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandSheetMoveDrawableZOrderArchive.Unmarshal(m, b)
}
func (m *CommandSheetMoveDrawableZOrderArchive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandSheetMoveDrawableZOrderArchive.Marshal(b, m, deterministic)
}
func (m *CommandSheetMoveDrawableZOrderArchive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandSheetMoveDrawableZOrderArchive.Merge(m, src)
}
func (m *CommandSheetMoveDrawableZOrderArchive) XXX_Size() int {
	return xxx_messageInfo_CommandSheetMoveDrawableZOrderArchive.Size(m)
}
func (m *CommandSheetMoveDrawableZOrderArchive) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandSheetMoveDrawableZOrderArchive.DiscardUnknown(m)
}

var xxx_messageInfo_CommandSheetMoveDrawableZOrderArchive proto.InternalMessageInfo

func (m *CommandSheetMoveDrawableZOrderArchive) GetSuper() *CommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *CommandSheetMoveDrawableZOrderArchive) GetSheet() *Reference {
	if m != nil {
		return m.Sheet
	}
	return nil
}

func (m *CommandSheetMoveDrawableZOrderArchive) GetDrawableInfos() []*Reference {
	if m != nil {
		return m.DrawableInfos
	}
	return nil
}

func (m *CommandSheetMoveDrawableZOrderArchive) GetIndexes() *IndexSet {
	if m != nil {
		return m.Indexes
	}
	return nil
}

type CommandDocumentInsertSheetArchive struct {
	Document             *Reference      `protobuf:"bytes,1,req,name=document" json:"document,omitempty"`
	Sheet                *Reference      `protobuf:"bytes,2,req,name=sheet" json:"sheet,omitempty"`
	Super                *CommandArchive `protobuf:"bytes,3,req,name=super" json:"super,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CommandDocumentInsertSheetArchive) Reset()         { *m = CommandDocumentInsertSheetArchive{} }
func (m *CommandDocumentInsertSheetArchive) String() string { return proto.CompactTextString(m) }
func (*CommandDocumentInsertSheetArchive) ProtoMessage()    {}
func (*CommandDocumentInsertSheetArchive) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0bf61362014be2a, []int{5}
}

func (m *CommandDocumentInsertSheetArchive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandDocumentInsertSheetArchive.Unmarshal(m, b)
}
func (m *CommandDocumentInsertSheetArchive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandDocumentInsertSheetArchive.Marshal(b, m, deterministic)
}
func (m *CommandDocumentInsertSheetArchive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandDocumentInsertSheetArchive.Merge(m, src)
}
func (m *CommandDocumentInsertSheetArchive) XXX_Size() int {
	return xxx_messageInfo_CommandDocumentInsertSheetArchive.Size(m)
}
func (m *CommandDocumentInsertSheetArchive) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandDocumentInsertSheetArchive.DiscardUnknown(m)
}

var xxx_messageInfo_CommandDocumentInsertSheetArchive proto.InternalMessageInfo

func (m *CommandDocumentInsertSheetArchive) GetDocument() *Reference {
	if m != nil {
		return m.Document
	}
	return nil
}

func (m *CommandDocumentInsertSheetArchive) GetSheet() *Reference {
	if m != nil {
		return m.Sheet
	}
	return nil
}

func (m *CommandDocumentInsertSheetArchive) GetSuper() *CommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

type CommandDocumentRemoveSheetArchive struct {
	Document                     *Reference      `protobuf:"bytes,1,req,name=document" json:"document,omitempty"`
	Sheet                        *Reference      `protobuf:"bytes,2,req,name=sheet" json:"sheet,omitempty"`
	Index                        *uint32         `protobuf:"varint,3,req,name=index" json:"index,omitempty"`
	OldSheetSidebarOrder         []*Reference    `protobuf:"bytes,4,rep,name=old_sheet_sidebar_order,json=oldSheetSidebarOrder" json:"old_sheet_sidebar_order,omitempty"`
	Super                        *CommandArchive `protobuf:"bytes,5,req,name=super" json:"super,omitempty"`
	FormulaRewriteCommandForUndo *Reference      `protobuf:"bytes,6,opt,name=formula_rewrite_command_for_undo,json=formulaRewriteCommandForUndo" json:"formula_rewrite_command_for_undo,omitempty"`
	XXX_NoUnkeyedLiteral         struct{}        `json:"-"`
	XXX_unrecognized             []byte          `json:"-"`
	XXX_sizecache                int32           `json:"-"`
}

func (m *CommandDocumentRemoveSheetArchive) Reset()         { *m = CommandDocumentRemoveSheetArchive{} }
func (m *CommandDocumentRemoveSheetArchive) String() string { return proto.CompactTextString(m) }
func (*CommandDocumentRemoveSheetArchive) ProtoMessage()    {}
func (*CommandDocumentRemoveSheetArchive) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0bf61362014be2a, []int{6}
}

func (m *CommandDocumentRemoveSheetArchive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandDocumentRemoveSheetArchive.Unmarshal(m, b)
}
func (m *CommandDocumentRemoveSheetArchive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandDocumentRemoveSheetArchive.Marshal(b, m, deterministic)
}
func (m *CommandDocumentRemoveSheetArchive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandDocumentRemoveSheetArchive.Merge(m, src)
}
func (m *CommandDocumentRemoveSheetArchive) XXX_Size() int {
	return xxx_messageInfo_CommandDocumentRemoveSheetArchive.Size(m)
}
func (m *CommandDocumentRemoveSheetArchive) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandDocumentRemoveSheetArchive.DiscardUnknown(m)
}

var xxx_messageInfo_CommandDocumentRemoveSheetArchive proto.InternalMessageInfo

func (m *CommandDocumentRemoveSheetArchive) GetDocument() *Reference {
	if m != nil {
		return m.Document
	}
	return nil
}

func (m *CommandDocumentRemoveSheetArchive) GetSheet() *Reference {
	if m != nil {
		return m.Sheet
	}
	return nil
}

func (m *CommandDocumentRemoveSheetArchive) GetIndex() uint32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *CommandDocumentRemoveSheetArchive) GetOldSheetSidebarOrder() []*Reference {
	if m != nil {
		return m.OldSheetSidebarOrder
	}
	return nil
}

func (m *CommandDocumentRemoveSheetArchive) GetSuper() *CommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *CommandDocumentRemoveSheetArchive) GetFormulaRewriteCommandForUndo() *Reference {
	if m != nil {
		return m.FormulaRewriteCommandForUndo
	}
	return nil
}

type CommandDocumentReplaceLastSheetArchive struct {
	Document             *Reference      `protobuf:"bytes,1,req,name=document" json:"document,omitempty"`
	LastSheet            *Reference      `protobuf:"bytes,2,req,name=last_sheet,json=lastSheet" json:"last_sheet,omitempty"`
	NewSheet             *Reference      `protobuf:"bytes,3,req,name=new_sheet,json=newSheet" json:"new_sheet,omitempty"`
	Super                *CommandArchive `protobuf:"bytes,4,req,name=super" json:"super,omitempty"`
	Index                *uint32         `protobuf:"varint,5,opt,name=index" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CommandDocumentReplaceLastSheetArchive) Reset() {
	*m = CommandDocumentReplaceLastSheetArchive{}
}
func (m *CommandDocumentReplaceLastSheetArchive) String() string { return proto.CompactTextString(m) }
func (*CommandDocumentReplaceLastSheetArchive) ProtoMessage()    {}
func (*CommandDocumentReplaceLastSheetArchive) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0bf61362014be2a, []int{7}
}

func (m *CommandDocumentReplaceLastSheetArchive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandDocumentReplaceLastSheetArchive.Unmarshal(m, b)
}
func (m *CommandDocumentReplaceLastSheetArchive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandDocumentReplaceLastSheetArchive.Marshal(b, m, deterministic)
}
func (m *CommandDocumentReplaceLastSheetArchive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandDocumentReplaceLastSheetArchive.Merge(m, src)
}
func (m *CommandDocumentReplaceLastSheetArchive) XXX_Size() int {
	return xxx_messageInfo_CommandDocumentReplaceLastSheetArchive.Size(m)
}
func (m *CommandDocumentReplaceLastSheetArchive) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandDocumentReplaceLastSheetArchive.DiscardUnknown(m)
}

var xxx_messageInfo_CommandDocumentReplaceLastSheetArchive proto.InternalMessageInfo

func (m *CommandDocumentReplaceLastSheetArchive) GetDocument() *Reference {
	if m != nil {
		return m.Document
	}
	return nil
}

func (m *CommandDocumentReplaceLastSheetArchive) GetLastSheet() *Reference {
	if m != nil {
		return m.LastSheet
	}
	return nil
}

func (m *CommandDocumentReplaceLastSheetArchive) GetNewSheet() *Reference {
	if m != nil {
		return m.NewSheet
	}
	return nil
}

func (m *CommandDocumentReplaceLastSheetArchive) GetSuper() *CommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *CommandDocumentReplaceLastSheetArchive) GetIndex() uint32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

type CommandDocumentReorderSheetArchive struct {
	Document             *Reference      `protobuf:"bytes,1,req,name=document" json:"document,omitempty"`
	Sheet                *Reference      `protobuf:"bytes,2,req,name=sheet" json:"sheet,omitempty"`
	SourceIndex          *uint32         `protobuf:"varint,3,req,name=source_index,json=sourceIndex" json:"source_index,omitempty"`
	DestIndex            *uint32         `protobuf:"varint,4,req,name=dest_index,json=destIndex" json:"dest_index,omitempty"`
	Super                *CommandArchive `protobuf:"bytes,5,req,name=super" json:"super,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CommandDocumentReorderSheetArchive) Reset()         { *m = CommandDocumentReorderSheetArchive{} }
func (m *CommandDocumentReorderSheetArchive) String() string { return proto.CompactTextString(m) }
func (*CommandDocumentReorderSheetArchive) ProtoMessage()    {}
func (*CommandDocumentReorderSheetArchive) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0bf61362014be2a, []int{8}
}

func (m *CommandDocumentReorderSheetArchive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandDocumentReorderSheetArchive.Unmarshal(m, b)
}
func (m *CommandDocumentReorderSheetArchive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandDocumentReorderSheetArchive.Marshal(b, m, deterministic)
}
func (m *CommandDocumentReorderSheetArchive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandDocumentReorderSheetArchive.Merge(m, src)
}
func (m *CommandDocumentReorderSheetArchive) XXX_Size() int {
	return xxx_messageInfo_CommandDocumentReorderSheetArchive.Size(m)
}
func (m *CommandDocumentReorderSheetArchive) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandDocumentReorderSheetArchive.DiscardUnknown(m)
}

var xxx_messageInfo_CommandDocumentReorderSheetArchive proto.InternalMessageInfo

func (m *CommandDocumentReorderSheetArchive) GetDocument() *Reference {
	if m != nil {
		return m.Document
	}
	return nil
}

func (m *CommandDocumentReorderSheetArchive) GetSheet() *Reference {
	if m != nil {
		return m.Sheet
	}
	return nil
}

func (m *CommandDocumentReorderSheetArchive) GetSourceIndex() uint32 {
	if m != nil && m.SourceIndex != nil {
		return *m.SourceIndex
	}
	return 0
}

func (m *CommandDocumentReorderSheetArchive) GetDestIndex() uint32 {
	if m != nil && m.DestIndex != nil {
		return *m.DestIndex
	}
	return 0
}

func (m *CommandDocumentReorderSheetArchive) GetSuper() *CommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

type CommandSetSheetNameArchive struct {
	Newname              *string         `protobuf:"bytes,1,req,name=newname" json:"newname,omitempty"`
	Oldname              *string         `protobuf:"bytes,2,req,name=oldname" json:"oldname,omitempty"`
	Sheet                *Reference      `protobuf:"bytes,3,req,name=sheet" json:"sheet,omitempty"`
	Super                *CommandArchive `protobuf:"bytes,4,req,name=super" json:"super,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CommandSetSheetNameArchive) Reset()         { *m = CommandSetSheetNameArchive{} }
func (m *CommandSetSheetNameArchive) String() string { return proto.CompactTextString(m) }
func (*CommandSetSheetNameArchive) ProtoMessage()    {}
func (*CommandSetSheetNameArchive) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0bf61362014be2a, []int{9}
}

func (m *CommandSetSheetNameArchive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandSetSheetNameArchive.Unmarshal(m, b)
}
func (m *CommandSetSheetNameArchive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandSetSheetNameArchive.Marshal(b, m, deterministic)
}
func (m *CommandSetSheetNameArchive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandSetSheetNameArchive.Merge(m, src)
}
func (m *CommandSetSheetNameArchive) XXX_Size() int {
	return xxx_messageInfo_CommandSetSheetNameArchive.Size(m)
}
func (m *CommandSetSheetNameArchive) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandSetSheetNameArchive.DiscardUnknown(m)
}

var xxx_messageInfo_CommandSetSheetNameArchive proto.InternalMessageInfo

func (m *CommandSetSheetNameArchive) GetNewname() string {
	if m != nil && m.Newname != nil {
		return *m.Newname
	}
	return ""
}

func (m *CommandSetSheetNameArchive) GetOldname() string {
	if m != nil && m.Oldname != nil {
		return *m.Oldname
	}
	return ""
}

func (m *CommandSetSheetNameArchive) GetSheet() *Reference {
	if m != nil {
		return m.Sheet
	}
	return nil
}

func (m *CommandSetSheetNameArchive) GetSuper() *CommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

type CommandSetPageOrientationArchive struct {
	InPortraitPageOrientation *bool           `protobuf:"varint,1,req,name=in_portrait_page_orientation,json=inPortraitPageOrientation" json:"in_portrait_page_orientation,omitempty"`
	Sheet                     *Reference      `protobuf:"bytes,2,req,name=sheet" json:"sheet,omitempty"`
	Super                     *CommandArchive `protobuf:"bytes,3,req,name=super" json:"super,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}        `json:"-"`
	XXX_unrecognized          []byte          `json:"-"`
	XXX_sizecache             int32           `json:"-"`
}

func (m *CommandSetPageOrientationArchive) Reset()         { *m = CommandSetPageOrientationArchive{} }
func (m *CommandSetPageOrientationArchive) String() string { return proto.CompactTextString(m) }
func (*CommandSetPageOrientationArchive) ProtoMessage()    {}
func (*CommandSetPageOrientationArchive) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0bf61362014be2a, []int{10}
}

func (m *CommandSetPageOrientationArchive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandSetPageOrientationArchive.Unmarshal(m, b)
}
func (m *CommandSetPageOrientationArchive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandSetPageOrientationArchive.Marshal(b, m, deterministic)
}
func (m *CommandSetPageOrientationArchive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandSetPageOrientationArchive.Merge(m, src)
}
func (m *CommandSetPageOrientationArchive) XXX_Size() int {
	return xxx_messageInfo_CommandSetPageOrientationArchive.Size(m)
}
func (m *CommandSetPageOrientationArchive) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandSetPageOrientationArchive.DiscardUnknown(m)
}

var xxx_messageInfo_CommandSetPageOrientationArchive proto.InternalMessageInfo

func (m *CommandSetPageOrientationArchive) GetInPortraitPageOrientation() bool {
	if m != nil && m.InPortraitPageOrientation != nil {
		return *m.InPortraitPageOrientation
	}
	return false
}

func (m *CommandSetPageOrientationArchive) GetSheet() *Reference {
	if m != nil {
		return m.Sheet
	}
	return nil
}

func (m *CommandSetPageOrientationArchive) GetSuper() *CommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

type CommandSetShowPageNumbersValueArchive struct {
	ShowPageNumbers      *bool           `protobuf:"varint,1,req,name=show_page_numbers,json=showPageNumbers" json:"show_page_numbers,omitempty"`
	Sheet                *Reference      `protobuf:"bytes,2,req,name=sheet" json:"sheet,omitempty"`
	Super                *CommandArchive `protobuf:"bytes,3,req,name=super" json:"super,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CommandSetShowPageNumbersValueArchive) Reset()         { *m = CommandSetShowPageNumbersValueArchive{} }
func (m *CommandSetShowPageNumbersValueArchive) String() string { return proto.CompactTextString(m) }
func (*CommandSetShowPageNumbersValueArchive) ProtoMessage()    {}
func (*CommandSetShowPageNumbersValueArchive) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0bf61362014be2a, []int{11}
}

func (m *CommandSetShowPageNumbersValueArchive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandSetShowPageNumbersValueArchive.Unmarshal(m, b)
}
func (m *CommandSetShowPageNumbersValueArchive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandSetShowPageNumbersValueArchive.Marshal(b, m, deterministic)
}
func (m *CommandSetShowPageNumbersValueArchive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandSetShowPageNumbersValueArchive.Merge(m, src)
}
func (m *CommandSetShowPageNumbersValueArchive) XXX_Size() int {
	return xxx_messageInfo_CommandSetShowPageNumbersValueArchive.Size(m)
}
func (m *CommandSetShowPageNumbersValueArchive) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandSetShowPageNumbersValueArchive.DiscardUnknown(m)
}

var xxx_messageInfo_CommandSetShowPageNumbersValueArchive proto.InternalMessageInfo

func (m *CommandSetShowPageNumbersValueArchive) GetShowPageNumbers() bool {
	if m != nil && m.ShowPageNumbers != nil {
		return *m.ShowPageNumbers
	}
	return false
}

func (m *CommandSetShowPageNumbersValueArchive) GetSheet() *Reference {
	if m != nil {
		return m.Sheet
	}
	return nil
}

func (m *CommandSetShowPageNumbersValueArchive) GetSuper() *CommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

type CommandSetRepeatingHeadersValueArchive struct {
	ShowRepeatingHeaders *bool           `protobuf:"varint,1,req,name=show_repeating_headers,json=showRepeatingHeaders" json:"show_repeating_headers,omitempty"`
	Sheet                *Reference      `protobuf:"bytes,2,req,name=sheet" json:"sheet,omitempty"`
	Super                *CommandArchive `protobuf:"bytes,3,req,name=super" json:"super,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CommandSetRepeatingHeadersValueArchive) Reset() {
	*m = CommandSetRepeatingHeadersValueArchive{}
}
func (m *CommandSetRepeatingHeadersValueArchive) String() string { return proto.CompactTextString(m) }
func (*CommandSetRepeatingHeadersValueArchive) ProtoMessage()    {}
func (*CommandSetRepeatingHeadersValueArchive) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0bf61362014be2a, []int{12}
}

func (m *CommandSetRepeatingHeadersValueArchive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandSetRepeatingHeadersValueArchive.Unmarshal(m, b)
}
func (m *CommandSetRepeatingHeadersValueArchive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandSetRepeatingHeadersValueArchive.Marshal(b, m, deterministic)
}
func (m *CommandSetRepeatingHeadersValueArchive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandSetRepeatingHeadersValueArchive.Merge(m, src)
}
func (m *CommandSetRepeatingHeadersValueArchive) XXX_Size() int {
	return xxx_messageInfo_CommandSetRepeatingHeadersValueArchive.Size(m)
}
func (m *CommandSetRepeatingHeadersValueArchive) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandSetRepeatingHeadersValueArchive.DiscardUnknown(m)
}

var xxx_messageInfo_CommandSetRepeatingHeadersValueArchive proto.InternalMessageInfo

func (m *CommandSetRepeatingHeadersValueArchive) GetShowRepeatingHeaders() bool {
	if m != nil && m.ShowRepeatingHeaders != nil {
		return *m.ShowRepeatingHeaders
	}
	return false
}

func (m *CommandSetRepeatingHeadersValueArchive) GetSheet() *Reference {
	if m != nil {
		return m.Sheet
	}
	return nil
}

func (m *CommandSetRepeatingHeadersValueArchive) GetSuper() *CommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

type CommandSetContentScaleArchive struct {
	IsAutofitOn          *bool           `protobuf:"varint,1,req,name=is_autofit_on,json=isAutofitOn" json:"is_autofit_on,omitempty"`
	OldContentScale      *float32        `protobuf:"fixed32,2,req,name=old_content_scale,json=oldContentScale" json:"old_content_scale,omitempty"`
	NewContentScale      *float32        `protobuf:"fixed32,3,opt,name=new_content_scale,json=newContentScale" json:"new_content_scale,omitempty"`
	Sheet                *Reference      `protobuf:"bytes,4,req,name=sheet" json:"sheet,omitempty"`
	Super                *CommandArchive `protobuf:"bytes,5,req,name=super" json:"super,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CommandSetContentScaleArchive) Reset()         { *m = CommandSetContentScaleArchive{} }
func (m *CommandSetContentScaleArchive) String() string { return proto.CompactTextString(m) }
func (*CommandSetContentScaleArchive) ProtoMessage()    {}
func (*CommandSetContentScaleArchive) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0bf61362014be2a, []int{13}
}

func (m *CommandSetContentScaleArchive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandSetContentScaleArchive.Unmarshal(m, b)
}
func (m *CommandSetContentScaleArchive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandSetContentScaleArchive.Marshal(b, m, deterministic)
}
func (m *CommandSetContentScaleArchive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandSetContentScaleArchive.Merge(m, src)
}
func (m *CommandSetContentScaleArchive) XXX_Size() int {
	return xxx_messageInfo_CommandSetContentScaleArchive.Size(m)
}
func (m *CommandSetContentScaleArchive) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandSetContentScaleArchive.DiscardUnknown(m)
}

var xxx_messageInfo_CommandSetContentScaleArchive proto.InternalMessageInfo

func (m *CommandSetContentScaleArchive) GetIsAutofitOn() bool {
	if m != nil && m.IsAutofitOn != nil {
		return *m.IsAutofitOn
	}
	return false
}

func (m *CommandSetContentScaleArchive) GetOldContentScale() float32 {
	if m != nil && m.OldContentScale != nil {
		return *m.OldContentScale
	}
	return 0
}

func (m *CommandSetContentScaleArchive) GetNewContentScale() float32 {
	if m != nil && m.NewContentScale != nil {
		return *m.NewContentScale
	}
	return 0
}

func (m *CommandSetContentScaleArchive) GetSheet() *Reference {
	if m != nil {
		return m.Sheet
	}
	return nil
}

func (m *CommandSetContentScaleArchive) GetSuper() *CommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

type CommandSetAutofitValueArchive struct {
	OldContentScale      *float32        `protobuf:"fixed32,1,req,name=old_content_scale,json=oldContentScale" json:"old_content_scale,omitempty"`
	Sheet                *Reference      `protobuf:"bytes,2,req,name=sheet" json:"sheet,omitempty"`
	Super                *CommandArchive `protobuf:"bytes,3,req,name=super" json:"super,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CommandSetAutofitValueArchive) Reset()         { *m = CommandSetAutofitValueArchive{} }
func (m *CommandSetAutofitValueArchive) String() string { return proto.CompactTextString(m) }
func (*CommandSetAutofitValueArchive) ProtoMessage()    {}
func (*CommandSetAutofitValueArchive) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0bf61362014be2a, []int{14}
}

func (m *CommandSetAutofitValueArchive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandSetAutofitValueArchive.Unmarshal(m, b)
}
func (m *CommandSetAutofitValueArchive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandSetAutofitValueArchive.Marshal(b, m, deterministic)
}
func (m *CommandSetAutofitValueArchive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandSetAutofitValueArchive.Merge(m, src)
}
func (m *CommandSetAutofitValueArchive) XXX_Size() int {
	return xxx_messageInfo_CommandSetAutofitValueArchive.Size(m)
}
func (m *CommandSetAutofitValueArchive) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandSetAutofitValueArchive.DiscardUnknown(m)
}

var xxx_messageInfo_CommandSetAutofitValueArchive proto.InternalMessageInfo

func (m *CommandSetAutofitValueArchive) GetOldContentScale() float32 {
	if m != nil && m.OldContentScale != nil {
		return *m.OldContentScale
	}
	return 0
}

func (m *CommandSetAutofitValueArchive) GetSheet() *Reference {
	if m != nil {
		return m.Sheet
	}
	return nil
}

func (m *CommandSetAutofitValueArchive) GetSuper() *CommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

type CommandSetDocumentPrinterOptions struct {
	PrinterId            *string         `protobuf:"bytes,1,req,name=printer_id,json=printerId" json:"printer_id,omitempty"`
	PaperId              *string         `protobuf:"bytes,2,req,name=paper_id,json=paperId" json:"paper_id,omitempty"`
	PageSize             *Size           `protobuf:"bytes,3,req,name=page_size,json=pageSize" json:"page_size,omitempty"`
	Super                *CommandArchive `protobuf:"bytes,4,req,name=super" json:"super,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CommandSetDocumentPrinterOptions) Reset()         { *m = CommandSetDocumentPrinterOptions{} }
func (m *CommandSetDocumentPrinterOptions) String() string { return proto.CompactTextString(m) }
func (*CommandSetDocumentPrinterOptions) ProtoMessage()    {}
func (*CommandSetDocumentPrinterOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0bf61362014be2a, []int{15}
}

func (m *CommandSetDocumentPrinterOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandSetDocumentPrinterOptions.Unmarshal(m, b)
}
func (m *CommandSetDocumentPrinterOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandSetDocumentPrinterOptions.Marshal(b, m, deterministic)
}
func (m *CommandSetDocumentPrinterOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandSetDocumentPrinterOptions.Merge(m, src)
}
func (m *CommandSetDocumentPrinterOptions) XXX_Size() int {
	return xxx_messageInfo_CommandSetDocumentPrinterOptions.Size(m)
}
func (m *CommandSetDocumentPrinterOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandSetDocumentPrinterOptions.DiscardUnknown(m)
}

var xxx_messageInfo_CommandSetDocumentPrinterOptions proto.InternalMessageInfo

func (m *CommandSetDocumentPrinterOptions) GetPrinterId() string {
	if m != nil && m.PrinterId != nil {
		return *m.PrinterId
	}
	return ""
}

func (m *CommandSetDocumentPrinterOptions) GetPaperId() string {
	if m != nil && m.PaperId != nil {
		return *m.PaperId
	}
	return ""
}

func (m *CommandSetDocumentPrinterOptions) GetPageSize() *Size {
	if m != nil {
		return m.PageSize
	}
	return nil
}

func (m *CommandSetDocumentPrinterOptions) GetSuper() *CommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

type CommandEnterPrintPreviewModeArchive struct {
	Super                *CommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CommandEnterPrintPreviewModeArchive) Reset()         { *m = CommandEnterPrintPreviewModeArchive{} }
func (m *CommandEnterPrintPreviewModeArchive) String() string { return proto.CompactTextString(m) }
func (*CommandEnterPrintPreviewModeArchive) ProtoMessage()    {}
func (*CommandEnterPrintPreviewModeArchive) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0bf61362014be2a, []int{16}
}

func (m *CommandEnterPrintPreviewModeArchive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandEnterPrintPreviewModeArchive.Unmarshal(m, b)
}
func (m *CommandEnterPrintPreviewModeArchive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandEnterPrintPreviewModeArchive.Marshal(b, m, deterministic)
}
func (m *CommandEnterPrintPreviewModeArchive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandEnterPrintPreviewModeArchive.Merge(m, src)
}
func (m *CommandEnterPrintPreviewModeArchive) XXX_Size() int {
	return xxx_messageInfo_CommandEnterPrintPreviewModeArchive.Size(m)
}
func (m *CommandEnterPrintPreviewModeArchive) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandEnterPrintPreviewModeArchive.DiscardUnknown(m)
}

var xxx_messageInfo_CommandEnterPrintPreviewModeArchive proto.InternalMessageInfo

func (m *CommandEnterPrintPreviewModeArchive) GetSuper() *CommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

type CommandExitPrintPreviewModeArchive struct {
	Super                *CommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CommandExitPrintPreviewModeArchive) Reset()         { *m = CommandExitPrintPreviewModeArchive{} }
func (m *CommandExitPrintPreviewModeArchive) String() string { return proto.CompactTextString(m) }
func (*CommandExitPrintPreviewModeArchive) ProtoMessage()    {}
func (*CommandExitPrintPreviewModeArchive) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0bf61362014be2a, []int{17}
}

func (m *CommandExitPrintPreviewModeArchive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandExitPrintPreviewModeArchive.Unmarshal(m, b)
}
func (m *CommandExitPrintPreviewModeArchive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandExitPrintPreviewModeArchive.Marshal(b, m, deterministic)
}
func (m *CommandExitPrintPreviewModeArchive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandExitPrintPreviewModeArchive.Merge(m, src)
}
func (m *CommandExitPrintPreviewModeArchive) XXX_Size() int {
	return xxx_messageInfo_CommandExitPrintPreviewModeArchive.Size(m)
}
func (m *CommandExitPrintPreviewModeArchive) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandExitPrintPreviewModeArchive.DiscardUnknown(m)
}

var xxx_messageInfo_CommandExitPrintPreviewModeArchive proto.InternalMessageInfo

func (m *CommandExitPrintPreviewModeArchive) GetSuper() *CommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

type CommandPasteDrawablesArchive struct {
	Super                *CommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	Sheet                *Reference      `protobuf:"bytes,2,req,name=sheet" json:"sheet,omitempty"`
	Drawables            []*Reference    `protobuf:"bytes,3,rep,name=drawables" json:"drawables,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CommandPasteDrawablesArchive) Reset()         { *m = CommandPasteDrawablesArchive{} }
func (m *CommandPasteDrawablesArchive) String() string { return proto.CompactTextString(m) }
func (*CommandPasteDrawablesArchive) ProtoMessage()    {}
func (*CommandPasteDrawablesArchive) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0bf61362014be2a, []int{18}
}

func (m *CommandPasteDrawablesArchive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandPasteDrawablesArchive.Unmarshal(m, b)
}
func (m *CommandPasteDrawablesArchive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandPasteDrawablesArchive.Marshal(b, m, deterministic)
}
func (m *CommandPasteDrawablesArchive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandPasteDrawablesArchive.Merge(m, src)
}
func (m *CommandPasteDrawablesArchive) XXX_Size() int {
	return xxx_messageInfo_CommandPasteDrawablesArchive.Size(m)
}
func (m *CommandPasteDrawablesArchive) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandPasteDrawablesArchive.DiscardUnknown(m)
}

var xxx_messageInfo_CommandPasteDrawablesArchive proto.InternalMessageInfo

func (m *CommandPasteDrawablesArchive) GetSuper() *CommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *CommandPasteDrawablesArchive) GetSheet() *Reference {
	if m != nil {
		return m.Sheet
	}
	return nil
}

func (m *CommandPasteDrawablesArchive) GetDrawables() []*Reference {
	if m != nil {
		return m.Drawables
	}
	return nil
}

type CommandPasteSheetArchive struct {
	Super                *CommandArchive      `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	Document             *Reference           `protobuf:"bytes,2,req,name=document" json:"document,omitempty"`
	Sheet                *Reference           `protobuf:"bytes,3,req,name=sheet" json:"sheet,omitempty"`
	SheetUistate         *SheetUIStateArchive `protobuf:"bytes,4,opt,name=sheet_uistate,json=sheetUistate" json:"sheet_uistate,omitempty"`
	SheetIndex           *uint32              `protobuf:"varint,5,req,name=sheetIndex" json:"sheetIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CommandPasteSheetArchive) Reset()         { *m = CommandPasteSheetArchive{} }
func (m *CommandPasteSheetArchive) String() string { return proto.CompactTextString(m) }
func (*CommandPasteSheetArchive) ProtoMessage()    {}
func (*CommandPasteSheetArchive) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0bf61362014be2a, []int{19}
}

func (m *CommandPasteSheetArchive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandPasteSheetArchive.Unmarshal(m, b)
}
func (m *CommandPasteSheetArchive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandPasteSheetArchive.Marshal(b, m, deterministic)
}
func (m *CommandPasteSheetArchive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandPasteSheetArchive.Merge(m, src)
}
func (m *CommandPasteSheetArchive) XXX_Size() int {
	return xxx_messageInfo_CommandPasteSheetArchive.Size(m)
}
func (m *CommandPasteSheetArchive) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandPasteSheetArchive.DiscardUnknown(m)
}

var xxx_messageInfo_CommandPasteSheetArchive proto.InternalMessageInfo

func (m *CommandPasteSheetArchive) GetSuper() *CommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *CommandPasteSheetArchive) GetDocument() *Reference {
	if m != nil {
		return m.Document
	}
	return nil
}

func (m *CommandPasteSheetArchive) GetSheet() *Reference {
	if m != nil {
		return m.Sheet
	}
	return nil
}

func (m *CommandPasteSheetArchive) GetSheetUistate() *SheetUIStateArchive {
	if m != nil {
		return m.SheetUistate
	}
	return nil
}

func (m *CommandPasteSheetArchive) GetSheetIndex() uint32 {
	if m != nil && m.SheetIndex != nil {
		return *m.SheetIndex
	}
	return 0
}

type CommandReorderSidebarItemChildrenAchive struct {
	Super                *CommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	Sheet                *Reference      `protobuf:"bytes,2,req,name=sheet" json:"sheet,omitempty"`
	OldChildren          []*Reference    `protobuf:"bytes,3,rep,name=old_children,json=oldChildren" json:"old_children,omitempty"`
	NewChildren          []*Reference    `protobuf:"bytes,4,rep,name=new_children,json=newChildren" json:"new_children,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CommandReorderSidebarItemChildrenAchive) Reset() {
	*m = CommandReorderSidebarItemChildrenAchive{}
}
func (m *CommandReorderSidebarItemChildrenAchive) String() string { return proto.CompactTextString(m) }
func (*CommandReorderSidebarItemChildrenAchive) ProtoMessage()    {}
func (*CommandReorderSidebarItemChildrenAchive) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0bf61362014be2a, []int{20}
}

func (m *CommandReorderSidebarItemChildrenAchive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandReorderSidebarItemChildrenAchive.Unmarshal(m, b)
}
func (m *CommandReorderSidebarItemChildrenAchive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandReorderSidebarItemChildrenAchive.Marshal(b, m, deterministic)
}
func (m *CommandReorderSidebarItemChildrenAchive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandReorderSidebarItemChildrenAchive.Merge(m, src)
}
func (m *CommandReorderSidebarItemChildrenAchive) XXX_Size() int {
	return xxx_messageInfo_CommandReorderSidebarItemChildrenAchive.Size(m)
}
func (m *CommandReorderSidebarItemChildrenAchive) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandReorderSidebarItemChildrenAchive.DiscardUnknown(m)
}

var xxx_messageInfo_CommandReorderSidebarItemChildrenAchive proto.InternalMessageInfo

func (m *CommandReorderSidebarItemChildrenAchive) GetSuper() *CommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *CommandReorderSidebarItemChildrenAchive) GetSheet() *Reference {
	if m != nil {
		return m.Sheet
	}
	return nil
}

func (m *CommandReorderSidebarItemChildrenAchive) GetOldChildren() []*Reference {
	if m != nil {
		return m.OldChildren
	}
	return nil
}

func (m *CommandReorderSidebarItemChildrenAchive) GetNewChildren() []*Reference {
	if m != nil {
		return m.NewChildren
	}
	return nil
}

type CommandChartMediatorSetEditingState struct {
	Super                *ChartCommandArchive         `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	OldFormulas          *ChartMediatorFormulaStorage `protobuf:"bytes,3,opt,name=old_formulas,json=oldFormulas" json:"old_formulas,omitempty"`
	NewFormulas          *ChartMediatorFormulaStorage `protobuf:"bytes,4,opt,name=new_formulas,json=newFormulas" json:"new_formulas,omitempty"`
	OldDirection         *int32                       `protobuf:"varint,5,opt,name=old_direction,json=oldDirection" json:"old_direction,omitempty"`
	NewDirection         *int32                       `protobuf:"varint,6,opt,name=new_direction,json=newDirection" json:"new_direction,omitempty"`
	OldScatterFormat     *int32                       `protobuf:"varint,7,opt,name=old_scatter_format,json=oldScatterFormat" json:"old_scatter_format,omitempty"`
	NewScatterFormat     *int32                       `protobuf:"varint,8,opt,name=new_scatter_format,json=newScatterFormat" json:"new_scatter_format,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *CommandChartMediatorSetEditingState) Reset()         { *m = CommandChartMediatorSetEditingState{} }
func (m *CommandChartMediatorSetEditingState) String() string { return proto.CompactTextString(m) }
func (*CommandChartMediatorSetEditingState) ProtoMessage()    {}
func (*CommandChartMediatorSetEditingState) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0bf61362014be2a, []int{21}
}

func (m *CommandChartMediatorSetEditingState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandChartMediatorSetEditingState.Unmarshal(m, b)
}
func (m *CommandChartMediatorSetEditingState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandChartMediatorSetEditingState.Marshal(b, m, deterministic)
}
func (m *CommandChartMediatorSetEditingState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandChartMediatorSetEditingState.Merge(m, src)
}
func (m *CommandChartMediatorSetEditingState) XXX_Size() int {
	return xxx_messageInfo_CommandChartMediatorSetEditingState.Size(m)
}
func (m *CommandChartMediatorSetEditingState) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandChartMediatorSetEditingState.DiscardUnknown(m)
}

var xxx_messageInfo_CommandChartMediatorSetEditingState proto.InternalMessageInfo

func (m *CommandChartMediatorSetEditingState) GetSuper() *ChartCommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *CommandChartMediatorSetEditingState) GetOldFormulas() *ChartMediatorFormulaStorage {
	if m != nil {
		return m.OldFormulas
	}
	return nil
}

func (m *CommandChartMediatorSetEditingState) GetNewFormulas() *ChartMediatorFormulaStorage {
	if m != nil {
		return m.NewFormulas
	}
	return nil
}

func (m *CommandChartMediatorSetEditingState) GetOldDirection() int32 {
	if m != nil && m.OldDirection != nil {
		return *m.OldDirection
	}
	return 0
}

func (m *CommandChartMediatorSetEditingState) GetNewDirection() int32 {
	if m != nil && m.NewDirection != nil {
		return *m.NewDirection
	}
	return 0
}

func (m *CommandChartMediatorSetEditingState) GetOldScatterFormat() int32 {
	if m != nil && m.OldScatterFormat != nil {
		return *m.OldScatterFormat
	}
	return 0
}

func (m *CommandChartMediatorSetEditingState) GetNewScatterFormat() int32 {
	if m != nil && m.NewScatterFormat != nil {
		return *m.NewScatterFormat
	}
	return 0
}

type CommandChartMediatorUpdateForEntityDelete struct {
	Super                *ChartCommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	Cmd                  *Reference           `protobuf:"bytes,3,opt,name=cmd" json:"cmd,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CommandChartMediatorUpdateForEntityDelete) Reset() {
	*m = CommandChartMediatorUpdateForEntityDelete{}
}
func (m *CommandChartMediatorUpdateForEntityDelete) String() string { return proto.CompactTextString(m) }
func (*CommandChartMediatorUpdateForEntityDelete) ProtoMessage()    {}
func (*CommandChartMediatorUpdateForEntityDelete) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0bf61362014be2a, []int{22}
}

func (m *CommandChartMediatorUpdateForEntityDelete) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandChartMediatorUpdateForEntityDelete.Unmarshal(m, b)
}
func (m *CommandChartMediatorUpdateForEntityDelete) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandChartMediatorUpdateForEntityDelete.Marshal(b, m, deterministic)
}
func (m *CommandChartMediatorUpdateForEntityDelete) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandChartMediatorUpdateForEntityDelete.Merge(m, src)
}
func (m *CommandChartMediatorUpdateForEntityDelete) XXX_Size() int {
	return xxx_messageInfo_CommandChartMediatorUpdateForEntityDelete.Size(m)
}
func (m *CommandChartMediatorUpdateForEntityDelete) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandChartMediatorUpdateForEntityDelete.DiscardUnknown(m)
}

var xxx_messageInfo_CommandChartMediatorUpdateForEntityDelete proto.InternalMessageInfo

func (m *CommandChartMediatorUpdateForEntityDelete) GetSuper() *ChartCommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *CommandChartMediatorUpdateForEntityDelete) GetCmd() *Reference {
	if m != nil {
		return m.Cmd
	}
	return nil
}

type ChartCommandSetSeriesNameArchive struct {
	Super                *ChartCommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	Mediator             *Reference           `protobuf:"bytes,2,req,name=mediator" json:"mediator,omitempty"`
	Seriesindex          *uint32              `protobuf:"varint,3,req,name=seriesindex" json:"seriesindex,omitempty"`
	OldFormula           *FormulaArchive      `protobuf:"bytes,4,opt,name=old_formula,json=oldFormula" json:"old_formula,omitempty"`
	NewFormula           *FormulaArchive      `protobuf:"bytes,5,opt,name=new_formula,json=newFormula" json:"new_formula,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ChartCommandSetSeriesNameArchive) Reset()         { *m = ChartCommandSetSeriesNameArchive{} }
func (m *ChartCommandSetSeriesNameArchive) String() string { return proto.CompactTextString(m) }
func (*ChartCommandSetSeriesNameArchive) ProtoMessage()    {}
func (*ChartCommandSetSeriesNameArchive) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0bf61362014be2a, []int{23}
}

func (m *ChartCommandSetSeriesNameArchive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChartCommandSetSeriesNameArchive.Unmarshal(m, b)
}
func (m *ChartCommandSetSeriesNameArchive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChartCommandSetSeriesNameArchive.Marshal(b, m, deterministic)
}
func (m *ChartCommandSetSeriesNameArchive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChartCommandSetSeriesNameArchive.Merge(m, src)
}
func (m *ChartCommandSetSeriesNameArchive) XXX_Size() int {
	return xxx_messageInfo_ChartCommandSetSeriesNameArchive.Size(m)
}
func (m *ChartCommandSetSeriesNameArchive) XXX_DiscardUnknown() {
	xxx_messageInfo_ChartCommandSetSeriesNameArchive.DiscardUnknown(m)
}

var xxx_messageInfo_ChartCommandSetSeriesNameArchive proto.InternalMessageInfo

func (m *ChartCommandSetSeriesNameArchive) GetSuper() *ChartCommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *ChartCommandSetSeriesNameArchive) GetMediator() *Reference {
	if m != nil {
		return m.Mediator
	}
	return nil
}

func (m *ChartCommandSetSeriesNameArchive) GetSeriesindex() uint32 {
	if m != nil && m.Seriesindex != nil {
		return *m.Seriesindex
	}
	return 0
}

func (m *ChartCommandSetSeriesNameArchive) GetOldFormula() *FormulaArchive {
	if m != nil {
		return m.OldFormula
	}
	return nil
}

func (m *ChartCommandSetSeriesNameArchive) GetNewFormula() *FormulaArchive {
	if m != nil {
		return m.NewFormula
	}
	return nil
}

type ChartCommandSelectionBehaviorArchive struct {
	DrawableInfo         *Reference             `protobuf:"bytes,1,req,name=drawable_info,json=drawableInfo" json:"drawable_info,omitempty"`
	BeginSelection       *ChartSelectionArchive `protobuf:"bytes,2,opt,name=begin_selection,json=beginSelection" json:"begin_selection,omitempty"`
	EndSelection         *ChartSelectionArchive `protobuf:"bytes,3,opt,name=end_selection,json=endSelection" json:"end_selection,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ChartCommandSelectionBehaviorArchive) Reset()         { *m = ChartCommandSelectionBehaviorArchive{} }
func (m *ChartCommandSelectionBehaviorArchive) String() string { return proto.CompactTextString(m) }
func (*ChartCommandSelectionBehaviorArchive) ProtoMessage()    {}
func (*ChartCommandSelectionBehaviorArchive) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0bf61362014be2a, []int{24}
}

func (m *ChartCommandSelectionBehaviorArchive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChartCommandSelectionBehaviorArchive.Unmarshal(m, b)
}
func (m *ChartCommandSelectionBehaviorArchive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChartCommandSelectionBehaviorArchive.Marshal(b, m, deterministic)
}
func (m *ChartCommandSelectionBehaviorArchive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChartCommandSelectionBehaviorArchive.Merge(m, src)
}
func (m *ChartCommandSelectionBehaviorArchive) XXX_Size() int {
	return xxx_messageInfo_ChartCommandSelectionBehaviorArchive.Size(m)
}
func (m *ChartCommandSelectionBehaviorArchive) XXX_DiscardUnknown() {
	xxx_messageInfo_ChartCommandSelectionBehaviorArchive.DiscardUnknown(m)
}

var xxx_messageInfo_ChartCommandSelectionBehaviorArchive proto.InternalMessageInfo

func (m *ChartCommandSelectionBehaviorArchive) GetDrawableInfo() *Reference {
	if m != nil {
		return m.DrawableInfo
	}
	return nil
}

func (m *ChartCommandSelectionBehaviorArchive) GetBeginSelection() *ChartSelectionArchive {
	if m != nil {
		return m.BeginSelection
	}
	return nil
}

func (m *ChartCommandSelectionBehaviorArchive) GetEndSelection() *ChartSelectionArchive {
	if m != nil {
		return m.EndSelection
	}
	return nil
}

func init() {
	proto.RegisterType((*SheetCommandSelectionBehaviorArchive)(nil), "TN.SheetCommandSelectionBehaviorArchive")
	proto.RegisterType((*CommandFormChooseTargetTableArchive)(nil), "TN.CommandFormChooseTargetTableArchive")
	proto.RegisterType((*CommandSheetInsertDrawablesArchive)(nil), "TN.CommandSheetInsertDrawablesArchive")
	proto.RegisterType((*CommandSheetRemoveDrawablesArchive)(nil), "TN.CommandSheetRemoveDrawablesArchive")
	proto.RegisterType((*CommandSheetMoveDrawableZOrderArchive)(nil), "TN.CommandSheetMoveDrawableZOrderArchive")
	proto.RegisterType((*CommandDocumentInsertSheetArchive)(nil), "TN.CommandDocumentInsertSheetArchive")
	proto.RegisterType((*CommandDocumentRemoveSheetArchive)(nil), "TN.CommandDocumentRemoveSheetArchive")
	proto.RegisterType((*CommandDocumentReplaceLastSheetArchive)(nil), "TN.CommandDocumentReplaceLastSheetArchive")
	proto.RegisterType((*CommandDocumentReorderSheetArchive)(nil), "TN.CommandDocumentReorderSheetArchive")
	proto.RegisterType((*CommandSetSheetNameArchive)(nil), "TN.CommandSetSheetNameArchive")
	proto.RegisterType((*CommandSetPageOrientationArchive)(nil), "TN.CommandSetPageOrientationArchive")
	proto.RegisterType((*CommandSetShowPageNumbersValueArchive)(nil), "TN.CommandSetShowPageNumbersValueArchive")
	proto.RegisterType((*CommandSetRepeatingHeadersValueArchive)(nil), "TN.CommandSetRepeatingHeadersValueArchive")
	proto.RegisterType((*CommandSetContentScaleArchive)(nil), "TN.CommandSetContentScaleArchive")
	proto.RegisterType((*CommandSetAutofitValueArchive)(nil), "TN.CommandSetAutofitValueArchive")
	proto.RegisterType((*CommandSetDocumentPrinterOptions)(nil), "TN.CommandSetDocumentPrinterOptions")
	proto.RegisterType((*CommandEnterPrintPreviewModeArchive)(nil), "TN.CommandEnterPrintPreviewModeArchive")
	proto.RegisterType((*CommandExitPrintPreviewModeArchive)(nil), "TN.CommandExitPrintPreviewModeArchive")
	proto.RegisterType((*CommandPasteDrawablesArchive)(nil), "TN.CommandPasteDrawablesArchive")
	proto.RegisterType((*CommandPasteSheetArchive)(nil), "TN.CommandPasteSheetArchive")
	proto.RegisterType((*CommandReorderSidebarItemChildrenAchive)(nil), "TN.CommandReorderSidebarItemChildrenAchive")
	proto.RegisterType((*CommandChartMediatorSetEditingState)(nil), "TN.CommandChartMediatorSetEditingState")
	proto.RegisterType((*CommandChartMediatorUpdateForEntityDelete)(nil), "TN.CommandChartMediatorUpdateForEntityDelete")
	proto.RegisterType((*ChartCommandSetSeriesNameArchive)(nil), "TN.ChartCommandSetSeriesNameArchive")
	proto.RegisterType((*ChartCommandSelectionBehaviorArchive)(nil), "TN.ChartCommandSelectionBehaviorArchive")
}

func init() { proto.RegisterFile("TNCommandArchives.proto", fileDescriptor_b0bf61362014be2a) }

var fileDescriptor_b0bf61362014be2a = []byte{
	// 1584 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x58, 0xbb, 0x6f, 0x1b, 0x47,
	0x1a, 0xc7, 0x92, 0xa2, 0x45, 0x0e, 0x45, 0xc9, 0x5e, 0x0b, 0x67, 0x4a, 0xb0, 0xef, 0xe8, 0xb5,
	0xcf, 0x96, 0x7d, 0x3e, 0x1e, 0xce, 0x8e, 0x91, 0x14, 0x41, 0x0c, 0x9b, 0x92, 0x60, 0xc2, 0x91,
	0x44, 0xec, 0x52, 0x2e, 0xd2, 0x2c, 0x46, 0xdc, 0x8f, 0xe4, 0x00, 0xe4, 0x0e, 0x31, 0x33, 0x14,
	0x1d, 0x17, 0xa9, 0x02, 0xa4, 0xcc, 0x3f, 0x90, 0x00, 0x09, 0x90, 0x22, 0x5d, 0x9a, 0x20, 0xff,
	0x49, 0x80, 0x74, 0x09, 0x90, 0x36, 0x4d, 0x8a, 0xf4, 0xc1, 0x3c, 0xf6, 0x45, 0x91, 0xa2, 0x64,
	0x48, 0x1d, 0xf7, 0x9b, 0xdf, 0xf7, 0x7e, 0xcc, 0x37, 0x44, 0x37, 0xda, 0xfb, 0x0d, 0x3a, 0x1c,
	0xe2, 0x30, 0x78, 0xce, 0x3a, 0x7d, 0x72, 0x0c, 0xbc, 0x3e, 0x62, 0x54, 0x50, 0x3b, 0xd7, 0xde,
	0xdf, 0xbc, 0xd6, 0xf6, 0x5a, 0x7b, 0xc0, 0x39, 0xee, 0x45, 0x64, 0x49, 0x7a, 0x95, 0x45, 0x6e,
	0x6e, 0xb4, 0xbd, 0xc6, 0xcb, 0x99, 0x42, 0x36, 0xed, 0xb6, 0xd7, 0xd8, 0x99, 0xa2, 0x5d, 0x6d,
	0xef, 0x67, 0x29, 0x8e, 0x8f, 0xee, 0x7a, 0x7d, 0x00, 0x61, 0x64, 0x78, 0x30, 0x80, 0x8e, 0x20,
	0x34, 0x7c, 0x01, 0x7d, 0x7c, 0x4c, 0x28, 0x33, 0x70, 0xfb, 0x7d, 0xb4, 0xc6, 0x25, 0xce, 0xe7,
	0x11, 0xa2, 0x6a, 0xd5, 0xac, 0xad, 0xf2, 0xe3, 0xd5, 0x7a, 0xdb, 0x6b, 0xd5, 0x5d, 0xe8, 0x02,
	0x83, 0xb0, 0x03, 0xee, 0xaa, 0x82, 0xc5, 0x72, 0x9c, 0x9f, 0x72, 0xe8, 0x8e, 0x11, 0xbe, 0x4b,
	0xd9, 0xb0, 0xd1, 0xa7, 0x94, 0x43, 0x1b, 0xb3, 0x1e, 0x88, 0x36, 0x3e, 0x1a, 0x40, 0xa4, 0xe0,
	0x01, 0x2a, 0xf0, 0xf1, 0x08, 0x58, 0xd5, 0xaa, 0xe5, 0xb6, 0xca, 0x8f, 0xaf, 0xd7, 0xdb, 0xde,
	0xab, 0x7a, 0xd6, 0x33, 0x57, 0x23, 0xec, 0x3a, 0x2a, 0x0a, 0xc9, 0xea, 0x93, 0xa0, 0x9a, 0x53,
	0x46, 0x48, 0x74, 0x63, 0xa7, 0xde, 0xd8, 0x3d, 0x3c, 0x6c, 0x6e, 0x47, 0xe8, 0x65, 0x05, 0x6a,
	0x06, 0xf6, 0x33, 0x74, 0x6d, 0xc4, 0xe0, 0x98, 0xd0, 0x31, 0xf7, 0x63, 0xc6, 0xfc, 0x7c, 0xc6,
	0xb5, 0x08, 0xdd, 0x36, 0x02, 0x6e, 0x21, 0xa4, 0x9d, 0x0f, 0xf1, 0x10, 0xaa, 0x4b, 0x35, 0x6b,
	0xab, 0xe4, 0x96, 0x14, 0x65, 0x1f, 0x0f, 0xc1, 0xae, 0xa3, 0xeb, 0xb1, 0xfc, 0x14, 0xae, 0xa0,
	0x70, 0xb1, 0x6a, 0x2f, 0xc6, 0xdf, 0x45, 0x05, 0x05, 0xab, 0x5e, 0x51, 0xae, 0x4e, 0x47, 0x50,
	0x1f, 0x3a, 0xdf, 0xe7, 0x90, 0x13, 0x65, 0x45, 0x12, 0x9a, 0x21, 0x07, 0x26, 0xb6, 0x19, 0x9e,
	0x48, 0xab, 0x78, 0x14, 0xb7, 0x58, 0x98, 0x75, 0x8a, 0x30, 0xfb, 0x11, 0x2a, 0x05, 0x11, 0x67,
	0x35, 0x57, 0xcb, 0xcf, 0x40, 0x26, 0x00, 0xfb, 0x09, 0xaa, 0x8c, 0x18, 0x3d, 0x26, 0x01, 0x30,
	0x7f, 0x1c, 0x06, 0xd4, 0x04, 0x6b, 0x9a, 0x63, 0x25, 0x02, 0x1d, 0x86, 0x01, 0x4d, 0x12, 0xb8,
	0xb4, 0x30, 0x81, 0x55, 0xb4, 0xdc, 0xa5, 0x6c, 0x9b, 0xe1, 0x9e, 0x0a, 0x52, 0xd1, 0x8d, 0x3e,
	0xed, 0x4d, 0x54, 0xec, 0x52, 0xd6, 0xc2, 0x5c, 0x40, 0x75, 0x59, 0x1d, 0xc5, 0xdf, 0x92, 0x0b,
	0x8b, 0x66, 0x18, 0xc0, 0x9b, 0xea, 0x95, 0x9a, 0xb5, 0x55, 0x70, 0xa3, 0x4f, 0xe7, 0x8b, 0x7c,
	0x36, 0x54, 0x2e, 0x0c, 0xe9, 0x31, 0x9c, 0x08, 0xd5, 0x39, 0x4a, 0x2c, 0x8e, 0x6a, 0xee, 0xb4,
	0xa8, 0x7e, 0x80, 0xd6, 0x38, 0x65, 0x02, 0x82, 0x58, 0x55, 0x35, 0x3f, 0x33, 0xb6, 0xd3, 0x30,
	0xd9, 0x4e, 0x51, 0xb8, 0x9b, 0x61, 0x40, 0x3a, 0xc0, 0x4d, 0xd8, 0x2a, 0x8a, 0x53, 0xb9, 0xe5,
	0x81, 0x70, 0xa7, 0x51, 0xf6, 0x0e, 0xba, 0x41, 0x07, 0x81, 0x29, 0x33, 0x4e, 0x02, 0x38, 0xc2,
	0xcc, 0xa7, 0x2c, 0x00, 0x56, 0x2d, 0xcc, 0x54, 0xbd, 0x4e, 0x07, 0x3a, 0x28, 0x9e, 0x06, 0x1f,
	0x48, 0xac, 0xfd, 0x1a, 0xd5, 0xba, 0x94, 0x0d, 0xc7, 0x03, 0xec, 0x33, 0x98, 0x30, 0x22, 0xc0,
	0xef, 0xe8, 0x40, 0xf8, 0x5d, 0x6a, 0x92, 0x7e, 0x65, 0x66, 0xd2, 0x6f, 0x1a, 0x3e, 0x57, 0xb3,
	0x25, 0xad, 0x2d, 0x8b, 0xc0, 0xf9, 0xc5, 0x42, 0xff, 0x4e, 0x67, 0x62, 0x2f, 0x95, 0x87, 0x4f,
	0x94, 0xea, 0x4b, 0x4b, 0xc6, 0x53, 0xb4, 0x1a, 0x05, 0xcb, 0x27, 0x61, 0x97, 0xce, 0xcb, 0x45,
	0x25, 0x09, 0x69, 0x97, 0x72, 0xfb, 0x3e, 0x5a, 0x26, 0x32, 0xda, 0xf3, 0x32, 0x10, 0x9d, 0x3a,
	0xdf, 0x58, 0xe8, 0xb6, 0xb1, 0x6f, 0x9b, 0x76, 0xc6, 0x43, 0x08, 0x4d, 0x4b, 0x2a, 0x47, 0x23,
	0xb7, 0x1e, 0xa2, 0x62, 0x60, 0x4e, 0xe7, 0x74, 0x64, 0x7c, 0x7e, 0x46, 0xbf, 0xe2, 0x40, 0xe5,
	0x17, 0x05, 0xca, 0xf9, 0x39, 0x77, 0xc2, 0x44, 0xdd, 0x0a, 0x97, 0x6c, 0xe2, 0x3a, 0x2a, 0xa8,
	0x28, 0x29, 0x13, 0x2b, 0xae, 0xfe, 0x38, 0xad, 0x54, 0x97, 0xce, 0x51, 0xaa, 0xb1, 0xff, 0x85,
	0x85, 0x85, 0x72, 0x59, 0x55, 0xfd, 0xa7, 0x85, 0xee, 0x9d, 0x88, 0xeb, 0x68, 0x80, 0x3b, 0xf0,
	0x31, 0xe6, 0xef, 0x9e, 0xff, 0xff, 0x22, 0x34, 0xc0, 0x5c, 0xf8, 0xa7, 0x45, 0xb8, 0x34, 0x88,
	0x34, 0xd8, 0xff, 0x41, 0xa5, 0x10, 0x26, 0x06, 0x9d, 0x9f, 0x2d, 0x3b, 0x84, 0x89, 0x97, 0xad,
	0x9a, 0xc5, 0xd3, 0x38, 0xce, 0x9e, 0x9c, 0xc5, 0x51, 0xf6, 0x9c, 0xdf, 0xad, 0x78, 0xa6, 0x26,
	0x3e, 0xab, 0xec, 0x5d, 0x72, 0x31, 0xdd, 0x46, 0x2b, 0x9c, 0x8e, 0x59, 0x47, 0x76, 0x71, 0x52,
	0x53, 0x65, 0x4d, 0x53, 0x6d, 0x29, 0xef, 0xe3, 0x00, 0xb8, 0x30, 0x80, 0x25, 0x05, 0x28, 0x49,
	0x8a, 0x3e, 0x3e, 0x7b, 0xc5, 0x38, 0xdf, 0x5a, 0x68, 0x33, 0x5e, 0x7d, 0x44, 0x7c, 0x45, 0x47,
	0xde, 0x55, 0xd1, 0x72, 0x08, 0x13, 0x75, 0x9b, 0x4b, 0xe7, 0x4a, 0x6e, 0xf4, 0x29, 0x4f, 0xe8,
	0x20, 0x50, 0x27, 0x39, 0x7d, 0x62, 0x3e, 0x13, 0x2f, 0xf3, 0x67, 0xea, 0xea, 0x85, 0xf9, 0x71,
	0x7e, 0xb4, 0x50, 0x2d, 0xb1, 0xb1, 0x85, 0x7b, 0x70, 0xc0, 0x08, 0x84, 0x02, 0xcb, 0xfd, 0x2a,
	0xb2, 0xf4, 0x19, 0xba, 0x49, 0x42, 0x7f, 0x44, 0x99, 0x60, 0x98, 0x08, 0x7f, 0x84, 0x7b, 0xe0,
	0xd3, 0x04, 0xa6, 0xcc, 0x2f, 0xba, 0x1b, 0x24, 0x6c, 0x19, 0xc8, 0x94, 0x9c, 0x8b, 0x1f, 0x46,
	0xdf, 0xa5, 0xae, 0x02, 0x19, 0x5a, 0x3a, 0x91, 0x2a, 0xf7, 0xc7, 0xc3, 0x23, 0x60, 0xfc, 0x35,
	0x1e, 0x8c, 0x21, 0xa9, 0xa1, 0x6b, 0xbc, 0x4f, 0x27, 0xda, 0xe8, 0x50, 0x03, 0x8c, 0xc1, 0x6b,
	0x3c, 0xcb, 0x77, 0xf1, 0x66, 0xfe, 0x90, 0xf4, 0xb6, 0x1c, 0xf7, 0x30, 0x02, 0x2c, 0x48, 0xd8,
	0x7b, 0x09, 0x38, 0x98, 0xb6, 0xf3, 0x3d, 0xf4, 0x0f, 0x65, 0x27, 0x8b, 0x40, 0x7e, 0x5f, 0xa3,
	0x8c, 0xb1, 0xeb, 0xf2, 0x74, 0x5a, 0xc2, 0xc5, 0x5b, 0xfc, 0x87, 0x85, 0x6e, 0x25, 0x16, 0x37,
	0x68, 0x28, 0x20, 0x14, 0x5e, 0x07, 0x27, 0xbb, 0xb4, 0x83, 0x2a, 0x84, 0xfb, 0x78, 0x2c, 0x68,
	0x97, 0x08, 0x3f, 0xce, 0x7e, 0x99, 0xf0, 0xe7, 0x9a, 0x76, 0x10, 0xca, 0xa0, 0xcb, 0xe9, 0xdc,
	0xd1, 0xec, 0x3e, 0x97, 0xfc, 0xca, 0xc4, 0x9c, 0xbb, 0x46, 0x07, 0x41, 0x5a, 0xac, 0xc4, 0xca,
	0xc9, 0x93, 0xc5, 0xca, 0x9d, 0x30, 0xe7, 0xae, 0x85, 0x30, 0xc9, 0x60, 0x63, 0x77, 0x97, 0xce,
	0xe4, 0xee, 0xe2, 0x16, 0xfd, 0x2a, 0xe3, 0xae, 0x71, 0x60, 0xba, 0x7e, 0x4e, 0xba, 0x62, 0xcd,
	0x76, 0xe5, 0x32, 0xea, 0x27, 0xd5, 0x9d, 0xd1, 0xa8, 0x6c, 0x31, 0x12, 0x0a, 0x60, 0x07, 0x23,
	0xd9, 0x5b, 0x5c, 0x0e, 0xac, 0x91, 0xa6, 0xc8, 0xa7, 0x87, 0x1e, 0x25, 0x25, 0x43, 0x69, 0x06,
	0xf6, 0x06, 0x2a, 0x8e, 0xf0, 0x48, 0x1f, 0x9a, 0x69, 0xa2, 0xbe, 0x9b, 0x81, 0x7d, 0x0f, 0x95,
	0x54, 0x5b, 0x70, 0xf2, 0x16, 0x8c, 0x35, 0x25, 0x65, 0xb3, 0x47, 0xde, 0x82, 0x5b, 0x94, 0x67,
	0xf2, 0xd7, 0x79, 0xe6, 0x49, 0x2b, 0x7e, 0x90, 0xed, 0x48, 0xfd, 0xca, 0xd4, 0x96, 0x7c, 0xa4,
	0xc0, 0x64, 0x8f, 0x06, 0xef, 0xf0, 0x20, 0x73, 0x0e, 0xe2, 0xab, 0x62, 0xe7, 0x0d, 0x11, 0x17,
	0x20, 0xf0, 0x6b, 0x0b, 0xdd, 0x34, 0x27, 0x6a, 0xf7, 0xbf, 0xfc, 0x55, 0x3e, 0xf3, 0x40, 0xca,
	0x2f, 0x78, 0x20, 0x39, 0x7f, 0x59, 0xa8, 0x9a, 0xb6, 0x2f, 0x73, 0x25, 0x9e, 0xc3, 0xb6, 0xf4,
	0xed, 0x99, 0x3b, 0xeb, 0xed, 0x79, 0xea, 0xbd, 0xf2, 0x21, 0xaa, 0xe8, 0x85, 0x6b, 0x4c, 0xb8,
	0xc0, 0x42, 0xbf, 0x56, 0xcb, 0x8f, 0x6f, 0xd4, 0xdb, 0xfb, 0x75, 0x65, 0xe5, 0x61, 0xd3, 0x93,
	0xf4, 0xc8, 0x90, 0x15, 0x85, 0x3e, 0xd4, 0x60, 0xfb, 0x9f, 0xe6, 0xa1, 0xdb, 0x34, 0xfb, 0x80,
	0xbc, 0x58, 0x53, 0x14, 0xe7, 0x37, 0x0b, 0xdd, 0x37, 0x9e, 0x44, 0xcb, 0x80, 0x5e, 0xd5, 0x9a,
	0x02, 0x86, 0x8d, 0x3e, 0x19, 0x04, 0x0c, 0xc2, 0xe7, 0x97, 0x94, 0xa2, 0xff, 0xa3, 0x15, 0xd5,
	0xe6, 0x46, 0xcd, 0x9c, 0x2c, 0x95, 0x65, 0xc7, 0x1b, 0x88, 0x64, 0x51, 0x83, 0x2b, 0x62, 0x99,
	0xbd, 0x77, 0x96, 0xe5, 0x0c, 0x33, 0x10, 0xe7, 0xf3, 0x7c, 0xdc, 0x1e, 0x8d, 0x3e, 0x66, 0x62,
	0x0f, 0x02, 0x82, 0x05, 0x65, 0x1e, 0x88, 0x9d, 0x80, 0xc8, 0xc1, 0xae, 0xe2, 0x67, 0xff, 0x2f,
	0xeb, 0xde, 0x46, 0xbd, 0xed, 0x35, 0x5e, 0xd6, 0x15, 0xcb, 0x6c, 0x27, 0x5f, 0x68, 0xf3, 0xcd,
	0xa2, 0xc9, 0xcd, 0x9b, 0xfa, 0x5f, 0x32, 0x31, 0x19, 0x45, 0xbb, 0x1a, 0xe0, 0x09, 0xca, 0x70,
	0x4f, 0xfb, 0x63, 0x48, 0x5c, 0xca, 0x90, 0xfe, 0xc4, 0x32, 0x96, 0xce, 0x28, 0x23, 0x84, 0x49,
	0x2c, 0xe3, 0x0e, 0xaa, 0x48, 0x3b, 0x02, 0xc2, 0xcc, 0xff, 0x38, 0x05, 0xf5, 0x98, 0x96, 0xc6,
	0x6d, 0x47, 0x34, 0x09, 0x92, 0x8a, 0x12, 0x90, 0x7e, 0x71, 0x4b, 0xed, 0x09, 0xe8, 0x11, 0xb2,
	0xd5, 0x82, 0xdf, 0xc1, 0x42, 0x4e, 0x36, 0x69, 0x15, 0x16, 0xea, 0xd9, 0x5e, 0x70, 0xaf, 0xca,
	0x5d, 0x5e, 0x1f, 0xec, 0x2a, 0xba, 0x44, 0xab, 0xf5, 0x35, 0x8b, 0x2e, 0x6a, 0xb4, 0xdc, 0x5b,
	0xd3, 0x68, 0xe7, 0x33, 0xf4, 0x60, 0x56, 0x16, 0x0e, 0x47, 0x01, 0x16, 0xb0, 0x4b, 0xd9, 0x4e,
	0x28, 0x88, 0xf8, 0x74, 0x1b, 0x06, 0xf0, 0x2e, 0xb9, 0xa8, 0xa1, 0x7c, 0x67, 0x18, 0xcc, 0xf9,
	0x5b, 0x43, 0x1e, 0x39, 0x5f, 0xe6, 0x50, 0x2d, 0x2d, 0x40, 0xae, 0x30, 0xc0, 0x08, 0xf0, 0xf4,
	0x7a, 0x78, 0x6e, 0xbd, 0x0f, 0x51, 0x71, 0x68, 0x3c, 0x99, 0xd7, 0xef, 0xd1, 0xb9, 0x5d, 0x43,
	0x65, 0xae, 0x34, 0x66, 0xd7, 0xe0, 0x84, 0x64, 0x3f, 0x45, 0xe5, 0x54, 0x45, 0x99, 0x62, 0x58,
	0xd7, 0xff, 0x68, 0x99, 0x74, 0x47, 0xfa, 0x51, 0x52, 0x45, 0x92, 0x2d, 0x55, 0x44, 0x2a, 0xfd,
	0x73, 0xd9, 0x92, 0xc2, 0x71, 0x7e, 0xb5, 0xd0, 0xdd, 0x6c, 0x44, 0xe6, 0xfc, 0x55, 0xf8, 0x04,
	0x55, 0x32, 0x0f, 0xf1, 0x39, 0xef, 0x82, 0x95, 0xf4, 0x3b, 0xdc, 0x7e, 0x81, 0xd6, 0x8e, 0xa0,
	0x47, 0xc2, 0xd4, 0xff, 0x8b, 0xfa, 0xaf, 0xbd, 0x8d, 0xb8, 0xb8, 0x63, 0x85, 0x91, 0x75, 0xab,
	0x8a, 0x23, 0x26, 0xdb, 0x1f, 0xa1, 0x0a, 0x84, 0x41, 0x4a, 0x42, 0x7e, 0x91, 0x84, 0x15, 0x48,
	0xf9, 0xf1, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe1, 0xb9, 0x02, 0xd3, 0x90, 0x15, 0x00, 0x00,
}
