// Code generated by protoc-gen-go. DO NOT EDIT.
// source: TSACommandArchives_sos.proto

package TSA

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	TSK "github.com/zimbabao/docconv/iWork/TSK"
	TSP "github.com/zimbabao/docconv/iWork/TSP"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InducedVerifyDrawableZOrdersWithServerCommandArchive struct {
	Super                              *TSK.CommandArchive          `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	ServerDrawableZOrderLists          []*DrawableZOrderListArchive `protobuf:"bytes,2,rep,name=server_drawable_z_order_lists,json=serverDrawableZOrderLists" json:"server_drawable_z_order_lists,omitempty"`
	ServerDrawableZOrderListsUndefined *bool                        `protobuf:"varint,3,opt,name=server_drawable_z_order_lists_undefined,json=serverDrawableZOrderListsUndefined" json:"server_drawable_z_order_lists_undefined,omitempty"`
	XXX_NoUnkeyedLiteral               struct{}                     `json:"-"`
	XXX_unrecognized                   []byte                       `json:"-"`
	XXX_sizecache                      int32                        `json:"-"`
}

func (m *InducedVerifyDrawableZOrdersWithServerCommandArchive) Reset() {
	*m = InducedVerifyDrawableZOrdersWithServerCommandArchive{}
}
func (m *InducedVerifyDrawableZOrdersWithServerCommandArchive) String() string {
	return proto.CompactTextString(m)
}
func (*InducedVerifyDrawableZOrdersWithServerCommandArchive) ProtoMessage() {}
func (*InducedVerifyDrawableZOrdersWithServerCommandArchive) Descriptor() ([]byte, []int) {
	return fileDescriptor_66516220d871115c, []int{0}
}

func (m *InducedVerifyDrawableZOrdersWithServerCommandArchive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InducedVerifyDrawableZOrdersWithServerCommandArchive.Unmarshal(m, b)
}
func (m *InducedVerifyDrawableZOrdersWithServerCommandArchive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InducedVerifyDrawableZOrdersWithServerCommandArchive.Marshal(b, m, deterministic)
}
func (m *InducedVerifyDrawableZOrdersWithServerCommandArchive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InducedVerifyDrawableZOrdersWithServerCommandArchive.Merge(m, src)
}
func (m *InducedVerifyDrawableZOrdersWithServerCommandArchive) XXX_Size() int {
	return xxx_messageInfo_InducedVerifyDrawableZOrdersWithServerCommandArchive.Size(m)
}
func (m *InducedVerifyDrawableZOrdersWithServerCommandArchive) XXX_DiscardUnknown() {
	xxx_messageInfo_InducedVerifyDrawableZOrdersWithServerCommandArchive.DiscardUnknown(m)
}

var xxx_messageInfo_InducedVerifyDrawableZOrdersWithServerCommandArchive proto.InternalMessageInfo

func (m *InducedVerifyDrawableZOrdersWithServerCommandArchive) GetSuper() *TSK.CommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *InducedVerifyDrawableZOrdersWithServerCommandArchive) GetServerDrawableZOrderLists() []*DrawableZOrderListArchive {
	if m != nil {
		return m.ServerDrawableZOrderLists
	}
	return nil
}

func (m *InducedVerifyDrawableZOrdersWithServerCommandArchive) GetServerDrawableZOrderListsUndefined() bool {
	if m != nil && m.ServerDrawableZOrderListsUndefined != nil {
		return *m.ServerDrawableZOrderListsUndefined
	}
	return false
}

type VerifyDocumentWithServerCommandArchive struct {
	Super                *TSK.CommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *VerifyDocumentWithServerCommandArchive) Reset() {
	*m = VerifyDocumentWithServerCommandArchive{}
}
func (m *VerifyDocumentWithServerCommandArchive) String() string { return proto.CompactTextString(m) }
func (*VerifyDocumentWithServerCommandArchive) ProtoMessage()    {}
func (*VerifyDocumentWithServerCommandArchive) Descriptor() ([]byte, []int) {
	return fileDescriptor_66516220d871115c, []int{1}
}

func (m *VerifyDocumentWithServerCommandArchive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyDocumentWithServerCommandArchive.Unmarshal(m, b)
}
func (m *VerifyDocumentWithServerCommandArchive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyDocumentWithServerCommandArchive.Marshal(b, m, deterministic)
}
func (m *VerifyDocumentWithServerCommandArchive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyDocumentWithServerCommandArchive.Merge(m, src)
}
func (m *VerifyDocumentWithServerCommandArchive) XXX_Size() int {
	return xxx_messageInfo_VerifyDocumentWithServerCommandArchive.Size(m)
}
func (m *VerifyDocumentWithServerCommandArchive) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyDocumentWithServerCommandArchive.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyDocumentWithServerCommandArchive proto.InternalMessageInfo

func (m *VerifyDocumentWithServerCommandArchive) GetSuper() *TSK.CommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

type VerifyDrawableZOrdersWithServerCommandArchive struct {
	Super                   *TSK.CommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	DrawableIdList          []*TSP.UUID         `protobuf:"bytes,2,rep,name=drawable_id_list,json=drawableIdList" json:"drawable_id_list,omitempty"`
	DrawableIdListUndefined *bool               `protobuf:"varint,3,opt,name=drawable_id_list_undefined,json=drawableIdListUndefined" json:"drawable_id_list_undefined,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}            `json:"-"`
	XXX_unrecognized        []byte              `json:"-"`
	XXX_sizecache           int32               `json:"-"`
}

func (m *VerifyDrawableZOrdersWithServerCommandArchive) Reset() {
	*m = VerifyDrawableZOrdersWithServerCommandArchive{}
}
func (m *VerifyDrawableZOrdersWithServerCommandArchive) String() string {
	return proto.CompactTextString(m)
}
func (*VerifyDrawableZOrdersWithServerCommandArchive) ProtoMessage() {}
func (*VerifyDrawableZOrdersWithServerCommandArchive) Descriptor() ([]byte, []int) {
	return fileDescriptor_66516220d871115c, []int{2}
}

func (m *VerifyDrawableZOrdersWithServerCommandArchive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyDrawableZOrdersWithServerCommandArchive.Unmarshal(m, b)
}
func (m *VerifyDrawableZOrdersWithServerCommandArchive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyDrawableZOrdersWithServerCommandArchive.Marshal(b, m, deterministic)
}
func (m *VerifyDrawableZOrdersWithServerCommandArchive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyDrawableZOrdersWithServerCommandArchive.Merge(m, src)
}
func (m *VerifyDrawableZOrdersWithServerCommandArchive) XXX_Size() int {
	return xxx_messageInfo_VerifyDrawableZOrdersWithServerCommandArchive.Size(m)
}
func (m *VerifyDrawableZOrdersWithServerCommandArchive) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyDrawableZOrdersWithServerCommandArchive.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyDrawableZOrdersWithServerCommandArchive proto.InternalMessageInfo

func (m *VerifyDrawableZOrdersWithServerCommandArchive) GetSuper() *TSK.CommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *VerifyDrawableZOrdersWithServerCommandArchive) GetDrawableIdList() []*TSP.UUID {
	if m != nil {
		return m.DrawableIdList
	}
	return nil
}

func (m *VerifyDrawableZOrdersWithServerCommandArchive) GetDrawableIdListUndefined() bool {
	if m != nil && m.DrawableIdListUndefined != nil {
		return *m.DrawableIdListUndefined
	}
	return false
}

type VerifyObjectsWithServerCommandArchive struct {
	Super                 *TSK.CommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	ObjectIdList          []*TSP.UUID         `protobuf:"bytes,2,rep,name=object_id_list,json=objectIdList" json:"object_id_list,omitempty"`
	ObjectIdListUndefined *bool               `protobuf:"varint,3,opt,name=object_id_list_undefined,json=objectIdListUndefined" json:"object_id_list_undefined,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}            `json:"-"`
	XXX_unrecognized      []byte              `json:"-"`
	XXX_sizecache         int32               `json:"-"`
}

func (m *VerifyObjectsWithServerCommandArchive) Reset()         { *m = VerifyObjectsWithServerCommandArchive{} }
func (m *VerifyObjectsWithServerCommandArchive) String() string { return proto.CompactTextString(m) }
func (*VerifyObjectsWithServerCommandArchive) ProtoMessage()    {}
func (*VerifyObjectsWithServerCommandArchive) Descriptor() ([]byte, []int) {
	return fileDescriptor_66516220d871115c, []int{3}
}

func (m *VerifyObjectsWithServerCommandArchive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyObjectsWithServerCommandArchive.Unmarshal(m, b)
}
func (m *VerifyObjectsWithServerCommandArchive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyObjectsWithServerCommandArchive.Marshal(b, m, deterministic)
}
func (m *VerifyObjectsWithServerCommandArchive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyObjectsWithServerCommandArchive.Merge(m, src)
}
func (m *VerifyObjectsWithServerCommandArchive) XXX_Size() int {
	return xxx_messageInfo_VerifyObjectsWithServerCommandArchive.Size(m)
}
func (m *VerifyObjectsWithServerCommandArchive) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyObjectsWithServerCommandArchive.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyObjectsWithServerCommandArchive proto.InternalMessageInfo

func (m *VerifyObjectsWithServerCommandArchive) GetSuper() *TSK.CommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *VerifyObjectsWithServerCommandArchive) GetObjectIdList() []*TSP.UUID {
	if m != nil {
		return m.ObjectIdList
	}
	return nil
}

func (m *VerifyObjectsWithServerCommandArchive) GetObjectIdListUndefined() bool {
	if m != nil && m.ObjectIdListUndefined != nil {
		return *m.ObjectIdListUndefined
	}
	return false
}

func init() {
	proto.RegisterType((*InducedVerifyDrawableZOrdersWithServerCommandArchive)(nil), "TSA.InducedVerifyDrawableZOrdersWithServerCommandArchive")
	proto.RegisterType((*VerifyDocumentWithServerCommandArchive)(nil), "TSA.VerifyDocumentWithServerCommandArchive")
	proto.RegisterType((*VerifyDrawableZOrdersWithServerCommandArchive)(nil), "TSA.VerifyDrawableZOrdersWithServerCommandArchive")
	proto.RegisterType((*VerifyObjectsWithServerCommandArchive)(nil), "TSA.VerifyObjectsWithServerCommandArchive")
}

func init() { proto.RegisterFile("TSACommandArchives_sos.proto", fileDescriptor_66516220d871115c) }

var fileDescriptor_66516220d871115c = []byte{
	// 378 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x90, 0xc1, 0x4e, 0xea, 0x40,
	0x14, 0x86, 0x53, 0xc8, 0x4d, 0xee, 0x1d, 0x6e, 0xc8, 0xbd, 0x35, 0xc4, 0x4a, 0xd4, 0x90, 0x26,
	0x08, 0x2e, 0x9c, 0x26, 0x68, 0xe2, 0xc2, 0x55, 0x95, 0x0d, 0x41, 0x03, 0x61, 0x06, 0x49, 0xd8,
	0xd4, 0xb6, 0x33, 0xc0, 0x28, 0xed, 0x90, 0x99, 0x16, 0x23, 0x4f, 0xe2, 0xc3, 0xf8, 0x08, 0x3e,
	0x94, 0x81, 0xb6, 0x60, 0x6d, 0x70, 0x85, 0xdb, 0x33, 0xff, 0xf9, 0xe6, 0x7c, 0x3f, 0x38, 0xc4,
	0xc8, 0xbc, 0xe1, 0x9e, 0x67, 0xfb, 0xc4, 0x14, 0xee, 0x84, 0xcd, 0xa9, 0xb4, 0x24, 0x97, 0x70,
	0x26, 0x78, 0xc0, 0xd5, 0x3c, 0x46, 0x66, 0xb9, 0x84, 0x91, 0x99, 0x7d, 0x2b, 0xff, 0xc7, 0xa8,
	0x9d, 0x8c, 0x37, 0xa3, 0xee, 0x1d, 0x95, 0xd2, 0x1e, 0x27, 0x23, 0xfd, 0x35, 0x07, 0x2e, 0x5a,
	0x3e, 0x09, 0x5d, 0x4a, 0xee, 0xa9, 0x60, 0xa3, 0x97, 0xa6, 0xb0, 0x9f, 0x6d, 0x67, 0x4a, 0x87,
	0x1d, 0x41, 0xa8, 0x90, 0x03, 0x16, 0x4c, 0x10, 0x15, 0x73, 0x2a, 0xd2, 0x57, 0xa8, 0xa7, 0xe0,
	0x97, 0x0c, 0x67, 0x54, 0x68, 0x4a, 0x25, 0x57, 0x2f, 0x34, 0xf6, 0x20, 0x46, 0x6d, 0x98, 0xce,
	0xf4, 0xa2, 0x84, 0xfa, 0x00, 0x8e, 0xe4, 0x0a, 0x61, 0x91, 0x18, 0x6e, 0x2d, 0x2c, 0xbe, 0xc4,
	0x5b, 0x53, 0x26, 0x03, 0xa9, 0xe5, 0x2a, 0xf9, 0x7a, 0xa1, 0x71, 0x0c, 0x31, 0x32, 0x61, 0xfa,
	0xff, 0x5b, 0x26, 0x83, 0x84, 0x76, 0x10, 0x41, 0xb2, 0x01, 0xa9, 0x22, 0x50, 0xfb, 0xf6, 0x07,
	0x2b, 0xf4, 0x09, 0x1d, 0x31, 0x9f, 0x12, 0x2d, 0x5f, 0x51, 0xea, 0xbf, 0x7b, 0xfa, 0x56, 0x56,
	0x3f, 0x49, 0xea, 0x08, 0x9c, 0xc4, 0x95, 0x70, 0x37, 0xf4, 0xa8, 0x1f, 0xec, 0xa0, 0x0b, 0xfd,
	0x5d, 0x01, 0x67, 0x3f, 0x56, 0xf4, 0x39, 0xf8, 0xb7, 0xf6, 0x67, 0x64, 0xa5, 0x1e, 0x77, 0xfb,
	0x07, 0x62, 0xd4, 0x85, 0xfd, 0x7e, 0xab, 0xd9, 0x2b, 0x26, 0x91, 0x16, 0x59, 0x0a, 0xab, 0x57,
	0xa0, 0xfc, 0x75, 0x29, 0x53, 0xd7, 0x7e, 0x7a, 0x67, 0xd3, 0xd1, 0x9b, 0x02, 0xaa, 0x91, 0x4e,
	0xc7, 0x79, 0xa4, 0x6e, 0xb0, 0x13, 0x0d, 0x03, 0x14, 0xf9, 0x8a, 0xb6, 0x5d, 0xe2, 0x6f, 0x14,
	0x88, 0x15, 0x2e, 0x81, 0x96, 0x5e, 0xc8, 0x08, 0x94, 0x3e, 0xe7, 0xd7, 0xe7, 0x5f, 0xd7, 0x86,
	0xd5, 0x31, 0x0b, 0x26, 0xa1, 0x03, 0x5d, 0xee, 0x19, 0x0b, 0xe6, 0x39, 0xb6, 0x63, 0x73, 0x83,
	0x70, 0xd7, 0xe5, 0xfe, 0xdc, 0x60, 0x03, 0x2e, 0x9e, 0x0c, 0x8c, 0xcc, 0x8f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xaf, 0xc4, 0x70, 0x61, 0x87, 0x03, 0x00, 0x00,
}
