// Code generated by protoc-gen-go. DO NOT EDIT.
// source: TSPArchiveMessages.proto

package TSP

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FieldInfo_Type int32

const (
	FieldInfo_Value           FieldInfo_Type = 0
	FieldInfo_ObjectReference FieldInfo_Type = 1
	FieldInfo_DataReference   FieldInfo_Type = 2
	FieldInfo_Message         FieldInfo_Type = 3
)

var FieldInfo_Type_name = map[int32]string{
	0: "Value",
	1: "ObjectReference",
	2: "DataReference",
	3: "Message",
}

var FieldInfo_Type_value = map[string]int32{
	"Value":           0,
	"ObjectReference": 1,
	"DataReference":   2,
	"Message":         3,
}

func (x FieldInfo_Type) Enum() *FieldInfo_Type {
	p := new(FieldInfo_Type)
	*p = x
	return p
}

func (x FieldInfo_Type) String() string {
	return proto.EnumName(FieldInfo_Type_name, int32(x))
}

func (x *FieldInfo_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(FieldInfo_Type_value, data, "FieldInfo_Type")
	if err != nil {
		return err
	}
	*x = FieldInfo_Type(value)
	return nil
}

func (FieldInfo_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_47802bcfa9d8cfa9, []int{2, 0}
}

type FieldInfo_UnknownFieldRule int32

const (
	FieldInfo_IgnoreAndPreserveUntilModified FieldInfo_UnknownFieldRule = 0
	FieldInfo_IgnoreAndPreserve              FieldInfo_UnknownFieldRule = 1
	FieldInfo_MustUnderstand                 FieldInfo_UnknownFieldRule = 2
	FieldInfo_NotSupported                   FieldInfo_UnknownFieldRule = -1
)

var FieldInfo_UnknownFieldRule_name = map[int32]string{
	0:  "IgnoreAndPreserveUntilModified",
	1:  "IgnoreAndPreserve",
	2:  "MustUnderstand",
	-1: "NotSupported",
}

var FieldInfo_UnknownFieldRule_value = map[string]int32{
	"IgnoreAndPreserveUntilModified": 0,
	"IgnoreAndPreserve":              1,
	"MustUnderstand":                 2,
	"NotSupported":                   -1,
}

func (x FieldInfo_UnknownFieldRule) Enum() *FieldInfo_UnknownFieldRule {
	p := new(FieldInfo_UnknownFieldRule)
	*p = x
	return p
}

func (x FieldInfo_UnknownFieldRule) String() string {
	return proto.EnumName(FieldInfo_UnknownFieldRule_name, int32(x))
}

func (x *FieldInfo_UnknownFieldRule) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(FieldInfo_UnknownFieldRule_value, data, "FieldInfo_UnknownFieldRule")
	if err != nil {
		return err
	}
	*x = FieldInfo_UnknownFieldRule(value)
	return nil
}

func (FieldInfo_UnknownFieldRule) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_47802bcfa9d8cfa9, []int{2, 1}
}

type FieldInfo_KnownFieldRule int32

const (
	FieldInfo_None                            FieldInfo_KnownFieldRule = 0
	FieldInfo_PreserveNewerValueUntilModified FieldInfo_KnownFieldRule = 1
	FieldInfo_PreserveNewerValue              FieldInfo_KnownFieldRule = 2
)

var FieldInfo_KnownFieldRule_name = map[int32]string{
	0: "None",
	1: "PreserveNewerValueUntilModified",
	2: "PreserveNewerValue",
}

var FieldInfo_KnownFieldRule_value = map[string]int32{
	"None":                            0,
	"PreserveNewerValueUntilModified": 1,
	"PreserveNewerValue":              2,
}

func (x FieldInfo_KnownFieldRule) Enum() *FieldInfo_KnownFieldRule {
	p := new(FieldInfo_KnownFieldRule)
	*p = x
	return p
}

func (x FieldInfo_KnownFieldRule) String() string {
	return proto.EnumName(FieldInfo_KnownFieldRule_name, int32(x))
}

func (x *FieldInfo_KnownFieldRule) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(FieldInfo_KnownFieldRule_value, data, "FieldInfo_KnownFieldRule")
	if err != nil {
		return err
	}
	*x = FieldInfo_KnownFieldRule(value)
	return nil
}

func (FieldInfo_KnownFieldRule) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_47802bcfa9d8cfa9, []int{2, 2}
}

type PackageMetadata_PackageType int32

const (
	PackageMetadata_Default    PackageMetadata_PackageType = 0
	PackageMetadata_Directory  PackageMetadata_PackageType = 1
	PackageMetadata_SingleFile PackageMetadata_PackageType = 2
)

var PackageMetadata_PackageType_name = map[int32]string{
	0: "Default",
	1: "Directory",
	2: "SingleFile",
}

var PackageMetadata_PackageType_value = map[string]int32{
	"Default":    0,
	"Directory":  1,
	"SingleFile": 2,
}

func (x PackageMetadata_PackageType) Enum() *PackageMetadata_PackageType {
	p := new(PackageMetadata_PackageType)
	*p = x
	return p
}

func (x PackageMetadata_PackageType) String() string {
	return proto.EnumName(PackageMetadata_PackageType_name, int32(x))
}

func (x *PackageMetadata_PackageType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PackageMetadata_PackageType_value, data, "PackageMetadata_PackageType")
	if err != nil {
		return err
	}
	*x = PackageMetadata_PackageType(value)
	return nil
}

func (PackageMetadata_PackageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_47802bcfa9d8cfa9, []int{9, 0}
}

type DataInfo_DownloadPriority int32

const (
	DataInfo_High    DataInfo_DownloadPriority = 0
	DataInfo_Default DataInfo_DownloadPriority = 1
)

var DataInfo_DownloadPriority_name = map[int32]string{
	0: "High",
	1: "Default",
}

var DataInfo_DownloadPriority_value = map[string]int32{
	"High":    0,
	"Default": 1,
}

func (x DataInfo_DownloadPriority) Enum() *DataInfo_DownloadPriority {
	p := new(DataInfo_DownloadPriority)
	*p = x
	return p
}

func (x DataInfo_DownloadPriority) String() string {
	return proto.EnumName(DataInfo_DownloadPriority_name, int32(x))
}

func (x *DataInfo_DownloadPriority) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(DataInfo_DownloadPriority_value, data, "DataInfo_DownloadPriority")
	if err != nil {
		return err
	}
	*x = DataInfo_DownloadPriority(value)
	return nil
}

func (DataInfo_DownloadPriority) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_47802bcfa9d8cfa9, []int{12, 0}
}

type ArchiveInfo struct {
	Identifier           *uint64        `protobuf:"varint,1,opt,name=identifier" json:"identifier,omitempty"`
	MessageInfos         []*MessageInfo `protobuf:"bytes,2,rep,name=message_infos,json=messageInfos" json:"message_infos,omitempty"`
	ShouldMerge          *bool          `protobuf:"varint,3,opt,name=should_merge,json=shouldMerge" json:"should_merge,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ArchiveInfo) Reset()         { *m = ArchiveInfo{} }
func (m *ArchiveInfo) String() string { return proto.CompactTextString(m) }
func (*ArchiveInfo) ProtoMessage()    {}
func (*ArchiveInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_47802bcfa9d8cfa9, []int{0}
}

func (m *ArchiveInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArchiveInfo.Unmarshal(m, b)
}
func (m *ArchiveInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArchiveInfo.Marshal(b, m, deterministic)
}
func (m *ArchiveInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArchiveInfo.Merge(m, src)
}
func (m *ArchiveInfo) XXX_Size() int {
	return xxx_messageInfo_ArchiveInfo.Size(m)
}
func (m *ArchiveInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ArchiveInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ArchiveInfo proto.InternalMessageInfo

func (m *ArchiveInfo) GetIdentifier() uint64 {
	if m != nil && m.Identifier != nil {
		return *m.Identifier
	}
	return 0
}

func (m *ArchiveInfo) GetMessageInfos() []*MessageInfo {
	if m != nil {
		return m.MessageInfos
	}
	return nil
}

func (m *ArchiveInfo) GetShouldMerge() bool {
	if m != nil && m.ShouldMerge != nil {
		return *m.ShouldMerge
	}
	return false
}

type MessageInfo struct {
	Type                 *uint32      `protobuf:"varint,1,req,name=type" json:"type,omitempty"`
	Version              []uint32     `protobuf:"varint,2,rep,packed,name=version" json:"version,omitempty"`
	Length               *uint32      `protobuf:"varint,3,req,name=length" json:"length,omitempty"`
	FieldInfos           []*FieldInfo `protobuf:"bytes,4,rep,name=field_infos,json=fieldInfos" json:"field_infos,omitempty"`
	ObjectReferences     []uint64     `protobuf:"varint,5,rep,packed,name=object_references,json=objectReferences" json:"object_references,omitempty"`
	DataReferences       []uint64     `protobuf:"varint,6,rep,packed,name=data_references,json=dataReferences" json:"data_references,omitempty"`
	BaseMessageIndex     *uint32      `protobuf:"varint,7,opt,name=base_message_index,json=baseMessageIndex" json:"base_message_index,omitempty"`
	DiffMergeVersion     []uint32     `protobuf:"varint,8,rep,packed,name=diff_merge_version,json=diffMergeVersion" json:"diff_merge_version,omitempty"`
	DiffFieldPath        *FieldPath   `protobuf:"bytes,9,opt,name=diff_field_path,json=diffFieldPath" json:"diff_field_path,omitempty"`
	FieldsToRemove       []*FieldPath `protobuf:"bytes,10,rep,name=fields_to_remove,json=fieldsToRemove" json:"fields_to_remove,omitempty"`
	DiffReadVersion      []uint32     `protobuf:"varint,11,rep,packed,name=diff_read_version,json=diffReadVersion" json:"diff_read_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *MessageInfo) Reset()         { *m = MessageInfo{} }
func (m *MessageInfo) String() string { return proto.CompactTextString(m) }
func (*MessageInfo) ProtoMessage()    {}
func (*MessageInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_47802bcfa9d8cfa9, []int{1}
}

func (m *MessageInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageInfo.Unmarshal(m, b)
}
func (m *MessageInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageInfo.Marshal(b, m, deterministic)
}
func (m *MessageInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageInfo.Merge(m, src)
}
func (m *MessageInfo) XXX_Size() int {
	return xxx_messageInfo_MessageInfo.Size(m)
}
func (m *MessageInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MessageInfo proto.InternalMessageInfo

func (m *MessageInfo) GetType() uint32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *MessageInfo) GetVersion() []uint32 {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *MessageInfo) GetLength() uint32 {
	if m != nil && m.Length != nil {
		return *m.Length
	}
	return 0
}

func (m *MessageInfo) GetFieldInfos() []*FieldInfo {
	if m != nil {
		return m.FieldInfos
	}
	return nil
}

func (m *MessageInfo) GetObjectReferences() []uint64 {
	if m != nil {
		return m.ObjectReferences
	}
	return nil
}

func (m *MessageInfo) GetDataReferences() []uint64 {
	if m != nil {
		return m.DataReferences
	}
	return nil
}

func (m *MessageInfo) GetBaseMessageIndex() uint32 {
	if m != nil && m.BaseMessageIndex != nil {
		return *m.BaseMessageIndex
	}
	return 0
}

func (m *MessageInfo) GetDiffMergeVersion() []uint32 {
	if m != nil {
		return m.DiffMergeVersion
	}
	return nil
}

func (m *MessageInfo) GetDiffFieldPath() *FieldPath {
	if m != nil {
		return m.DiffFieldPath
	}
	return nil
}

func (m *MessageInfo) GetFieldsToRemove() []*FieldPath {
	if m != nil {
		return m.FieldsToRemove
	}
	return nil
}

func (m *MessageInfo) GetDiffReadVersion() []uint32 {
	if m != nil {
		return m.DiffReadVersion
	}
	return nil
}

type FieldInfo struct {
	Path                        *FieldPath                  `protobuf:"bytes,1,req,name=path" json:"path,omitempty"`
	Type                        *FieldInfo_Type             `protobuf:"varint,2,opt,name=type,enum=TSP.FieldInfo_Type,def=0" json:"type,omitempty"`
	UnknownFieldRule            *FieldInfo_UnknownFieldRule `protobuf:"varint,3,opt,name=unknown_field_rule,json=unknownFieldRule,enum=TSP.FieldInfo_UnknownFieldRule,def=0" json:"unknown_field_rule,omitempty"`
	ObjectReferences            []uint64                    `protobuf:"varint,4,rep,packed,name=object_references,json=objectReferences" json:"object_references,omitempty"`
	DataReferences              []uint64                    `protobuf:"varint,5,rep,packed,name=data_references,json=dataReferences" json:"data_references,omitempty"`
	KnownFieldRule              *FieldInfo_KnownFieldRule   `protobuf:"varint,6,opt,name=known_field_rule,json=knownFieldRule,enum=TSP.FieldInfo_KnownFieldRule,def=0" json:"known_field_rule,omitempty"`
	KnownFieldVersion           []uint32                    `protobuf:"varint,7,rep,packed,name=known_field_version,json=knownFieldVersion" json:"known_field_version,omitempty"`
	KnownFieldFeatureIdentifier *string                     `protobuf:"bytes,8,opt,name=known_field_feature_identifier,json=knownFieldFeatureIdentifier" json:"known_field_feature_identifier,omitempty"`
	XXX_NoUnkeyedLiteral        struct{}                    `json:"-"`
	XXX_unrecognized            []byte                      `json:"-"`
	XXX_sizecache               int32                       `json:"-"`
}

func (m *FieldInfo) Reset()         { *m = FieldInfo{} }
func (m *FieldInfo) String() string { return proto.CompactTextString(m) }
func (*FieldInfo) ProtoMessage()    {}
func (*FieldInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_47802bcfa9d8cfa9, []int{2}
}

func (m *FieldInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldInfo.Unmarshal(m, b)
}
func (m *FieldInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldInfo.Marshal(b, m, deterministic)
}
func (m *FieldInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldInfo.Merge(m, src)
}
func (m *FieldInfo) XXX_Size() int {
	return xxx_messageInfo_FieldInfo.Size(m)
}
func (m *FieldInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FieldInfo proto.InternalMessageInfo

const Default_FieldInfo_Type FieldInfo_Type = FieldInfo_Value
const Default_FieldInfo_UnknownFieldRule FieldInfo_UnknownFieldRule = FieldInfo_IgnoreAndPreserveUntilModified
const Default_FieldInfo_KnownFieldRule FieldInfo_KnownFieldRule = FieldInfo_None

func (m *FieldInfo) GetPath() *FieldPath {
	if m != nil {
		return m.Path
	}
	return nil
}

func (m *FieldInfo) GetType() FieldInfo_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Default_FieldInfo_Type
}

func (m *FieldInfo) GetUnknownFieldRule() FieldInfo_UnknownFieldRule {
	if m != nil && m.UnknownFieldRule != nil {
		return *m.UnknownFieldRule
	}
	return Default_FieldInfo_UnknownFieldRule
}

func (m *FieldInfo) GetObjectReferences() []uint64 {
	if m != nil {
		return m.ObjectReferences
	}
	return nil
}

func (m *FieldInfo) GetDataReferences() []uint64 {
	if m != nil {
		return m.DataReferences
	}
	return nil
}

func (m *FieldInfo) GetKnownFieldRule() FieldInfo_KnownFieldRule {
	if m != nil && m.KnownFieldRule != nil {
		return *m.KnownFieldRule
	}
	return Default_FieldInfo_KnownFieldRule
}

func (m *FieldInfo) GetKnownFieldVersion() []uint32 {
	if m != nil {
		return m.KnownFieldVersion
	}
	return nil
}

func (m *FieldInfo) GetKnownFieldFeatureIdentifier() string {
	if m != nil && m.KnownFieldFeatureIdentifier != nil {
		return *m.KnownFieldFeatureIdentifier
	}
	return ""
}

type FieldPath struct {
	Path                 []uint32 `protobuf:"varint,1,rep,packed,name=path" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FieldPath) Reset()         { *m = FieldPath{} }
func (m *FieldPath) String() string { return proto.CompactTextString(m) }
func (*FieldPath) ProtoMessage()    {}
func (*FieldPath) Descriptor() ([]byte, []int) {
	return fileDescriptor_47802bcfa9d8cfa9, []int{3}
}

func (m *FieldPath) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldPath.Unmarshal(m, b)
}
func (m *FieldPath) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldPath.Marshal(b, m, deterministic)
}
func (m *FieldPath) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldPath.Merge(m, src)
}
func (m *FieldPath) XXX_Size() int {
	return xxx_messageInfo_FieldPath.Size(m)
}
func (m *FieldPath) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldPath.DiscardUnknown(m)
}

var xxx_messageInfo_FieldPath proto.InternalMessageInfo

func (m *FieldPath) GetPath() []uint32 {
	if m != nil {
		return m.Path
	}
	return nil
}

type ComponentInfo struct {
	Identifier                   *uint64                       `protobuf:"varint,1,req,name=identifier" json:"identifier,omitempty"`
	PreferredLocator             *string                       `protobuf:"bytes,2,req,name=preferred_locator,json=preferredLocator" json:"preferred_locator,omitempty"`
	Locator                      *string                       `protobuf:"bytes,3,opt,name=locator" json:"locator,omitempty"`
	ReadVersion                  []uint32                      `protobuf:"varint,4,rep,packed,name=read_version,json=readVersion" json:"read_version,omitempty"`
	WriteVersion                 []uint32                      `protobuf:"varint,5,rep,packed,name=write_version,json=writeVersion" json:"write_version,omitempty"`
	ExternalReferences           []*ComponentExternalReference `protobuf:"bytes,6,rep,name=external_references,json=externalReferences" json:"external_references,omitempty"`
	DataReferences               []*ComponentDataReference     `protobuf:"bytes,7,rep,name=data_references,json=dataReferences" json:"data_references,omitempty"`
	ObjectUuidMapEntries         []*ObjectUUIDMapEntry         `protobuf:"bytes,11,rep,name=object_uuid_map_entries,json=objectUuidMapEntries" json:"object_uuid_map_entries,omitempty"`
	FeatureInfos                 []*FeatureInfo                `protobuf:"bytes,13,rep,name=feature_infos,json=featureInfos" json:"feature_infos,omitempty"`
	IsStoredOutsideObjectArchive *bool                         `protobuf:"varint,10,opt,name=is_stored_outside_object_archive,json=isStoredOutsideObjectArchive,def=0" json:"is_stored_outside_object_archive,omitempty"`
	SaveToken                    *uint64                       `protobuf:"varint,12,opt,name=save_token,json=saveToken,def=0" json:"save_token,omitempty"`
	XXX_NoUnkeyedLiteral         struct{}                      `json:"-"`
	XXX_unrecognized             []byte                        `json:"-"`
	XXX_sizecache                int32                         `json:"-"`
}

func (m *ComponentInfo) Reset()         { *m = ComponentInfo{} }
func (m *ComponentInfo) String() string { return proto.CompactTextString(m) }
func (*ComponentInfo) ProtoMessage()    {}
func (*ComponentInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_47802bcfa9d8cfa9, []int{4}
}

func (m *ComponentInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComponentInfo.Unmarshal(m, b)
}
func (m *ComponentInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComponentInfo.Marshal(b, m, deterministic)
}
func (m *ComponentInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComponentInfo.Merge(m, src)
}
func (m *ComponentInfo) XXX_Size() int {
	return xxx_messageInfo_ComponentInfo.Size(m)
}
func (m *ComponentInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ComponentInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ComponentInfo proto.InternalMessageInfo

const Default_ComponentInfo_IsStoredOutsideObjectArchive bool = false
const Default_ComponentInfo_SaveToken uint64 = 0

func (m *ComponentInfo) GetIdentifier() uint64 {
	if m != nil && m.Identifier != nil {
		return *m.Identifier
	}
	return 0
}

func (m *ComponentInfo) GetPreferredLocator() string {
	if m != nil && m.PreferredLocator != nil {
		return *m.PreferredLocator
	}
	return ""
}

func (m *ComponentInfo) GetLocator() string {
	if m != nil && m.Locator != nil {
		return *m.Locator
	}
	return ""
}

func (m *ComponentInfo) GetReadVersion() []uint32 {
	if m != nil {
		return m.ReadVersion
	}
	return nil
}

func (m *ComponentInfo) GetWriteVersion() []uint32 {
	if m != nil {
		return m.WriteVersion
	}
	return nil
}

func (m *ComponentInfo) GetExternalReferences() []*ComponentExternalReference {
	if m != nil {
		return m.ExternalReferences
	}
	return nil
}

func (m *ComponentInfo) GetDataReferences() []*ComponentDataReference {
	if m != nil {
		return m.DataReferences
	}
	return nil
}

func (m *ComponentInfo) GetObjectUuidMapEntries() []*ObjectUUIDMapEntry {
	if m != nil {
		return m.ObjectUuidMapEntries
	}
	return nil
}

func (m *ComponentInfo) GetFeatureInfos() []*FeatureInfo {
	if m != nil {
		return m.FeatureInfos
	}
	return nil
}

func (m *ComponentInfo) GetIsStoredOutsideObjectArchive() bool {
	if m != nil && m.IsStoredOutsideObjectArchive != nil {
		return *m.IsStoredOutsideObjectArchive
	}
	return Default_ComponentInfo_IsStoredOutsideObjectArchive
}

func (m *ComponentInfo) GetSaveToken() uint64 {
	if m != nil && m.SaveToken != nil {
		return *m.SaveToken
	}
	return Default_ComponentInfo_SaveToken
}

type ComponentExternalReference struct {
	ComponentIdentifier  *uint64  `protobuf:"varint,1,req,name=component_identifier,json=componentIdentifier" json:"component_identifier,omitempty"`
	ObjectIdentifier     *uint64  `protobuf:"varint,2,opt,name=object_identifier,json=objectIdentifier" json:"object_identifier,omitempty"`
	IsWeak               *bool    `protobuf:"varint,3,opt,name=is_weak,json=isWeak" json:"is_weak,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ComponentExternalReference) Reset()         { *m = ComponentExternalReference{} }
func (m *ComponentExternalReference) String() string { return proto.CompactTextString(m) }
func (*ComponentExternalReference) ProtoMessage()    {}
func (*ComponentExternalReference) Descriptor() ([]byte, []int) {
	return fileDescriptor_47802bcfa9d8cfa9, []int{5}
}

func (m *ComponentExternalReference) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComponentExternalReference.Unmarshal(m, b)
}
func (m *ComponentExternalReference) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComponentExternalReference.Marshal(b, m, deterministic)
}
func (m *ComponentExternalReference) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComponentExternalReference.Merge(m, src)
}
func (m *ComponentExternalReference) XXX_Size() int {
	return xxx_messageInfo_ComponentExternalReference.Size(m)
}
func (m *ComponentExternalReference) XXX_DiscardUnknown() {
	xxx_messageInfo_ComponentExternalReference.DiscardUnknown(m)
}

var xxx_messageInfo_ComponentExternalReference proto.InternalMessageInfo

func (m *ComponentExternalReference) GetComponentIdentifier() uint64 {
	if m != nil && m.ComponentIdentifier != nil {
		return *m.ComponentIdentifier
	}
	return 0
}

func (m *ComponentExternalReference) GetObjectIdentifier() uint64 {
	if m != nil && m.ObjectIdentifier != nil {
		return *m.ObjectIdentifier
	}
	return 0
}

func (m *ComponentExternalReference) GetIsWeak() bool {
	if m != nil && m.IsWeak != nil {
		return *m.IsWeak
	}
	return false
}

type ComponentDataReference struct {
	DataIdentifier       *uint64  `protobuf:"varint,1,req,name=data_identifier,json=dataIdentifier" json:"data_identifier,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ComponentDataReference) Reset()         { *m = ComponentDataReference{} }
func (m *ComponentDataReference) String() string { return proto.CompactTextString(m) }
func (*ComponentDataReference) ProtoMessage()    {}
func (*ComponentDataReference) Descriptor() ([]byte, []int) {
	return fileDescriptor_47802bcfa9d8cfa9, []int{6}
}

func (m *ComponentDataReference) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComponentDataReference.Unmarshal(m, b)
}
func (m *ComponentDataReference) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComponentDataReference.Marshal(b, m, deterministic)
}
func (m *ComponentDataReference) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComponentDataReference.Merge(m, src)
}
func (m *ComponentDataReference) XXX_Size() int {
	return xxx_messageInfo_ComponentDataReference.Size(m)
}
func (m *ComponentDataReference) XXX_DiscardUnknown() {
	xxx_messageInfo_ComponentDataReference.DiscardUnknown(m)
}

var xxx_messageInfo_ComponentDataReference proto.InternalMessageInfo

func (m *ComponentDataReference) GetDataIdentifier() uint64 {
	if m != nil && m.DataIdentifier != nil {
		return *m.DataIdentifier
	}
	return 0
}

type ObjectUUIDMapEntry struct {
	Identifier           *uint64  `protobuf:"varint,1,req,name=identifier" json:"identifier,omitempty"`
	Uuid                 *UUID    `protobuf:"bytes,2,req,name=uuid" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ObjectUUIDMapEntry) Reset()         { *m = ObjectUUIDMapEntry{} }
func (m *ObjectUUIDMapEntry) String() string { return proto.CompactTextString(m) }
func (*ObjectUUIDMapEntry) ProtoMessage()    {}
func (*ObjectUUIDMapEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_47802bcfa9d8cfa9, []int{7}
}

func (m *ObjectUUIDMapEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectUUIDMapEntry.Unmarshal(m, b)
}
func (m *ObjectUUIDMapEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectUUIDMapEntry.Marshal(b, m, deterministic)
}
func (m *ObjectUUIDMapEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectUUIDMapEntry.Merge(m, src)
}
func (m *ObjectUUIDMapEntry) XXX_Size() int {
	return xxx_messageInfo_ObjectUUIDMapEntry.Size(m)
}
func (m *ObjectUUIDMapEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectUUIDMapEntry.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectUUIDMapEntry proto.InternalMessageInfo

func (m *ObjectUUIDMapEntry) GetIdentifier() uint64 {
	if m != nil && m.Identifier != nil {
		return *m.Identifier
	}
	return 0
}

func (m *ObjectUUIDMapEntry) GetUuid() *UUID {
	if m != nil {
		return m.Uuid
	}
	return nil
}

type FeatureInfo struct {
	Identifier           *string  `protobuf:"bytes,1,req,name=identifier" json:"identifier,omitempty"`
	ReadVersion          []uint32 `protobuf:"varint,2,rep,packed,name=read_version,json=readVersion" json:"read_version,omitempty"`
	WriteVersion         []uint32 `protobuf:"varint,3,rep,packed,name=write_version,json=writeVersion" json:"write_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeatureInfo) Reset()         { *m = FeatureInfo{} }
func (m *FeatureInfo) String() string { return proto.CompactTextString(m) }
func (*FeatureInfo) ProtoMessage()    {}
func (*FeatureInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_47802bcfa9d8cfa9, []int{8}
}

func (m *FeatureInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeatureInfo.Unmarshal(m, b)
}
func (m *FeatureInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeatureInfo.Marshal(b, m, deterministic)
}
func (m *FeatureInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeatureInfo.Merge(m, src)
}
func (m *FeatureInfo) XXX_Size() int {
	return xxx_messageInfo_FeatureInfo.Size(m)
}
func (m *FeatureInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FeatureInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FeatureInfo proto.InternalMessageInfo

func (m *FeatureInfo) GetIdentifier() string {
	if m != nil && m.Identifier != nil {
		return *m.Identifier
	}
	return ""
}

func (m *FeatureInfo) GetReadVersion() []uint32 {
	if m != nil {
		return m.ReadVersion
	}
	return nil
}

func (m *FeatureInfo) GetWriteVersion() []uint32 {
	if m != nil {
		return m.WriteVersion
	}
	return nil
}

type PackageMetadata struct {
	LastObjectIdentifier *uint64                      `protobuf:"varint,1,req,name=last_object_identifier,json=lastObjectIdentifier" json:"last_object_identifier,omitempty"`
	Revision             *DocumentRevision            `protobuf:"bytes,2,opt,name=revision" json:"revision,omitempty"`
	Components           []*ComponentInfo             `protobuf:"bytes,3,rep,name=components" json:"components,omitempty"`
	Datas                []*DataInfo                  `protobuf:"bytes,4,rep,name=datas" json:"datas,omitempty"`
	ReadVersion          []uint32                     `protobuf:"varint,5,rep,packed,name=read_version,json=readVersion" json:"read_version,omitempty"`
	WriteVersion         []uint32                     `protobuf:"varint,6,rep,packed,name=write_version,json=writeVersion" json:"write_version,omitempty"`
	FileFormatVersion    []uint32                     `protobuf:"varint,7,rep,packed,name=file_format_version,json=fileFormatVersion" json:"file_format_version,omitempty"`
	SaveToken            *uint64                      `protobuf:"varint,8,opt,name=save_token,json=saveToken,def=0" json:"save_token,omitempty"`
	PreferredPackageType *PackageMetadata_PackageType `protobuf:"varint,9,opt,name=preferred_package_type,json=preferredPackageType,enum=TSP.PackageMetadata_PackageType,def=0" json:"preferred_package_type,omitempty"`
	DataMetadataMap      *Reference                   `protobuf:"bytes,10,opt,name=data_metadata_map,json=dataMetadataMap" json:"data_metadata_map,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *PackageMetadata) Reset()         { *m = PackageMetadata{} }
func (m *PackageMetadata) String() string { return proto.CompactTextString(m) }
func (*PackageMetadata) ProtoMessage()    {}
func (*PackageMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_47802bcfa9d8cfa9, []int{9}
}

func (m *PackageMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PackageMetadata.Unmarshal(m, b)
}
func (m *PackageMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PackageMetadata.Marshal(b, m, deterministic)
}
func (m *PackageMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PackageMetadata.Merge(m, src)
}
func (m *PackageMetadata) XXX_Size() int {
	return xxx_messageInfo_PackageMetadata.Size(m)
}
func (m *PackageMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_PackageMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_PackageMetadata proto.InternalMessageInfo

const Default_PackageMetadata_SaveToken uint64 = 0
const Default_PackageMetadata_PreferredPackageType PackageMetadata_PackageType = PackageMetadata_Default

func (m *PackageMetadata) GetLastObjectIdentifier() uint64 {
	if m != nil && m.LastObjectIdentifier != nil {
		return *m.LastObjectIdentifier
	}
	return 0
}

func (m *PackageMetadata) GetRevision() *DocumentRevision {
	if m != nil {
		return m.Revision
	}
	return nil
}

func (m *PackageMetadata) GetComponents() []*ComponentInfo {
	if m != nil {
		return m.Components
	}
	return nil
}

func (m *PackageMetadata) GetDatas() []*DataInfo {
	if m != nil {
		return m.Datas
	}
	return nil
}

func (m *PackageMetadata) GetReadVersion() []uint32 {
	if m != nil {
		return m.ReadVersion
	}
	return nil
}

func (m *PackageMetadata) GetWriteVersion() []uint32 {
	if m != nil {
		return m.WriteVersion
	}
	return nil
}

func (m *PackageMetadata) GetFileFormatVersion() []uint32 {
	if m != nil {
		return m.FileFormatVersion
	}
	return nil
}

func (m *PackageMetadata) GetSaveToken() uint64 {
	if m != nil && m.SaveToken != nil {
		return *m.SaveToken
	}
	return Default_PackageMetadata_SaveToken
}

func (m *PackageMetadata) GetPreferredPackageType() PackageMetadata_PackageType {
	if m != nil && m.PreferredPackageType != nil {
		return *m.PreferredPackageType
	}
	return Default_PackageMetadata_PreferredPackageType
}

func (m *PackageMetadata) GetDataMetadataMap() *Reference {
	if m != nil {
		return m.DataMetadataMap
	}
	return nil
}

type DocumentRevision struct {
	Sequence_32          *int32   `protobuf:"varint,3,opt,name=sequence_32,json=sequence32,def=0" json:"sequence_32,omitempty"`
	Identifier           *string  `protobuf:"bytes,2,opt,name=identifier" json:"identifier,omitempty"`
	Sequence_64          *uint64  `protobuf:"varint,1,opt,name=sequence_64,json=sequence64,def=0" json:"sequence_64,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DocumentRevision) Reset()         { *m = DocumentRevision{} }
func (m *DocumentRevision) String() string { return proto.CompactTextString(m) }
func (*DocumentRevision) ProtoMessage()    {}
func (*DocumentRevision) Descriptor() ([]byte, []int) {
	return fileDescriptor_47802bcfa9d8cfa9, []int{10}
}

func (m *DocumentRevision) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DocumentRevision.Unmarshal(m, b)
}
func (m *DocumentRevision) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DocumentRevision.Marshal(b, m, deterministic)
}
func (m *DocumentRevision) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DocumentRevision.Merge(m, src)
}
func (m *DocumentRevision) XXX_Size() int {
	return xxx_messageInfo_DocumentRevision.Size(m)
}
func (m *DocumentRevision) XXX_DiscardUnknown() {
	xxx_messageInfo_DocumentRevision.DiscardUnknown(m)
}

var xxx_messageInfo_DocumentRevision proto.InternalMessageInfo

const Default_DocumentRevision_Sequence_32 int32 = 0
const Default_DocumentRevision_Sequence_64 uint64 = 0

func (m *DocumentRevision) GetSequence_32() int32 {
	if m != nil && m.Sequence_32 != nil {
		return *m.Sequence_32
	}
	return Default_DocumentRevision_Sequence_32
}

func (m *DocumentRevision) GetIdentifier() string {
	if m != nil && m.Identifier != nil {
		return *m.Identifier
	}
	return ""
}

func (m *DocumentRevision) GetSequence_64() uint64 {
	if m != nil && m.Sequence_64 != nil {
		return *m.Sequence_64
	}
	return Default_DocumentRevision_Sequence_64
}

type PasteboardMetadata struct {
	Version              []uint32    `protobuf:"varint,1,rep,packed,name=version" json:"version,omitempty"`
	AppName              *string     `protobuf:"bytes,2,req,name=app_name,json=appName" json:"app_name,omitempty"`
	Datas                []*DataInfo `protobuf:"bytes,3,rep,name=datas" json:"datas,omitempty"`
	SourceDocumentUuid   *UUID       `protobuf:"bytes,5,opt,name=source_document_uuid,json=sourceDocumentUuid" json:"source_document_uuid,omitempty"`
	DataMetadataMap      *Reference  `protobuf:"bytes,6,opt,name=data_metadata_map,json=dataMetadataMap" json:"data_metadata_map,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PasteboardMetadata) Reset()         { *m = PasteboardMetadata{} }
func (m *PasteboardMetadata) String() string { return proto.CompactTextString(m) }
func (*PasteboardMetadata) ProtoMessage()    {}
func (*PasteboardMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_47802bcfa9d8cfa9, []int{11}
}

func (m *PasteboardMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PasteboardMetadata.Unmarshal(m, b)
}
func (m *PasteboardMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PasteboardMetadata.Marshal(b, m, deterministic)
}
func (m *PasteboardMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PasteboardMetadata.Merge(m, src)
}
func (m *PasteboardMetadata) XXX_Size() int {
	return xxx_messageInfo_PasteboardMetadata.Size(m)
}
func (m *PasteboardMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_PasteboardMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_PasteboardMetadata proto.InternalMessageInfo

func (m *PasteboardMetadata) GetVersion() []uint32 {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *PasteboardMetadata) GetAppName() string {
	if m != nil && m.AppName != nil {
		return *m.AppName
	}
	return ""
}

func (m *PasteboardMetadata) GetDatas() []*DataInfo {
	if m != nil {
		return m.Datas
	}
	return nil
}

func (m *PasteboardMetadata) GetSourceDocumentUuid() *UUID {
	if m != nil {
		return m.SourceDocumentUuid
	}
	return nil
}

func (m *PasteboardMetadata) GetDataMetadataMap() *Reference {
	if m != nil {
		return m.DataMetadataMap
	}
	return nil
}

type DataInfo struct {
	Identifier                 *uint64                    `protobuf:"varint,1,req,name=identifier" json:"identifier,omitempty"`
	Digest                     []byte                     `protobuf:"bytes,2,req,name=digest" json:"digest,omitempty"`
	PreferredFileName          *string                    `protobuf:"bytes,3,req,name=preferred_file_name,json=preferredFileName" json:"preferred_file_name,omitempty"`
	FileName                   *string                    `protobuf:"bytes,4,opt,name=file_name,json=fileName" json:"file_name,omitempty"`
	DocumentResourceLocator    *string                    `protobuf:"bytes,5,opt,name=document_resource_locator,json=documentResourceLocator" json:"document_resource_locator,omitempty"`
	SourceBookmarkData         []byte                     `protobuf:"bytes,6,opt,name=source_bookmark_data,json=sourceBookmarkData" json:"source_bookmark_data,omitempty"`
	RemoteUrl                  *string                    `protobuf:"bytes,7,opt,name=remote_url,json=remoteUrl" json:"remote_url,omitempty"`
	CanDownload                *bool                      `protobuf:"varint,8,opt,name=can_download,json=canDownload,def=0" json:"can_download,omitempty"`
	DownloadPriority           *DataInfo_DownloadPriority `protobuf:"varint,9,opt,name=download_priority,json=downloadPriority,enum=TSP.DataInfo_DownloadPriority,def=1" json:"download_priority,omitempty"`
	Attributes                 *DataAttributes            `protobuf:"bytes,10,opt,name=attributes" json:"attributes,omitempty"`
	EncryptionInfo             *EncryptionInfo            `protobuf:"bytes,11,opt,name=encryption_info,json=encryptionInfo" json:"encryption_info,omitempty"`
	PasteboardExternalFilePath *string                    `protobuf:"bytes,99,opt,name=pasteboard_external_file_path,json=pasteboardExternalFilePath" json:"pasteboard_external_file_path,omitempty"`
	XXX_NoUnkeyedLiteral       struct{}                   `json:"-"`
	XXX_unrecognized           []byte                     `json:"-"`
	XXX_sizecache              int32                      `json:"-"`
}

func (m *DataInfo) Reset()         { *m = DataInfo{} }
func (m *DataInfo) String() string { return proto.CompactTextString(m) }
func (*DataInfo) ProtoMessage()    {}
func (*DataInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_47802bcfa9d8cfa9, []int{12}
}

func (m *DataInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataInfo.Unmarshal(m, b)
}
func (m *DataInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataInfo.Marshal(b, m, deterministic)
}
func (m *DataInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataInfo.Merge(m, src)
}
func (m *DataInfo) XXX_Size() int {
	return xxx_messageInfo_DataInfo.Size(m)
}
func (m *DataInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DataInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DataInfo proto.InternalMessageInfo

const Default_DataInfo_CanDownload bool = false
const Default_DataInfo_DownloadPriority DataInfo_DownloadPriority = DataInfo_Default

func (m *DataInfo) GetIdentifier() uint64 {
	if m != nil && m.Identifier != nil {
		return *m.Identifier
	}
	return 0
}

func (m *DataInfo) GetDigest() []byte {
	if m != nil {
		return m.Digest
	}
	return nil
}

func (m *DataInfo) GetPreferredFileName() string {
	if m != nil && m.PreferredFileName != nil {
		return *m.PreferredFileName
	}
	return ""
}

func (m *DataInfo) GetFileName() string {
	if m != nil && m.FileName != nil {
		return *m.FileName
	}
	return ""
}

func (m *DataInfo) GetDocumentResourceLocator() string {
	if m != nil && m.DocumentResourceLocator != nil {
		return *m.DocumentResourceLocator
	}
	return ""
}

func (m *DataInfo) GetSourceBookmarkData() []byte {
	if m != nil {
		return m.SourceBookmarkData
	}
	return nil
}

func (m *DataInfo) GetRemoteUrl() string {
	if m != nil && m.RemoteUrl != nil {
		return *m.RemoteUrl
	}
	return ""
}

func (m *DataInfo) GetCanDownload() bool {
	if m != nil && m.CanDownload != nil {
		return *m.CanDownload
	}
	return Default_DataInfo_CanDownload
}

func (m *DataInfo) GetDownloadPriority() DataInfo_DownloadPriority {
	if m != nil && m.DownloadPriority != nil {
		return *m.DownloadPriority
	}
	return Default_DataInfo_DownloadPriority
}

func (m *DataInfo) GetAttributes() *DataAttributes {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *DataInfo) GetEncryptionInfo() *EncryptionInfo {
	if m != nil {
		return m.EncryptionInfo
	}
	return nil
}

func (m *DataInfo) GetPasteboardExternalFilePath() string {
	if m != nil && m.PasteboardExternalFilePath != nil {
		return *m.PasteboardExternalFilePath
	}
	return ""
}

type DataMetadataMap struct {
	DataMetadataEntries  []*DataMetadataMap_DataMetadataMapEntry `protobuf:"bytes,1,rep,name=data_metadata_entries,json=dataMetadataEntries" json:"data_metadata_entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                `json:"-"`
	XXX_unrecognized     []byte                                  `json:"-"`
	XXX_sizecache        int32                                   `json:"-"`
}

func (m *DataMetadataMap) Reset()         { *m = DataMetadataMap{} }
func (m *DataMetadataMap) String() string { return proto.CompactTextString(m) }
func (*DataMetadataMap) ProtoMessage()    {}
func (*DataMetadataMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_47802bcfa9d8cfa9, []int{13}
}

func (m *DataMetadataMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataMetadataMap.Unmarshal(m, b)
}
func (m *DataMetadataMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataMetadataMap.Marshal(b, m, deterministic)
}
func (m *DataMetadataMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataMetadataMap.Merge(m, src)
}
func (m *DataMetadataMap) XXX_Size() int {
	return xxx_messageInfo_DataMetadataMap.Size(m)
}
func (m *DataMetadataMap) XXX_DiscardUnknown() {
	xxx_messageInfo_DataMetadataMap.DiscardUnknown(m)
}

var xxx_messageInfo_DataMetadataMap proto.InternalMessageInfo

func (m *DataMetadataMap) GetDataMetadataEntries() []*DataMetadataMap_DataMetadataMapEntry {
	if m != nil {
		return m.DataMetadataEntries
	}
	return nil
}

type DataMetadataMap_DataMetadataMapEntry struct {
	DataIdentifier       *uint64    `protobuf:"varint,1,req,name=data_identifier,json=dataIdentifier" json:"data_identifier,omitempty"`
	DataMetadata         *Reference `protobuf:"bytes,2,req,name=data_metadata,json=dataMetadata" json:"data_metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *DataMetadataMap_DataMetadataMapEntry) Reset()         { *m = DataMetadataMap_DataMetadataMapEntry{} }
func (m *DataMetadataMap_DataMetadataMapEntry) String() string { return proto.CompactTextString(m) }
func (*DataMetadataMap_DataMetadataMapEntry) ProtoMessage()    {}
func (*DataMetadataMap_DataMetadataMapEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_47802bcfa9d8cfa9, []int{13, 0}
}

func (m *DataMetadataMap_DataMetadataMapEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataMetadataMap_DataMetadataMapEntry.Unmarshal(m, b)
}
func (m *DataMetadataMap_DataMetadataMapEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataMetadataMap_DataMetadataMapEntry.Marshal(b, m, deterministic)
}
func (m *DataMetadataMap_DataMetadataMapEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataMetadataMap_DataMetadataMapEntry.Merge(m, src)
}
func (m *DataMetadataMap_DataMetadataMapEntry) XXX_Size() int {
	return xxx_messageInfo_DataMetadataMap_DataMetadataMapEntry.Size(m)
}
func (m *DataMetadataMap_DataMetadataMapEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_DataMetadataMap_DataMetadataMapEntry.DiscardUnknown(m)
}

var xxx_messageInfo_DataMetadataMap_DataMetadataMapEntry proto.InternalMessageInfo

func (m *DataMetadataMap_DataMetadataMapEntry) GetDataIdentifier() uint64 {
	if m != nil && m.DataIdentifier != nil {
		return *m.DataIdentifier
	}
	return 0
}

func (m *DataMetadataMap_DataMetadataMapEntry) GetDataMetadata() *Reference {
	if m != nil {
		return m.DataMetadata
	}
	return nil
}

type DataMetadata struct {
	FallbackColor        *Color   `protobuf:"bytes,1,opt,name=fallback_color,json=fallbackColor" json:"fallback_color,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataMetadata) Reset()         { *m = DataMetadata{} }
func (m *DataMetadata) String() string { return proto.CompactTextString(m) }
func (*DataMetadata) ProtoMessage()    {}
func (*DataMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_47802bcfa9d8cfa9, []int{14}
}

func (m *DataMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataMetadata.Unmarshal(m, b)
}
func (m *DataMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataMetadata.Marshal(b, m, deterministic)
}
func (m *DataMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataMetadata.Merge(m, src)
}
func (m *DataMetadata) XXX_Size() int {
	return xxx_messageInfo_DataMetadata.Size(m)
}
func (m *DataMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_DataMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_DataMetadata proto.InternalMessageInfo

func (m *DataMetadata) GetFallbackColor() *Color {
	if m != nil {
		return m.FallbackColor
	}
	return nil
}

type EncryptionInfo struct {
	DecodedLength        *uint64                `protobuf:"varint,1,opt,name=decoded_length,json=decodedLength" json:"decoded_length,omitempty"`
	PreferredBlockSize   *uint64                `protobuf:"varint,2,opt,name=preferred_block_size,json=preferredBlockSize" json:"preferred_block_size,omitempty"`
	BlockInfos           []*EncryptionBlockInfo `protobuf:"bytes,3,rep,name=block_infos,json=blockInfos" json:"block_infos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *EncryptionInfo) Reset()         { *m = EncryptionInfo{} }
func (m *EncryptionInfo) String() string { return proto.CompactTextString(m) }
func (*EncryptionInfo) ProtoMessage()    {}
func (*EncryptionInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_47802bcfa9d8cfa9, []int{15}
}

func (m *EncryptionInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EncryptionInfo.Unmarshal(m, b)
}
func (m *EncryptionInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EncryptionInfo.Marshal(b, m, deterministic)
}
func (m *EncryptionInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EncryptionInfo.Merge(m, src)
}
func (m *EncryptionInfo) XXX_Size() int {
	return xxx_messageInfo_EncryptionInfo.Size(m)
}
func (m *EncryptionInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_EncryptionInfo.DiscardUnknown(m)
}

var xxx_messageInfo_EncryptionInfo proto.InternalMessageInfo

func (m *EncryptionInfo) GetDecodedLength() uint64 {
	if m != nil && m.DecodedLength != nil {
		return *m.DecodedLength
	}
	return 0
}

func (m *EncryptionInfo) GetPreferredBlockSize() uint64 {
	if m != nil && m.PreferredBlockSize != nil {
		return *m.PreferredBlockSize
	}
	return 0
}

func (m *EncryptionInfo) GetBlockInfos() []*EncryptionBlockInfo {
	if m != nil {
		return m.BlockInfos
	}
	return nil
}

type EncryptionBlockInfo struct {
	EncodedLength        *uint64  `protobuf:"varint,1,req,name=encoded_length,json=encodedLength" json:"encoded_length,omitempty"`
	DecodedLength        *uint64  `protobuf:"varint,2,opt,name=decoded_length,json=decodedLength" json:"decoded_length,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EncryptionBlockInfo) Reset()         { *m = EncryptionBlockInfo{} }
func (m *EncryptionBlockInfo) String() string { return proto.CompactTextString(m) }
func (*EncryptionBlockInfo) ProtoMessage()    {}
func (*EncryptionBlockInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_47802bcfa9d8cfa9, []int{16}
}

func (m *EncryptionBlockInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EncryptionBlockInfo.Unmarshal(m, b)
}
func (m *EncryptionBlockInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EncryptionBlockInfo.Marshal(b, m, deterministic)
}
func (m *EncryptionBlockInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EncryptionBlockInfo.Merge(m, src)
}
func (m *EncryptionBlockInfo) XXX_Size() int {
	return xxx_messageInfo_EncryptionBlockInfo.Size(m)
}
func (m *EncryptionBlockInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_EncryptionBlockInfo.DiscardUnknown(m)
}

var xxx_messageInfo_EncryptionBlockInfo proto.InternalMessageInfo

func (m *EncryptionBlockInfo) GetEncodedLength() uint64 {
	if m != nil && m.EncodedLength != nil {
		return *m.EncodedLength
	}
	return 0
}

func (m *EncryptionBlockInfo) GetDecodedLength() uint64 {
	if m != nil && m.DecodedLength != nil {
		return *m.DecodedLength
	}
	return 0
}

type ViewStateMetadata struct {
	Version                      []uint32              `protobuf:"varint,1,rep,packed,name=version" json:"version,omitempty"`
	VersionUuid                  *UUID                 `protobuf:"bytes,4,opt,name=version_uuid,json=versionUuid" json:"version_uuid,omitempty"`
	Component                    *ComponentInfo        `protobuf:"bytes,3,req,name=component" json:"component,omitempty"`
	ExternalObjectUuidMapEntries []*ObjectUUIDMapEntry `protobuf:"bytes,5,rep,name=external_object_uuid_map_entries,json=externalObjectUuidMapEntries" json:"external_object_uuid_map_entries,omitempty"`
	XXX_NoUnkeyedLiteral         struct{}              `json:"-"`
	XXX_unrecognized             []byte                `json:"-"`
	XXX_sizecache                int32                 `json:"-"`
}

func (m *ViewStateMetadata) Reset()         { *m = ViewStateMetadata{} }
func (m *ViewStateMetadata) String() string { return proto.CompactTextString(m) }
func (*ViewStateMetadata) ProtoMessage()    {}
func (*ViewStateMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_47802bcfa9d8cfa9, []int{17}
}

func (m *ViewStateMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewStateMetadata.Unmarshal(m, b)
}
func (m *ViewStateMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewStateMetadata.Marshal(b, m, deterministic)
}
func (m *ViewStateMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewStateMetadata.Merge(m, src)
}
func (m *ViewStateMetadata) XXX_Size() int {
	return xxx_messageInfo_ViewStateMetadata.Size(m)
}
func (m *ViewStateMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewStateMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_ViewStateMetadata proto.InternalMessageInfo

func (m *ViewStateMetadata) GetVersion() []uint32 {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *ViewStateMetadata) GetVersionUuid() *UUID {
	if m != nil {
		return m.VersionUuid
	}
	return nil
}

func (m *ViewStateMetadata) GetComponent() *ComponentInfo {
	if m != nil {
		return m.Component
	}
	return nil
}

func (m *ViewStateMetadata) GetExternalObjectUuidMapEntries() []*ObjectUUIDMapEntry {
	if m != nil {
		return m.ExternalObjectUuidMapEntries
	}
	return nil
}

type ObjectSerializationMetadata struct {
	Version                      []uint32              `protobuf:"varint,1,rep,packed,name=version" json:"version,omitempty"`
	SourceDocumentUuid           *UUID                 `protobuf:"bytes,2,opt,name=source_document_uuid,json=sourceDocumentUuid" json:"source_document_uuid,omitempty"`
	VersionUuid                  *UUID                 `protobuf:"bytes,3,opt,name=version_uuid,json=versionUuid" json:"version_uuid,omitempty"`
	Component                    *ComponentInfo        `protobuf:"bytes,4,req,name=component" json:"component,omitempty"`
	Datas                        []*DataInfo           `protobuf:"bytes,5,rep,name=datas" json:"datas,omitempty"`
	ExternalObjectUuidMapEntries []*ObjectUUIDMapEntry `protobuf:"bytes,6,rep,name=external_object_uuid_map_entries,json=externalObjectUuidMapEntries" json:"external_object_uuid_map_entries,omitempty"`
	DataMetadataMap              *Reference            `protobuf:"bytes,7,opt,name=data_metadata_map,json=dataMetadataMap" json:"data_metadata_map,omitempty"`
	XXX_NoUnkeyedLiteral         struct{}              `json:"-"`
	XXX_unrecognized             []byte                `json:"-"`
	XXX_sizecache                int32                 `json:"-"`
}

func (m *ObjectSerializationMetadata) Reset()         { *m = ObjectSerializationMetadata{} }
func (m *ObjectSerializationMetadata) String() string { return proto.CompactTextString(m) }
func (*ObjectSerializationMetadata) ProtoMessage()    {}
func (*ObjectSerializationMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_47802bcfa9d8cfa9, []int{18}
}

func (m *ObjectSerializationMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectSerializationMetadata.Unmarshal(m, b)
}
func (m *ObjectSerializationMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectSerializationMetadata.Marshal(b, m, deterministic)
}
func (m *ObjectSerializationMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectSerializationMetadata.Merge(m, src)
}
func (m *ObjectSerializationMetadata) XXX_Size() int {
	return xxx_messageInfo_ObjectSerializationMetadata.Size(m)
}
func (m *ObjectSerializationMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectSerializationMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectSerializationMetadata proto.InternalMessageInfo

func (m *ObjectSerializationMetadata) GetVersion() []uint32 {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *ObjectSerializationMetadata) GetSourceDocumentUuid() *UUID {
	if m != nil {
		return m.SourceDocumentUuid
	}
	return nil
}

func (m *ObjectSerializationMetadata) GetVersionUuid() *UUID {
	if m != nil {
		return m.VersionUuid
	}
	return nil
}

func (m *ObjectSerializationMetadata) GetComponent() *ComponentInfo {
	if m != nil {
		return m.Component
	}
	return nil
}

func (m *ObjectSerializationMetadata) GetDatas() []*DataInfo {
	if m != nil {
		return m.Datas
	}
	return nil
}

func (m *ObjectSerializationMetadata) GetExternalObjectUuidMapEntries() []*ObjectUUIDMapEntry {
	if m != nil {
		return m.ExternalObjectUuidMapEntries
	}
	return nil
}

func (m *ObjectSerializationMetadata) GetDataMetadataMap() *Reference {
	if m != nil {
		return m.DataMetadataMap
	}
	return nil
}

type ObjectSerializationDirectory struct {
	Entries              []*ObjectSerializationDirectory_Entry `protobuf:"bytes,1,rep,name=entries" json:"entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *ObjectSerializationDirectory) Reset()         { *m = ObjectSerializationDirectory{} }
func (m *ObjectSerializationDirectory) String() string { return proto.CompactTextString(m) }
func (*ObjectSerializationDirectory) ProtoMessage()    {}
func (*ObjectSerializationDirectory) Descriptor() ([]byte, []int) {
	return fileDescriptor_47802bcfa9d8cfa9, []int{19}
}

func (m *ObjectSerializationDirectory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectSerializationDirectory.Unmarshal(m, b)
}
func (m *ObjectSerializationDirectory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectSerializationDirectory.Marshal(b, m, deterministic)
}
func (m *ObjectSerializationDirectory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectSerializationDirectory.Merge(m, src)
}
func (m *ObjectSerializationDirectory) XXX_Size() int {
	return xxx_messageInfo_ObjectSerializationDirectory.Size(m)
}
func (m *ObjectSerializationDirectory) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectSerializationDirectory.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectSerializationDirectory proto.InternalMessageInfo

func (m *ObjectSerializationDirectory) GetEntries() []*ObjectSerializationDirectory_Entry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type ObjectSerializationDirectory_Entry struct {
	Locator              *string  `protobuf:"bytes,1,req,name=locator" json:"locator,omitempty"`
	Offset               *uint64  `protobuf:"varint,2,req,name=offset" json:"offset,omitempty"`
	Size                 *uint64  `protobuf:"varint,3,req,name=size" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ObjectSerializationDirectory_Entry) Reset()         { *m = ObjectSerializationDirectory_Entry{} }
func (m *ObjectSerializationDirectory_Entry) String() string { return proto.CompactTextString(m) }
func (*ObjectSerializationDirectory_Entry) ProtoMessage()    {}
func (*ObjectSerializationDirectory_Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_47802bcfa9d8cfa9, []int{19, 0}
}

func (m *ObjectSerializationDirectory_Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectSerializationDirectory_Entry.Unmarshal(m, b)
}
func (m *ObjectSerializationDirectory_Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectSerializationDirectory_Entry.Marshal(b, m, deterministic)
}
func (m *ObjectSerializationDirectory_Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectSerializationDirectory_Entry.Merge(m, src)
}
func (m *ObjectSerializationDirectory_Entry) XXX_Size() int {
	return xxx_messageInfo_ObjectSerializationDirectory_Entry.Size(m)
}
func (m *ObjectSerializationDirectory_Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectSerializationDirectory_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectSerializationDirectory_Entry proto.InternalMessageInfo

func (m *ObjectSerializationDirectory_Entry) GetLocator() string {
	if m != nil && m.Locator != nil {
		return *m.Locator
	}
	return ""
}

func (m *ObjectSerializationDirectory_Entry) GetOffset() uint64 {
	if m != nil && m.Offset != nil {
		return *m.Offset
	}
	return 0
}

func (m *ObjectSerializationDirectory_Entry) GetSize() uint64 {
	if m != nil && m.Size != nil {
		return *m.Size
	}
	return 0
}

type DocumentMetadata struct {
	IsInCollaborationMode *bool    `protobuf:"varint,1,opt,name=is_in_collaboration_mode,json=isInCollaborationMode" json:"is_in_collaboration_mode,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *DocumentMetadata) Reset()         { *m = DocumentMetadata{} }
func (m *DocumentMetadata) String() string { return proto.CompactTextString(m) }
func (*DocumentMetadata) ProtoMessage()    {}
func (*DocumentMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_47802bcfa9d8cfa9, []int{20}
}

func (m *DocumentMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DocumentMetadata.Unmarshal(m, b)
}
func (m *DocumentMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DocumentMetadata.Marshal(b, m, deterministic)
}
func (m *DocumentMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DocumentMetadata.Merge(m, src)
}
func (m *DocumentMetadata) XXX_Size() int {
	return xxx_messageInfo_DocumentMetadata.Size(m)
}
func (m *DocumentMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_DocumentMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_DocumentMetadata proto.InternalMessageInfo

func (m *DocumentMetadata) GetIsInCollaborationMode() bool {
	if m != nil && m.IsInCollaborationMode != nil {
		return *m.IsInCollaborationMode
	}
	return false
}

type SupportMetadata struct {
	IsInCollaborationMode  *bool            `protobuf:"varint,1,opt,name=is_in_collaboration_mode,json=isInCollaborationMode" json:"is_in_collaboration_mode,omitempty"`
	AcknowledgedServerData []*DataReference `protobuf:"bytes,2,rep,name=acknowledged_server_data,json=acknowledgedServerData" json:"acknowledged_server_data,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}         `json:"-"`
	XXX_unrecognized       []byte           `json:"-"`
	XXX_sizecache          int32            `json:"-"`
}

func (m *SupportMetadata) Reset()         { *m = SupportMetadata{} }
func (m *SupportMetadata) String() string { return proto.CompactTextString(m) }
func (*SupportMetadata) ProtoMessage()    {}
func (*SupportMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_47802bcfa9d8cfa9, []int{21}
}

func (m *SupportMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SupportMetadata.Unmarshal(m, b)
}
func (m *SupportMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SupportMetadata.Marshal(b, m, deterministic)
}
func (m *SupportMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SupportMetadata.Merge(m, src)
}
func (m *SupportMetadata) XXX_Size() int {
	return xxx_messageInfo_SupportMetadata.Size(m)
}
func (m *SupportMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_SupportMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_SupportMetadata proto.InternalMessageInfo

func (m *SupportMetadata) GetIsInCollaborationMode() bool {
	if m != nil && m.IsInCollaborationMode != nil {
		return *m.IsInCollaborationMode
	}
	return false
}

func (m *SupportMetadata) GetAcknowledgedServerData() []*DataReference {
	if m != nil {
		return m.AcknowledgedServerData
	}
	return nil
}

func init() {
	proto.RegisterEnum("TSP.FieldInfo_Type", FieldInfo_Type_name, FieldInfo_Type_value)
	proto.RegisterEnum("TSP.FieldInfo_UnknownFieldRule", FieldInfo_UnknownFieldRule_name, FieldInfo_UnknownFieldRule_value)
	proto.RegisterEnum("TSP.FieldInfo_KnownFieldRule", FieldInfo_KnownFieldRule_name, FieldInfo_KnownFieldRule_value)
	proto.RegisterEnum("TSP.PackageMetadata_PackageType", PackageMetadata_PackageType_name, PackageMetadata_PackageType_value)
	proto.RegisterEnum("TSP.DataInfo_DownloadPriority", DataInfo_DownloadPriority_name, DataInfo_DownloadPriority_value)
	proto.RegisterType((*ArchiveInfo)(nil), "TSP.ArchiveInfo")
	proto.RegisterType((*MessageInfo)(nil), "TSP.MessageInfo")
	proto.RegisterType((*FieldInfo)(nil), "TSP.FieldInfo")
	proto.RegisterType((*FieldPath)(nil), "TSP.FieldPath")
	proto.RegisterType((*ComponentInfo)(nil), "TSP.ComponentInfo")
	proto.RegisterType((*ComponentExternalReference)(nil), "TSP.ComponentExternalReference")
	proto.RegisterType((*ComponentDataReference)(nil), "TSP.ComponentDataReference")
	proto.RegisterType((*ObjectUUIDMapEntry)(nil), "TSP.ObjectUUIDMapEntry")
	proto.RegisterType((*FeatureInfo)(nil), "TSP.FeatureInfo")
	proto.RegisterType((*PackageMetadata)(nil), "TSP.PackageMetadata")
	proto.RegisterType((*DocumentRevision)(nil), "TSP.DocumentRevision")
	proto.RegisterType((*PasteboardMetadata)(nil), "TSP.PasteboardMetadata")
	proto.RegisterType((*DataInfo)(nil), "TSP.DataInfo")
	proto.RegisterType((*DataMetadataMap)(nil), "TSP.DataMetadataMap")
	proto.RegisterType((*DataMetadataMap_DataMetadataMapEntry)(nil), "TSP.DataMetadataMap.DataMetadataMapEntry")
	proto.RegisterType((*DataMetadata)(nil), "TSP.DataMetadata")
	proto.RegisterType((*EncryptionInfo)(nil), "TSP.EncryptionInfo")
	proto.RegisterType((*EncryptionBlockInfo)(nil), "TSP.EncryptionBlockInfo")
	proto.RegisterType((*ViewStateMetadata)(nil), "TSP.ViewStateMetadata")
	proto.RegisterType((*ObjectSerializationMetadata)(nil), "TSP.ObjectSerializationMetadata")
	proto.RegisterType((*ObjectSerializationDirectory)(nil), "TSP.ObjectSerializationDirectory")
	proto.RegisterType((*ObjectSerializationDirectory_Entry)(nil), "TSP.ObjectSerializationDirectory.Entry")
	proto.RegisterType((*DocumentMetadata)(nil), "TSP.DocumentMetadata")
	proto.RegisterType((*SupportMetadata)(nil), "TSP.SupportMetadata")
}

func init() { proto.RegisterFile("TSPArchiveMessages.proto", fileDescriptor_47802bcfa9d8cfa9) }

var fileDescriptor_47802bcfa9d8cfa9 = []byte{
	// 2153 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x58, 0xcd, 0x6e, 0xdb, 0xca,
	0x15, 0x0e, 0xf5, 0x63, 0x49, 0x87, 0x92, 0x4c, 0x8f, 0x1d, 0x47, 0xf9, 0xbd, 0x2a, 0x83, 0x20,
	0xbe, 0xb8, 0x17, 0x76, 0xa2, 0xa4, 0x69, 0xaf, 0xdb, 0x8d, 0x13, 0x27, 0xa8, 0x71, 0xe3, 0x44,
	0xa0, 0xec, 0x04, 0x28, 0x50, 0x10, 0x23, 0x72, 0x64, 0x4f, 0x45, 0x71, 0xd4, 0xe1, 0xc8, 0x8e,
	0x83, 0x76, 0xdd, 0x07, 0x28, 0x0a, 0x14, 0x5d, 0xf7, 0x01, 0xfa, 0x2a, 0xdd, 0xf4, 0x11, 0x8a,
	0x02, 0xdd, 0x75, 0x5f, 0xb4, 0x98, 0xe1, 0x90, 0x22, 0x29, 0x25, 0x51, 0x71, 0xb5, 0xd2, 0xcc,
	0xf9, 0xe1, 0x39, 0xdf, 0xf9, 0x25, 0xa1, 0x73, 0x32, 0xe8, 0x1f, 0x70, 0xef, 0x9c, 0x5e, 0x90,
	0x63, 0x12, 0x45, 0xf8, 0x8c, 0x44, 0xbb, 0x53, 0xce, 0x04, 0x43, 0xe5, 0x93, 0x41, 0xff, 0xd6,
	0xc6, 0xc9, 0xa0, 0x9f, 0xbf, 0xb7, 0x7f, 0x6f, 0x80, 0xa9, 0x25, 0x8e, 0xc2, 0x11, 0x43, 0xf7,
	0x00, 0xa8, 0x4f, 0x42, 0x41, 0x47, 0x94, 0xf0, 0x8e, 0xd1, 0x35, 0x76, 0x2a, 0x4e, 0xe6, 0x06,
	0xfd, 0x18, 0x5a, 0x93, 0x58, 0x83, 0x4b, 0xc3, 0x11, 0x8b, 0x3a, 0xa5, 0x6e, 0x79, 0xc7, 0xec,
	0x59, 0xbb, 0x27, 0x83, 0xfe, 0xae, 0xd6, 0x2d, 0x15, 0x39, 0xcd, 0xc9, 0xfc, 0x10, 0xa1, 0x1f,
	0x41, 0x33, 0x3a, 0x67, 0xb3, 0xc0, 0x77, 0x27, 0x84, 0x9f, 0x91, 0x4e, 0xb9, 0x6b, 0xec, 0xd4,
	0x1d, 0x33, 0xbe, 0x3b, 0x96, 0x57, 0xf6, 0x3f, 0xcb, 0x60, 0x66, 0x14, 0x20, 0x04, 0x15, 0x71,
	0x35, 0x25, 0x1d, 0xa3, 0x5b, 0xda, 0x69, 0x39, 0xea, 0x3f, 0xba, 0x03, 0xb5, 0x0b, 0xc2, 0x23,
	0xca, 0x42, 0xf5, 0xdc, 0xd6, 0xf3, 0x92, 0x65, 0x38, 0xc9, 0x15, 0xda, 0x86, 0xb5, 0x80, 0x84,
	0x67, 0xe2, 0xbc, 0x53, 0x56, 0x32, 0xfa, 0x84, 0xf6, 0xc0, 0x1c, 0x51, 0x12, 0xf8, 0xda, 0xe2,
	0x8a, 0xb2, 0xb8, 0xad, 0x2c, 0x7e, 0x25, 0xef, 0x95, 0xbd, 0x30, 0x4a, 0xfe, 0x46, 0x68, 0x0f,
	0x36, 0xd8, 0xf0, 0xd7, 0xc4, 0x13, 0x2e, 0x27, 0x23, 0xc2, 0x49, 0xe8, 0x91, 0xa8, 0x53, 0xed,
	0x96, 0x77, 0x2a, 0xea, 0x81, 0x56, 0x4c, 0x74, 0x52, 0x1a, 0xfa, 0x06, 0xd6, 0x7d, 0x2c, 0x70,
	0x96, 0x7d, 0x2d, 0x65, 0x6f, 0x4b, 0x52, 0x86, 0xf9, 0x5b, 0x40, 0x43, 0x1c, 0x11, 0x77, 0x8e,
	0xa3, 0x4f, 0x3e, 0x74, 0x6a, 0x5d, 0x63, 0xa7, 0xe5, 0x58, 0x92, 0x92, 0xa2, 0xe0, 0x93, 0x0f,
	0xe8, 0x11, 0x20, 0x9f, 0x8e, 0x46, 0x31, 0x6e, 0x6e, 0xe2, 0x7d, 0x3d, 0xf5, 0xde, 0x92, 0x54,
	0x85, 0xe0, 0x3b, 0x0d, 0xc3, 0x33, 0x58, 0x57, 0x12, 0xb1, 0xcf, 0x53, 0x2c, 0xce, 0x3b, 0x8d,
	0xae, 0x91, 0x77, 0xb9, 0x8f, 0xc5, 0xb9, 0xd3, 0x92, 0x6c, 0xe9, 0x11, 0xfd, 0x14, 0x2c, 0x25,
	0x12, 0xb9, 0x82, 0xb9, 0x9c, 0x4c, 0xd8, 0x05, 0xe9, 0x40, 0x11, 0x2b, 0x25, 0xd8, 0x8e, 0xf9,
	0x4e, 0x98, 0xa3, 0xb8, 0xd0, 0x2e, 0x6c, 0xa8, 0x27, 0x72, 0x82, 0xfd, 0xd4, 0x44, 0x33, 0x35,
	0x51, 0x99, 0xe3, 0x10, 0xec, 0x6b, 0x0b, 0xed, 0x3f, 0xac, 0x41, 0x23, 0x45, 0x1e, 0xd9, 0x50,
	0x51, 0x46, 0xca, 0x40, 0x2f, 0x3e, 0x4b, 0xd1, 0xd0, 0xae, 0x4e, 0x86, 0x52, 0xd7, 0xd8, 0x69,
	0xf7, 0x36, 0xf3, 0xb1, 0xdb, 0x3d, 0xb9, 0x9a, 0x92, 0xfd, 0xea, 0x3b, 0x1c, 0xcc, 0x88, 0x4e,
	0x94, 0x09, 0xa0, 0x59, 0x38, 0x0e, 0xd9, 0x65, 0xa8, 0x61, 0xe0, 0xb3, 0x20, 0xce, 0xba, 0x76,
	0xef, 0xab, 0x82, 0xf4, 0x69, 0xcc, 0xa8, 0x2e, 0x9c, 0x59, 0x40, 0xf6, 0xef, 0x1d, 0x9d, 0x85,
	0x8c, 0x93, 0x83, 0xd0, 0xef, 0x73, 0x12, 0x11, 0x7e, 0x41, 0x4e, 0x43, 0x41, 0x83, 0x63, 0xe6,
	0xcb, 0x1a, 0xf0, 0x1d, 0x6b, 0x56, 0x90, 0x58, 0x9e, 0x30, 0x95, 0xff, 0x2f, 0x61, 0xaa, 0x9f,
	0x4c, 0x98, 0x63, 0xb0, 0x16, 0x5c, 0x59, 0x53, 0xae, 0xdc, 0x2d, 0xb8, 0xf2, 0x7d, 0xde, 0x91,
	0xca, 0x1b, 0x16, 0x12, 0xa7, 0x5d, 0x30, 0xb6, 0x07, 0x9b, 0x59, 0x75, 0x49, 0xbc, 0x6a, 0x69,
	0xbc, 0x36, 0xe6, 0x02, 0x49, 0x4e, 0xbd, 0x80, 0x7b, 0x59, 0x99, 0x11, 0xc1, 0x62, 0xc6, 0x89,
	0x9b, 0x69, 0x15, 0xf5, 0xae, 0xb1, 0xd3, 0x70, 0x6e, 0xcf, 0x45, 0x5f, 0xc5, 0x3c, 0x47, 0x29,
	0x8b, 0xfd, 0x0a, 0x2a, 0x32, 0x52, 0xa8, 0x01, 0x71, 0xac, 0xac, 0x6b, 0x68, 0x13, 0xd6, 0xdf,
	0xe6, 0xb1, 0xb1, 0x0c, 0xb4, 0x01, 0xad, 0xc3, 0x2c, 0x02, 0x56, 0x09, 0x99, 0x50, 0xd3, 0x55,
	0x61, 0x95, 0xed, 0xdf, 0x82, 0x55, 0x8c, 0x19, 0xb2, 0xe1, 0x0b, 0x51, 0xb3, 0xae, 0xa1, 0xeb,
	0xb0, 0xb1, 0xc0, 0x63, 0x19, 0x08, 0x41, 0xfb, 0x78, 0x16, 0x89, 0xd3, 0xd0, 0x27, 0x3c, 0x12,
	0x38, 0xf4, 0xad, 0x12, 0xba, 0x09, 0xcd, 0x37, 0x4c, 0x0c, 0x66, 0xd3, 0x29, 0xe3, 0x82, 0xf8,
	0xd6, 0x7f, 0x93, 0x9f, 0x61, 0xbf, 0x87, 0x76, 0x1e, 0x66, 0x54, 0x07, 0x05, 0xb4, 0x75, 0x0d,
	0xdd, 0x87, 0xaf, 0x12, 0xc5, 0x6f, 0xc8, 0x25, 0xe1, 0xca, 0xcd, 0xbc, 0x19, 0x06, 0xda, 0x06,
	0xb4, 0xc8, 0x64, 0x95, 0xec, 0xfb, 0xba, 0x28, 0x54, 0x31, 0x6e, 0xa7, 0x45, 0x91, 0x44, 0x45,
	0x9d, 0xed, 0xbf, 0x57, 0xa0, 0xf5, 0x82, 0x4d, 0xa6, 0x2c, 0x24, 0xa1, 0x58, 0xda, 0xb1, 0x4b,
	0x85, 0x8e, 0xfd, 0x0d, 0x6c, 0x4c, 0x55, 0x9a, 0x71, 0xe2, 0xbb, 0x01, 0xf3, 0xb0, 0x60, 0xbc,
	0x53, 0xea, 0x96, 0x76, 0x1a, 0x8e, 0x95, 0x12, 0x5e, 0xc7, 0xf7, 0xa8, 0x03, 0xb5, 0x84, 0xa5,
	0xac, 0x02, 0x9a, 0x1c, 0xd1, 0x03, 0x68, 0xe6, 0xca, 0xbb, 0x92, 0x1a, 0x66, 0xf2, 0x79, 0x69,
	0xa3, 0x87, 0xd0, 0xba, 0xe4, 0x54, 0xcc, 0x3b, 0x55, 0x35, 0xe5, 0x6b, 0x2a, 0x42, 0xc2, 0xd8,
	0x87, 0x4d, 0xf2, 0x41, 0x10, 0x1e, 0xe2, 0xa0, 0xd8, 0x36, 0x4d, 0x5d, 0xa2, 0xa9, 0x9f, 0x2f,
	0x35, 0x63, 0x9a, 0x11, 0x0e, 0x22, 0xc5, 0xab, 0x08, 0x1d, 0x2e, 0xd6, 0x54, 0x4d, 0x69, 0xbb,
	0x9d, 0xd7, 0x96, 0xcb, 0xad, 0x85, 0x62, 0x7b, 0x03, 0x37, 0x74, 0x29, 0xcf, 0x66, 0xd4, 0x77,
	0x27, 0x78, 0xea, 0x92, 0x50, 0x70, 0x4a, 0x22, 0xd5, 0xd1, 0xcc, 0xde, 0x0d, 0xa5, 0x2d, 0xce,
	0xda, 0xd3, 0xd3, 0xa3, 0xc3, 0x63, 0x3c, 0x7d, 0x19, 0x0a, 0x7e, 0xe5, 0x6c, 0xc5, 0x72, 0xa7,
	0x33, 0xea, 0xeb, 0x3b, 0x4a, 0x22, 0x39, 0x30, 0xd3, 0x6a, 0x51, 0xe3, 0xa7, 0x95, 0x19, 0x98,
	0x49, 0x8d, 0xa8, 0x81, 0x39, 0x9a, 0x1f, 0x64, 0xcd, 0x77, 0x69, 0xe4, 0x46, 0x82, 0xc9, 0xa8,
	0xb1, 0x99, 0x88, 0xa8, 0x4f, 0x5c, 0x6d, 0x18, 0x8e, 0xe7, 0x75, 0x07, 0xe4, 0x10, 0xdd, 0xaf,
	0x8e, 0x70, 0x10, 0x11, 0xe7, 0x0e, 0x8d, 0x06, 0x8a, 0xfb, 0x6d, 0xcc, 0x1c, 0x1b, 0xa8, 0x47,
	0x3b, 0xea, 0x02, 0x44, 0xf8, 0x82, 0xb8, 0x82, 0x8d, 0x49, 0xd8, 0x69, 0xca, 0xb1, 0xbe, 0x6f,
	0x3c, 0x72, 0x1a, 0xf2, 0xf2, 0x44, 0xde, 0xd9, 0x7f, 0x34, 0xe0, 0xd6, 0xa7, 0x01, 0x47, 0x8f,
	0x61, 0xcb, 0x4b, 0xa8, 0xee, 0x42, 0xbe, 0x6d, 0xa6, 0xb4, 0xa3, 0x5c, 0xe2, 0x69, 0x83, 0x33,
	0xfc, 0x25, 0xb5, 0x51, 0xe8, 0x86, 0x98, 0x61, 0xbe, 0x01, 0x35, 0x1a, 0xb9, 0x97, 0x04, 0x8f,
	0xf5, 0x6e, 0xb0, 0x46, 0xa3, 0xf7, 0x04, 0x8f, 0xed, 0x03, 0xd8, 0x5e, 0x1e, 0x39, 0xf4, 0x50,
	0xc7, 0x7b, 0xc1, 0x1a, 0x15, 0xd2, 0x4c, 0xdf, 0x19, 0x00, 0x5a, 0x0c, 0xd7, 0x17, 0xeb, 0xe6,
	0x2e, 0x54, 0x64, 0x06, 0xa8, 0x52, 0x31, 0x7b, 0x0d, 0x15, 0x2f, 0xa9, 0xc0, 0x51, 0xd7, 0xf6,
	0xef, 0xc0, 0xcc, 0x44, 0x6f, 0x89, 0xb6, 0x46, 0x4e, 0x5b, 0xb1, 0x7c, 0x4a, 0x2b, 0x96, 0x4f,
	0x79, 0x79, 0xf9, 0xd8, 0x7f, 0xab, 0xc0, 0x7a, 0x1f, 0x7b, 0x63, 0x7c, 0x46, 0x8e, 0x89, 0xc0,
	0xd2, 0x63, 0xf4, 0x14, 0xb6, 0x03, 0x1c, 0x09, 0x77, 0x11, 0xf5, 0xd8, 0xbb, 0x2d, 0x49, 0x7d,
	0x5b, 0x44, 0xfe, 0x31, 0xd4, 0x39, 0xb9, 0xa0, 0xda, 0x2a, 0xb9, 0x27, 0x5c, 0x57, 0xbe, 0x1e,
	0x32, 0x6f, 0x36, 0x21, 0xa1, 0x70, 0x34, 0xd1, 0x49, 0xd9, 0x50, 0x0f, 0x20, 0x0d, 0x78, 0xa4,
	0x4c, 0x34, 0x7b, 0x28, 0x5f, 0x64, 0xf1, 0x4e, 0x35, 0xe7, 0x42, 0xf7, 0xa1, 0x2a, 0x8d, 0x4c,
	0xd6, 0xaf, 0x56, 0xfc, 0x0c, 0x19, 0x28, 0xc9, 0x19, 0xd3, 0x16, 0x50, 0xaa, 0xae, 0x88, 0xd2,
	0xda, 0x27, 0x9a, 0x4c, 0x0f, 0x36, 0x47, 0x34, 0x20, 0xee, 0x88, 0xf1, 0x09, 0x16, 0xcb, 0x46,
	0x9d, 0x24, 0xbf, 0x52, 0xd4, 0x44, 0x26, 0x5f, 0x2a, 0xf5, 0xc5, 0x52, 0x41, 0x2e, 0x6c, 0xcf,
	0x3b, 0xea, 0x34, 0x0e, 0x82, 0xab, 0xd6, 0x93, 0x86, 0x9a, 0xca, 0x5d, 0xe5, 0x5b, 0x21, 0x3a,
	0xc9, 0x59, 0xed, 0x2a, 0xb5, 0x43, 0x32, 0xc2, 0xb3, 0x40, 0x38, 0x5b, 0xa9, 0xa2, 0x0c, 0x19,
	0xed, 0xc3, 0x86, 0xca, 0xec, 0x89, 0x96, 0x95, 0x5d, 0x48, 0x55, 0x7b, 0xb2, 0x1e, 0xcd, 0xdb,
	0x97, 0x2a, 0x81, 0xe4, 0x19, 0xc7, 0x78, 0x6a, 0x7f, 0x07, 0x66, 0x56, 0x95, 0x09, 0xc9, 0xb3,
	0xac, 0x6b, 0xa8, 0x05, 0x8d, 0x43, 0xca, 0x89, 0x27, 0x18, 0xbf, 0xb2, 0x0c, 0xd4, 0x06, 0x18,
	0xd0, 0xf0, 0x2c, 0x20, 0xaf, 0x68, 0x20, 0x07, 0xd0, 0x47, 0xb0, 0x8a, 0x41, 0x47, 0x36, 0x98,
	0x11, 0xf9, 0xcd, 0x4c, 0x3e, 0xcb, 0x7d, 0xd2, 0x53, 0xb5, 0x59, 0x95, 0x70, 0x40, 0x72, 0xfb,
	0xa4, 0x57, 0xc8, 0xfd, 0x92, 0x9a, 0x1b, 0xd9, 0xdc, 0xcf, 0xea, 0x78, 0xf6, 0x34, 0x7e, 0xa9,
	0xc8, 0xe9, 0x78, 0xf6, 0xd4, 0xfe, 0x97, 0x01, 0xa8, 0x8f, 0x23, 0x41, 0x86, 0x0c, 0x73, 0x3f,
	0x4d, 0xe9, 0xcc, 0xc2, 0x6f, 0x2c, 0x2e, 0xfc, 0x37, 0xa1, 0x8e, 0xa7, 0x53, 0x37, 0xc4, 0x13,
	0xa2, 0x27, 0x5a, 0x0d, 0x4f, 0xa7, 0x6f, 0xf0, 0x84, 0xcc, 0xd3, 0xad, 0xfc, 0x99, 0x74, 0xfb,
	0x19, 0x6c, 0x45, 0x6c, 0xc6, 0x3d, 0xe2, 0xfa, 0xda, 0x6f, 0xd5, 0xf4, 0x3b, 0x55, 0x05, 0x75,
	0xa6, 0xe4, 0x51, 0xcc, 0x96, 0xa0, 0x23, 0x5b, 0xfc, 0xf2, 0x20, 0xad, 0xad, 0x16, 0xa4, 0xff,
	0x54, 0xa0, 0x9e, 0x18, 0xf3, 0xc5, 0x46, 0xb4, 0x0d, 0x6b, 0x3e, 0x3d, 0x23, 0x91, 0x50, 0x3e,
	0x36, 0x1d, 0x7d, 0x42, 0xbb, 0xb0, 0x39, 0x4f, 0x43, 0x95, 0xe6, 0x0a, 0x88, 0xb2, 0x02, 0x62,
	0x3e, 0xf3, 0x65, 0x70, 0x15, 0x24, 0xb7, 0xa1, 0x31, 0xe7, 0xaa, 0xa8, 0x28, 0xd5, 0x47, 0x09,
	0x71, 0x1f, 0x6e, 0xa6, 0x18, 0x70, 0xa2, 0x51, 0x49, 0x56, 0x81, 0xaa, 0x62, 0xbe, 0xe1, 0xa7,
	0xc9, 0x11, 0xd3, 0x93, 0xa5, 0xe1, 0x51, 0x0a, 0xe3, 0x90, 0xb1, 0xf1, 0x04, 0xf3, 0xb1, 0x2b,
	0x1d, 0x55, 0x60, 0x34, 0x13, 0xec, 0x9e, 0x6b, 0x92, 0x74, 0x1b, 0xdd, 0x05, 0x90, 0x2f, 0x18,
	0x82, 0xb8, 0x33, 0x1e, 0xa8, 0x57, 0x9f, 0x86, 0xd3, 0x88, 0x6f, 0x4e, 0x79, 0x80, 0x76, 0xa0,
	0xe9, 0xe1, 0xd0, 0xf5, 0xd9, 0x65, 0x18, 0x30, 0xec, 0xab, 0x22, 0x4c, 0x07, 0x9d, 0xe9, 0xe1,
	0xf0, 0x50, 0x53, 0xd0, 0x09, 0x6c, 0x24, 0x5c, 0xee, 0x94, 0x53, 0xc6, 0xa9, 0xb8, 0xd2, 0x55,
	0x78, 0x2f, 0x17, 0xf2, 0xdd, 0x44, 0xa4, 0xaf, 0xb9, 0xe6, 0x35, 0x68, 0xf9, 0x05, 0x12, 0x7a,
	0x02, 0x80, 0x85, 0xe0, 0x74, 0x38, 0x13, 0x24, 0xd2, 0x85, 0xb7, 0x99, 0xaa, 0x3b, 0x48, 0x49,
	0x4e, 0x86, 0x0d, 0xfd, 0x1c, 0xd6, 0x49, 0xe8, 0xf1, 0xab, 0xa9, 0xa0, 0x2c, 0x54, 0xb3, 0xbe,
	0x63, 0x66, 0x24, 0x5f, 0xa6, 0x34, 0x95, 0x81, 0x6d, 0x92, 0x3b, 0xa3, 0x03, 0xb8, 0x3b, 0x4d,
	0xd3, 0xdf, 0x4d, 0x37, 0x23, 0x15, 0x30, 0xb5, 0x08, 0x7a, 0x0a, 0xa4, 0x5b, 0x73, 0xa6, 0x64,
	0x46, 0xcb, 0xf8, 0xca, 0x95, 0xd1, 0xfe, 0x5a, 0x96, 0x6f, 0xc1, 0x93, 0x3a, 0x54, 0x7e, 0x41,
	0xcf, 0xce, 0xad, 0x6b, 0xd9, 0x46, 0x60, 0xd8, 0xff, 0x30, 0x60, 0xfd, 0x30, 0x9f, 0x93, 0xe8,
	0x57, 0x70, 0x3d, 0x9f, 0xcf, 0xc9, 0xda, 0x63, 0xa8, 0x0a, 0xfa, 0x3a, 0xf5, 0x3f, 0x23, 0x54,
	0x3c, 0xc7, 0x8b, 0xd0, 0x66, 0x36, 0xdd, 0xf5, 0x1e, 0x74, 0x4b, 0xc0, 0xd6, 0x32, 0xe6, 0x95,
	0xa7, 0x38, 0x7a, 0x02, 0xad, 0x9c, 0x7d, 0x7a, 0x30, 0x17, 0x6b, 0xad, 0x99, 0x7d, 0xb8, 0x7d,
	0x00, 0xcd, 0xec, 0x53, 0xd1, 0x63, 0x68, 0x8f, 0x70, 0x10, 0x0c, 0xb1, 0x37, 0x76, 0x3d, 0x16,
	0xb0, 0xf8, 0x13, 0x87, 0xd9, 0x03, 0x3d, 0xbd, 0x02, 0xc6, 0x9d, 0x56, 0xc2, 0xa1, 0x8e, 0xf6,
	0x5f, 0x0c, 0x68, 0xe7, 0x83, 0x87, 0x1e, 0x40, 0xdb, 0x27, 0x1e, 0xf3, 0xe5, 0x42, 0x1d, 0x7f,
	0x70, 0x88, 0x3f, 0x94, 0xb4, 0xf4, 0xed, 0xeb, 0xf8, 0xbb, 0xc3, 0x23, 0x98, 0xb7, 0x77, 0x77,
	0x18, 0x30, 0x6f, 0xec, 0x46, 0xf4, 0x23, 0xd1, 0x3b, 0x10, 0x4a, 0x69, 0xcf, 0x25, 0x69, 0x40,
	0x3f, 0x12, 0xf4, 0x1d, 0x98, 0x31, 0x5f, 0xbc, 0x2a, 0xc6, 0xbd, 0xab, 0x53, 0xc8, 0x1f, 0xc5,
	0x1e, 0xcf, 0xd7, 0x61, 0xf2, 0x37, 0xb2, 0x3d, 0xd8, 0x5c, 0xc2, 0x22, 0x4d, 0x25, 0x61, 0xc1,
	0x54, 0x89, 0x6e, 0x4b, 0xdf, 0x6a, 0x53, 0x17, 0x3d, 0x2a, 0x2d, 0xf1, 0xc8, 0xfe, 0xb7, 0x01,
	0x1b, 0xef, 0x28, 0xb9, 0x1c, 0x08, 0x2c, 0xc8, 0x8a, 0x4d, 0xfa, 0x5b, 0x68, 0xea, 0xbf, 0x71,
	0x73, 0xad, 0x14, 0x9b, 0xab, 0xa9, 0xc9, 0xaa, 0xab, 0x3e, 0x82, 0x46, 0xba, 0x34, 0xa8, 0x56,
	0xb6, 0x7c, 0xb3, 0x98, 0x33, 0x21, 0x17, 0xba, 0x69, 0xb9, 0x7c, 0x6a, 0x73, 0xaf, 0x7e, 0x7e,
	0x73, 0xbf, 0x93, 0x28, 0x78, 0xbb, 0x64, 0x83, 0xb7, 0xff, 0x5c, 0x86, 0xdb, 0x31, 0x61, 0x40,
	0x38, 0xc5, 0x01, 0xfd, 0x88, 0x25, 0xc6, 0x2b, 0xba, 0xff, 0xa9, 0x19, 0x53, 0x5a, 0x65, 0xc6,
	0x14, 0xb1, 0x2b, 0xaf, 0x8e, 0x5d, 0x65, 0x15, 0xec, 0xd2, 0x29, 0x59, 0xfd, 0xcc, 0x94, 0x5c,
	0x05, 0xe0, 0xb5, 0x1f, 0x00, 0xf0, 0xf2, 0x49, 0x5a, 0x5b, 0x6d, 0x92, 0xfe, 0xd5, 0x80, 0x3b,
	0x4b, 0x82, 0x93, 0xae, 0x39, 0xe8, 0x00, 0x6a, 0xf9, 0x46, 0xf6, 0x30, 0x63, 0xe4, 0x72, 0x99,
	0xdd, 0xd8, 0xe8, 0x44, 0xee, 0xd6, 0x31, 0x54, 0xe3, 0x5e, 0x95, 0x79, 0x3b, 0x8e, 0x37, 0xfc,
	0xf4, 0xed, 0x78, 0x1b, 0xd6, 0xd8, 0x68, 0x14, 0x91, 0x78, 0x46, 0x57, 0x1c, 0x7d, 0x42, 0x08,
	0x2a, 0xaa, 0xe4, 0xcb, 0xea, 0x56, 0xfd, 0xb7, 0xbf, 0x9f, 0xaf, 0x59, 0x69, 0x0e, 0xfd, 0x04,
	0x3a, 0x34, 0x72, 0x69, 0x28, 0x9b, 0x52, 0x80, 0x87, 0x8c, 0x2b, 0x8b, 0xdc, 0x09, 0xf3, 0x89,
	0xea, 0x2d, 0x75, 0xe7, 0x3a, 0x8d, 0x8e, 0xc2, 0x17, 0x59, 0xea, 0x31, 0xf3, 0x89, 0xfd, 0x27,
	0x03, 0xd6, 0xf5, 0x67, 0x8a, 0x1f, 0xac, 0x0c, 0xbd, 0x86, 0x0e, 0xf6, 0xc6, 0x21, 0xbb, 0x0c,
	0x88, 0x7f, 0x46, 0x7c, 0x57, 0x7d, 0xa3, 0xe0, 0xae, 0xee, 0xb6, 0xf3, 0x2d, 0x3f, 0xff, 0x06,
	0xbd, 0x9d, 0x95, 0x19, 0x28, 0x11, 0xc9, 0xf0, 0xfc, 0xe1, 0x2f, 0x1f, 0x9c, 0x51, 0x71, 0x3e,
	0x1b, 0xee, 0x7a, 0x6c, 0xb2, 0xf7, 0x91, 0x4e, 0x86, 0x78, 0x88, 0xd9, 0x9e, 0xcf, 0x3c, 0x8f,
	0x85, 0x17, 0x7b, 0xf4, 0x3d, 0xe3, 0xe3, 0xbd, 0x93, 0x41, 0xff, 0x7f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xe4, 0xf6, 0x4b, 0x31, 0xb6, 0x16, 0x00, 0x00,
}
