// Code generated by protoc-gen-go. DO NOT EDIT.
// source: TSPMessages.proto

package TSP

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Color_ColorModel int32

const (
	Color_rgb   Color_ColorModel = 1
	Color_cmyk  Color_ColorModel = 2
	Color_white Color_ColorModel = 3
)

var Color_ColorModel_name = map[int32]string{
	1: "rgb",
	2: "cmyk",
	3: "white",
}

var Color_ColorModel_value = map[string]int32{
	"rgb":   1,
	"cmyk":  2,
	"white": 3,
}

func (x Color_ColorModel) Enum() *Color_ColorModel {
	p := new(Color_ColorModel)
	*p = x
	return p
}

func (x Color_ColorModel) String() string {
	return proto.EnumName(Color_ColorModel_name, int32(x))
}

func (x *Color_ColorModel) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Color_ColorModel_value, data, "Color_ColorModel")
	if err != nil {
		return err
	}
	*x = Color_ColorModel(value)
	return nil
}

func (Color_ColorModel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_97e0e7aa6082a9cd, []int{7, 0}
}

type Path_ElementType int32

const (
	Path_moveTo       Path_ElementType = 1
	Path_lineTo       Path_ElementType = 2
	Path_quadCurveTo  Path_ElementType = 3
	Path_curveTo      Path_ElementType = 4
	Path_closeSubpath Path_ElementType = 5
)

var Path_ElementType_name = map[int32]string{
	1: "moveTo",
	2: "lineTo",
	3: "quadCurveTo",
	4: "curveTo",
	5: "closeSubpath",
}

var Path_ElementType_value = map[string]int32{
	"moveTo":       1,
	"lineTo":       2,
	"quadCurveTo":  3,
	"curveTo":      4,
	"closeSubpath": 5,
}

func (x Path_ElementType) Enum() *Path_ElementType {
	p := new(Path_ElementType)
	*p = x
	return p
}

func (x Path_ElementType) String() string {
	return proto.EnumName(Path_ElementType_name, int32(x))
}

func (x *Path_ElementType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Path_ElementType_value, data, "Path_ElementType")
	if err != nil {
		return err
	}
	*x = Path_ElementType(value)
	return nil
}

func (Path_ElementType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_97e0e7aa6082a9cd, []int{8, 0}
}

type Reference struct {
	Identifier           *uint64  `protobuf:"varint,1,req,name=identifier" json:"identifier,omitempty"`
	DeprecatedType       *int32   `protobuf:"varint,2,opt,name=deprecated_type,json=deprecatedType" json:"deprecated_type,omitempty"`
	DeprecatedIsExternal *bool    `protobuf:"varint,3,opt,name=deprecated_is_external,json=deprecatedIsExternal" json:"deprecated_is_external,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reference) Reset()         { *m = Reference{} }
func (m *Reference) String() string { return proto.CompactTextString(m) }
func (*Reference) ProtoMessage()    {}
func (*Reference) Descriptor() ([]byte, []int) {
	return fileDescriptor_97e0e7aa6082a9cd, []int{0}
}

func (m *Reference) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reference.Unmarshal(m, b)
}
func (m *Reference) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reference.Marshal(b, m, deterministic)
}
func (m *Reference) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reference.Merge(m, src)
}
func (m *Reference) XXX_Size() int {
	return xxx_messageInfo_Reference.Size(m)
}
func (m *Reference) XXX_DiscardUnknown() {
	xxx_messageInfo_Reference.DiscardUnknown(m)
}

var xxx_messageInfo_Reference proto.InternalMessageInfo

func (m *Reference) GetIdentifier() uint64 {
	if m != nil && m.Identifier != nil {
		return *m.Identifier
	}
	return 0
}

func (m *Reference) GetDeprecatedType() int32 {
	if m != nil && m.DeprecatedType != nil {
		return *m.DeprecatedType
	}
	return 0
}

func (m *Reference) GetDeprecatedIsExternal() bool {
	if m != nil && m.DeprecatedIsExternal != nil {
		return *m.DeprecatedIsExternal
	}
	return false
}

type DataReference struct {
	Identifier           *uint64  `protobuf:"varint,1,req,name=identifier" json:"identifier,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataReference) Reset()         { *m = DataReference{} }
func (m *DataReference) String() string { return proto.CompactTextString(m) }
func (*DataReference) ProtoMessage()    {}
func (*DataReference) Descriptor() ([]byte, []int) {
	return fileDescriptor_97e0e7aa6082a9cd, []int{1}
}

func (m *DataReference) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataReference.Unmarshal(m, b)
}
func (m *DataReference) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataReference.Marshal(b, m, deterministic)
}
func (m *DataReference) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataReference.Merge(m, src)
}
func (m *DataReference) XXX_Size() int {
	return xxx_messageInfo_DataReference.Size(m)
}
func (m *DataReference) XXX_DiscardUnknown() {
	xxx_messageInfo_DataReference.DiscardUnknown(m)
}

var xxx_messageInfo_DataReference proto.InternalMessageInfo

func (m *DataReference) GetIdentifier() uint64 {
	if m != nil && m.Identifier != nil {
		return *m.Identifier
	}
	return 0
}

type Point struct {
	X                    *float32 `protobuf:"fixed32,1,req,name=x" json:"x,omitempty"`
	Y                    *float32 `protobuf:"fixed32,2,req,name=y" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Point) Reset()         { *m = Point{} }
func (m *Point) String() string { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()    {}
func (*Point) Descriptor() ([]byte, []int) {
	return fileDescriptor_97e0e7aa6082a9cd, []int{2}
}

func (m *Point) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Point.Unmarshal(m, b)
}
func (m *Point) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Point.Marshal(b, m, deterministic)
}
func (m *Point) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Point.Merge(m, src)
}
func (m *Point) XXX_Size() int {
	return xxx_messageInfo_Point.Size(m)
}
func (m *Point) XXX_DiscardUnknown() {
	xxx_messageInfo_Point.DiscardUnknown(m)
}

var xxx_messageInfo_Point proto.InternalMessageInfo

func (m *Point) GetX() float32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *Point) GetY() float32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

type Size struct {
	Width                *float32 `protobuf:"fixed32,1,req,name=width" json:"width,omitempty"`
	Height               *float32 `protobuf:"fixed32,2,req,name=height" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Size) Reset()         { *m = Size{} }
func (m *Size) String() string { return proto.CompactTextString(m) }
func (*Size) ProtoMessage()    {}
func (*Size) Descriptor() ([]byte, []int) {
	return fileDescriptor_97e0e7aa6082a9cd, []int{3}
}

func (m *Size) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Size.Unmarshal(m, b)
}
func (m *Size) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Size.Marshal(b, m, deterministic)
}
func (m *Size) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Size.Merge(m, src)
}
func (m *Size) XXX_Size() int {
	return xxx_messageInfo_Size.Size(m)
}
func (m *Size) XXX_DiscardUnknown() {
	xxx_messageInfo_Size.DiscardUnknown(m)
}

var xxx_messageInfo_Size proto.InternalMessageInfo

func (m *Size) GetWidth() float32 {
	if m != nil && m.Width != nil {
		return *m.Width
	}
	return 0
}

func (m *Size) GetHeight() float32 {
	if m != nil && m.Height != nil {
		return *m.Height
	}
	return 0
}

type Range struct {
	Location             *uint32  `protobuf:"varint,1,req,name=location" json:"location,omitempty"`
	Length               *uint32  `protobuf:"varint,2,req,name=length" json:"length,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Range) Reset()         { *m = Range{} }
func (m *Range) String() string { return proto.CompactTextString(m) }
func (*Range) ProtoMessage()    {}
func (*Range) Descriptor() ([]byte, []int) {
	return fileDescriptor_97e0e7aa6082a9cd, []int{4}
}

func (m *Range) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Range.Unmarshal(m, b)
}
func (m *Range) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Range.Marshal(b, m, deterministic)
}
func (m *Range) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Range.Merge(m, src)
}
func (m *Range) XXX_Size() int {
	return xxx_messageInfo_Range.Size(m)
}
func (m *Range) XXX_DiscardUnknown() {
	xxx_messageInfo_Range.DiscardUnknown(m)
}

var xxx_messageInfo_Range proto.InternalMessageInfo

func (m *Range) GetLocation() uint32 {
	if m != nil && m.Location != nil {
		return *m.Location
	}
	return 0
}

func (m *Range) GetLength() uint32 {
	if m != nil && m.Length != nil {
		return *m.Length
	}
	return 0
}

type Date struct {
	Seconds              *float64 `protobuf:"fixed64,1,req,name=seconds" json:"seconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Date) Reset()         { *m = Date{} }
func (m *Date) String() string { return proto.CompactTextString(m) }
func (*Date) ProtoMessage()    {}
func (*Date) Descriptor() ([]byte, []int) {
	return fileDescriptor_97e0e7aa6082a9cd, []int{5}
}

func (m *Date) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Date.Unmarshal(m, b)
}
func (m *Date) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Date.Marshal(b, m, deterministic)
}
func (m *Date) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Date.Merge(m, src)
}
func (m *Date) XXX_Size() int {
	return xxx_messageInfo_Date.Size(m)
}
func (m *Date) XXX_DiscardUnknown() {
	xxx_messageInfo_Date.DiscardUnknown(m)
}

var xxx_messageInfo_Date proto.InternalMessageInfo

func (m *Date) GetSeconds() float64 {
	if m != nil && m.Seconds != nil {
		return *m.Seconds
	}
	return 0
}

type IndexSet struct {
	Ranges               []*Range `protobuf:"bytes,1,rep,name=ranges" json:"ranges,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IndexSet) Reset()         { *m = IndexSet{} }
func (m *IndexSet) String() string { return proto.CompactTextString(m) }
func (*IndexSet) ProtoMessage()    {}
func (*IndexSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_97e0e7aa6082a9cd, []int{6}
}

func (m *IndexSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexSet.Unmarshal(m, b)
}
func (m *IndexSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexSet.Marshal(b, m, deterministic)
}
func (m *IndexSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexSet.Merge(m, src)
}
func (m *IndexSet) XXX_Size() int {
	return xxx_messageInfo_IndexSet.Size(m)
}
func (m *IndexSet) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexSet.DiscardUnknown(m)
}

var xxx_messageInfo_IndexSet proto.InternalMessageInfo

func (m *IndexSet) GetRanges() []*Range {
	if m != nil {
		return m.Ranges
	}
	return nil
}

type Color struct {
	Model                *Color_ColorModel `protobuf:"varint,1,req,name=model,enum=TSP.Color_ColorModel" json:"model,omitempty"`
	R                    *float32          `protobuf:"fixed32,3,opt,name=r" json:"r,omitempty"`
	G                    *float32          `protobuf:"fixed32,4,opt,name=g" json:"g,omitempty"`
	B                    *float32          `protobuf:"fixed32,5,opt,name=b" json:"b,omitempty"`
	A                    *float32          `protobuf:"fixed32,6,opt,name=a,def=1" json:"a,omitempty"`
	C                    *float32          `protobuf:"fixed32,7,opt,name=c" json:"c,omitempty"`
	M                    *float32          `protobuf:"fixed32,8,opt,name=m" json:"m,omitempty"`
	Y                    *float32          `protobuf:"fixed32,9,opt,name=y" json:"y,omitempty"`
	K                    *float32          `protobuf:"fixed32,10,opt,name=k" json:"k,omitempty"`
	W                    *float32          `protobuf:"fixed32,11,opt,name=w" json:"w,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Color) Reset()         { *m = Color{} }
func (m *Color) String() string { return proto.CompactTextString(m) }
func (*Color) ProtoMessage()    {}
func (*Color) Descriptor() ([]byte, []int) {
	return fileDescriptor_97e0e7aa6082a9cd, []int{7}
}

func (m *Color) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Color.Unmarshal(m, b)
}
func (m *Color) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Color.Marshal(b, m, deterministic)
}
func (m *Color) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Color.Merge(m, src)
}
func (m *Color) XXX_Size() int {
	return xxx_messageInfo_Color.Size(m)
}
func (m *Color) XXX_DiscardUnknown() {
	xxx_messageInfo_Color.DiscardUnknown(m)
}

var xxx_messageInfo_Color proto.InternalMessageInfo

const Default_Color_A float32 = 1

func (m *Color) GetModel() Color_ColorModel {
	if m != nil && m.Model != nil {
		return *m.Model
	}
	return Color_rgb
}

func (m *Color) GetR() float32 {
	if m != nil && m.R != nil {
		return *m.R
	}
	return 0
}

func (m *Color) GetG() float32 {
	if m != nil && m.G != nil {
		return *m.G
	}
	return 0
}

func (m *Color) GetB() float32 {
	if m != nil && m.B != nil {
		return *m.B
	}
	return 0
}

func (m *Color) GetA() float32 {
	if m != nil && m.A != nil {
		return *m.A
	}
	return Default_Color_A
}

func (m *Color) GetC() float32 {
	if m != nil && m.C != nil {
		return *m.C
	}
	return 0
}

func (m *Color) GetM() float32 {
	if m != nil && m.M != nil {
		return *m.M
	}
	return 0
}

func (m *Color) GetY() float32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func (m *Color) GetK() float32 {
	if m != nil && m.K != nil {
		return *m.K
	}
	return 0
}

func (m *Color) GetW() float32 {
	if m != nil && m.W != nil {
		return *m.W
	}
	return 0
}

type Path struct {
	Elements             []*Path_Element `protobuf:"bytes,1,rep,name=elements" json:"elements,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Path) Reset()         { *m = Path{} }
func (m *Path) String() string { return proto.CompactTextString(m) }
func (*Path) ProtoMessage()    {}
func (*Path) Descriptor() ([]byte, []int) {
	return fileDescriptor_97e0e7aa6082a9cd, []int{8}
}

func (m *Path) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Path.Unmarshal(m, b)
}
func (m *Path) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Path.Marshal(b, m, deterministic)
}
func (m *Path) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Path.Merge(m, src)
}
func (m *Path) XXX_Size() int {
	return xxx_messageInfo_Path.Size(m)
}
func (m *Path) XXX_DiscardUnknown() {
	xxx_messageInfo_Path.DiscardUnknown(m)
}

var xxx_messageInfo_Path proto.InternalMessageInfo

func (m *Path) GetElements() []*Path_Element {
	if m != nil {
		return m.Elements
	}
	return nil
}

type Path_Element struct {
	Type                 *Path_ElementType `protobuf:"varint,1,req,name=type,enum=TSP.Path_ElementType" json:"type,omitempty"`
	Points               []*Point          `protobuf:"bytes,2,rep,name=points" json:"points,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Path_Element) Reset()         { *m = Path_Element{} }
func (m *Path_Element) String() string { return proto.CompactTextString(m) }
func (*Path_Element) ProtoMessage()    {}
func (*Path_Element) Descriptor() ([]byte, []int) {
	return fileDescriptor_97e0e7aa6082a9cd, []int{8, 0}
}

func (m *Path_Element) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Path_Element.Unmarshal(m, b)
}
func (m *Path_Element) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Path_Element.Marshal(b, m, deterministic)
}
func (m *Path_Element) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Path_Element.Merge(m, src)
}
func (m *Path_Element) XXX_Size() int {
	return xxx_messageInfo_Path_Element.Size(m)
}
func (m *Path_Element) XXX_DiscardUnknown() {
	xxx_messageInfo_Path_Element.DiscardUnknown(m)
}

var xxx_messageInfo_Path_Element proto.InternalMessageInfo

func (m *Path_Element) GetType() Path_ElementType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Path_moveTo
}

func (m *Path_Element) GetPoints() []*Point {
	if m != nil {
		return m.Points
	}
	return nil
}

type ReferenceDictionary struct {
	Entries              []*ReferenceDictionary_Entry `protobuf:"bytes,1,rep,name=entries" json:"entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *ReferenceDictionary) Reset()         { *m = ReferenceDictionary{} }
func (m *ReferenceDictionary) String() string { return proto.CompactTextString(m) }
func (*ReferenceDictionary) ProtoMessage()    {}
func (*ReferenceDictionary) Descriptor() ([]byte, []int) {
	return fileDescriptor_97e0e7aa6082a9cd, []int{9}
}

func (m *ReferenceDictionary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReferenceDictionary.Unmarshal(m, b)
}
func (m *ReferenceDictionary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReferenceDictionary.Marshal(b, m, deterministic)
}
func (m *ReferenceDictionary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReferenceDictionary.Merge(m, src)
}
func (m *ReferenceDictionary) XXX_Size() int {
	return xxx_messageInfo_ReferenceDictionary.Size(m)
}
func (m *ReferenceDictionary) XXX_DiscardUnknown() {
	xxx_messageInfo_ReferenceDictionary.DiscardUnknown(m)
}

var xxx_messageInfo_ReferenceDictionary proto.InternalMessageInfo

func (m *ReferenceDictionary) GetEntries() []*ReferenceDictionary_Entry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type ReferenceDictionary_Entry struct {
	Key                  *Reference `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Value                *Reference `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ReferenceDictionary_Entry) Reset()         { *m = ReferenceDictionary_Entry{} }
func (m *ReferenceDictionary_Entry) String() string { return proto.CompactTextString(m) }
func (*ReferenceDictionary_Entry) ProtoMessage()    {}
func (*ReferenceDictionary_Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_97e0e7aa6082a9cd, []int{9, 0}
}

func (m *ReferenceDictionary_Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReferenceDictionary_Entry.Unmarshal(m, b)
}
func (m *ReferenceDictionary_Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReferenceDictionary_Entry.Marshal(b, m, deterministic)
}
func (m *ReferenceDictionary_Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReferenceDictionary_Entry.Merge(m, src)
}
func (m *ReferenceDictionary_Entry) XXX_Size() int {
	return xxx_messageInfo_ReferenceDictionary_Entry.Size(m)
}
func (m *ReferenceDictionary_Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_ReferenceDictionary_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_ReferenceDictionary_Entry proto.InternalMessageInfo

func (m *ReferenceDictionary_Entry) GetKey() *Reference {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *ReferenceDictionary_Entry) GetValue() *Reference {
	if m != nil {
		return m.Value
	}
	return nil
}

type PasteboardObject struct {
	Stylesheet           *Reference   `protobuf:"bytes,1,opt,name=stylesheet" json:"stylesheet,omitempty"`
	Drawables            []*Reference `protobuf:"bytes,2,rep,name=drawables" json:"drawables,omitempty"`
	Styles               []*Reference `protobuf:"bytes,3,rep,name=styles" json:"styles,omitempty"`
	Theme                *Reference   `protobuf:"bytes,4,opt,name=theme" json:"theme,omitempty"`
	WpStorage            *Reference   `protobuf:"bytes,5,opt,name=wp_storage,json=wpStorage" json:"wp_storage,omitempty"`
	GuideStorage         *Reference   `protobuf:"bytes,9,opt,name=guide_storage,json=guideStorage" json:"guide_storage,omitempty"`
	AppNativeObject      *Reference   `protobuf:"bytes,6,opt,name=app_native_object,json=appNativeObject" json:"app_native_object,omitempty"`
	IsTextPrimary        *bool        `protobuf:"varint,7,opt,name=is_text_primary,json=isTextPrimary,def=0" json:"is_text_primary,omitempty"`
	IsSmart              *bool        `protobuf:"varint,8,opt,name=is_smart,json=isSmart,def=0" json:"is_smart,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PasteboardObject) Reset()         { *m = PasteboardObject{} }
func (m *PasteboardObject) String() string { return proto.CompactTextString(m) }
func (*PasteboardObject) ProtoMessage()    {}
func (*PasteboardObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_97e0e7aa6082a9cd, []int{10}
}

func (m *PasteboardObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PasteboardObject.Unmarshal(m, b)
}
func (m *PasteboardObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PasteboardObject.Marshal(b, m, deterministic)
}
func (m *PasteboardObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PasteboardObject.Merge(m, src)
}
func (m *PasteboardObject) XXX_Size() int {
	return xxx_messageInfo_PasteboardObject.Size(m)
}
func (m *PasteboardObject) XXX_DiscardUnknown() {
	xxx_messageInfo_PasteboardObject.DiscardUnknown(m)
}

var xxx_messageInfo_PasteboardObject proto.InternalMessageInfo

const Default_PasteboardObject_IsTextPrimary bool = false
const Default_PasteboardObject_IsSmart bool = false

func (m *PasteboardObject) GetStylesheet() *Reference {
	if m != nil {
		return m.Stylesheet
	}
	return nil
}

func (m *PasteboardObject) GetDrawables() []*Reference {
	if m != nil {
		return m.Drawables
	}
	return nil
}

func (m *PasteboardObject) GetStyles() []*Reference {
	if m != nil {
		return m.Styles
	}
	return nil
}

func (m *PasteboardObject) GetTheme() *Reference {
	if m != nil {
		return m.Theme
	}
	return nil
}

func (m *PasteboardObject) GetWpStorage() *Reference {
	if m != nil {
		return m.WpStorage
	}
	return nil
}

func (m *PasteboardObject) GetGuideStorage() *Reference {
	if m != nil {
		return m.GuideStorage
	}
	return nil
}

func (m *PasteboardObject) GetAppNativeObject() *Reference {
	if m != nil {
		return m.AppNativeObject
	}
	return nil
}

func (m *PasteboardObject) GetIsTextPrimary() bool {
	if m != nil && m.IsTextPrimary != nil {
		return *m.IsTextPrimary
	}
	return Default_PasteboardObject_IsTextPrimary
}

func (m *PasteboardObject) GetIsSmart() bool {
	if m != nil && m.IsSmart != nil {
		return *m.IsSmart
	}
	return Default_PasteboardObject_IsSmart
}

type ObjectContainer struct {
	Identifier           *uint32      `protobuf:"varint,1,opt,name=identifier" json:"identifier,omitempty"`
	Objects              []*Reference `protobuf:"bytes,2,rep,name=objects" json:"objects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ObjectContainer) Reset()         { *m = ObjectContainer{} }
func (m *ObjectContainer) String() string { return proto.CompactTextString(m) }
func (*ObjectContainer) ProtoMessage()    {}
func (*ObjectContainer) Descriptor() ([]byte, []int) {
	return fileDescriptor_97e0e7aa6082a9cd, []int{11}
}

func (m *ObjectContainer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectContainer.Unmarshal(m, b)
}
func (m *ObjectContainer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectContainer.Marshal(b, m, deterministic)
}
func (m *ObjectContainer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectContainer.Merge(m, src)
}
func (m *ObjectContainer) XXX_Size() int {
	return xxx_messageInfo_ObjectContainer.Size(m)
}
func (m *ObjectContainer) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectContainer.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectContainer proto.InternalMessageInfo

func (m *ObjectContainer) GetIdentifier() uint32 {
	if m != nil && m.Identifier != nil {
		return *m.Identifier
	}
	return 0
}

func (m *ObjectContainer) GetObjects() []*Reference {
	if m != nil {
		return m.Objects
	}
	return nil
}

func init() {
	proto.RegisterEnum("TSP.Color_ColorModel", Color_ColorModel_name, Color_ColorModel_value)
	proto.RegisterEnum("TSP.Path_ElementType", Path_ElementType_name, Path_ElementType_value)
	proto.RegisterType((*Reference)(nil), "TSP.Reference")
	proto.RegisterType((*DataReference)(nil), "TSP.DataReference")
	proto.RegisterType((*Point)(nil), "TSP.Point")
	proto.RegisterType((*Size)(nil), "TSP.Size")
	proto.RegisterType((*Range)(nil), "TSP.Range")
	proto.RegisterType((*Date)(nil), "TSP.Date")
	proto.RegisterType((*IndexSet)(nil), "TSP.IndexSet")
	proto.RegisterType((*Color)(nil), "TSP.Color")
	proto.RegisterType((*Path)(nil), "TSP.Path")
	proto.RegisterType((*Path_Element)(nil), "TSP.Path.Element")
	proto.RegisterType((*ReferenceDictionary)(nil), "TSP.ReferenceDictionary")
	proto.RegisterType((*ReferenceDictionary_Entry)(nil), "TSP.ReferenceDictionary.Entry")
	proto.RegisterType((*PasteboardObject)(nil), "TSP.PasteboardObject")
	proto.RegisterType((*ObjectContainer)(nil), "TSP.ObjectContainer")
}

func init() { proto.RegisterFile("TSPMessages.proto", fileDescriptor_97e0e7aa6082a9cd) }

var fileDescriptor_97e0e7aa6082a9cd = []byte{
	// 851 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xdd, 0x6e, 0xe2, 0x46,
	0x18, 0x95, 0x01, 0x07, 0xf8, 0x08, 0x81, 0x4c, 0xb7, 0x2b, 0x2b, 0x17, 0x2b, 0xe4, 0xfe, 0x2c,
	0xfd, 0x09, 0xa8, 0xe9, 0x5e, 0x54, 0xe9, 0x5d, 0x93, 0x5c, 0xec, 0xc5, 0x76, 0x91, 0xa1, 0x6a,
	0xd5, 0x5e, 0xa0, 0xb1, 0xfd, 0xc5, 0x9e, 0x62, 0x7b, 0xdc, 0x99, 0x21, 0xe0, 0x7d, 0x84, 0x3e,
	0x45, 0xdf, 0xa0, 0xcf, 0xd4, 0x9b, 0x3e, 0x47, 0x35, 0x33, 0x86, 0xb0, 0x0d, 0x95, 0x7a, 0x83,
	0x7c, 0xbe, 0x73, 0x8e, 0x67, 0xe6, 0x70, 0xc6, 0x70, 0xbe, 0x98, 0xcf, 0xde, 0xa0, 0x94, 0x34,
	0x41, 0x39, 0x29, 0x05, 0x57, 0x9c, 0x34, 0x17, 0xf3, 0x99, 0xff, 0xbb, 0x03, 0xdd, 0x00, 0xef,
	0x51, 0x60, 0x11, 0x21, 0x79, 0x01, 0xc0, 0x62, 0x2c, 0x14, 0xbb, 0x67, 0x28, 0x3c, 0x67, 0xd4,
	0x18, 0xb7, 0x82, 0x83, 0x09, 0x79, 0x09, 0x83, 0x18, 0x4b, 0x81, 0x11, 0x55, 0x18, 0x2f, 0x55,
	0x55, 0xa2, 0xd7, 0x18, 0x39, 0x63, 0x37, 0x38, 0x7b, 0x1c, 0x2f, 0xaa, 0x12, 0xc9, 0x2b, 0x78,
	0x7e, 0x20, 0x64, 0x72, 0x89, 0x5b, 0x85, 0xa2, 0xa0, 0x99, 0xd7, 0x1c, 0x39, 0xe3, 0x4e, 0xf0,
	0xec, 0x91, 0x7d, 0x2d, 0xef, 0x6a, 0xce, 0x9f, 0x42, 0xff, 0x96, 0x2a, 0xfa, 0xbf, 0xf7, 0xe3,
	0x7f, 0x04, 0xee, 0x8c, 0xb3, 0x42, 0x91, 0x53, 0x70, 0xb6, 0x86, 0x6f, 0x04, 0xce, 0x56, 0xa3,
	0xca, 0x6b, 0x58, 0x54, 0xf9, 0xaf, 0xa0, 0x35, 0x67, 0xef, 0x90, 0x3c, 0x03, 0x77, 0xc3, 0x62,
	0x95, 0xd6, 0x3a, 0x0b, 0xc8, 0x73, 0x38, 0x49, 0x91, 0x25, 0xa9, 0xaa, 0x0d, 0x35, 0xf2, 0xbf,
	0x05, 0x37, 0xa0, 0x45, 0x82, 0xe4, 0x02, 0x3a, 0x19, 0x8f, 0xa8, 0x62, 0xbc, 0x30, 0xce, 0x7e,
	0xb0, 0xc7, 0xda, 0x9c, 0x61, 0x91, 0xa8, 0xd4, 0x98, 0xfb, 0x41, 0x8d, 0xfc, 0x11, 0xb4, 0x6e,
	0xa9, 0x42, 0xe2, 0x41, 0x5b, 0x62, 0xc4, 0x8b, 0x58, 0x1a, 0xab, 0x13, 0xec, 0xa0, 0x3f, 0x81,
	0xce, 0xeb, 0x22, 0xc6, 0xed, 0x1c, 0x15, 0xf1, 0xe1, 0x44, 0xe8, 0xa5, 0xb4, 0xa8, 0x39, 0xee,
	0x5d, 0xc1, 0x64, 0x31, 0x9f, 0x4d, 0xcc, 0xea, 0x41, 0xcd, 0xf8, 0x7f, 0x39, 0xe0, 0xde, 0xf0,
	0x8c, 0x0b, 0xf2, 0x05, 0xb8, 0x39, 0x8f, 0x31, 0x33, 0x6f, 0x3c, 0xbb, 0xfa, 0xd0, 0x88, 0x0d,
	0x65, 0x7f, 0xdf, 0x68, 0x32, 0xb0, 0x1a, 0x9d, 0x84, 0x30, 0x91, 0x37, 0x02, 0x47, 0x68, 0x94,
	0x78, 0x2d, 0x8b, 0x12, 0x8d, 0x42, 0xcf, 0xb5, 0x28, 0x24, 0x03, 0x70, 0xa8, 0x77, 0xa2, 0xd1,
	0xb5, 0xf3, 0x55, 0xe0, 0x50, 0x4d, 0x47, 0x5e, 0xdb, 0xd2, 0x91, 0x46, 0xb9, 0xd7, 0xb1, 0x28,
	0xb7, 0x01, 0x77, 0x2d, 0xaa, 0x34, 0x5a, 0x79, 0x60, 0xd1, 0x4a, 0xa3, 0x8d, 0xd7, 0xb3, 0x68,
	0xe3, 0x7f, 0x0e, 0xf0, 0xb8, 0x2b, 0xd2, 0x86, 0xa6, 0x48, 0xc2, 0xa1, 0x43, 0x3a, 0xd0, 0x8a,
	0xf2, 0x6a, 0x35, 0x6c, 0x90, 0x2e, 0xb8, 0x9b, 0x94, 0x29, 0x1c, 0x36, 0xfd, 0xbf, 0x1d, 0x68,
	0xcd, 0xa8, 0x4a, 0xc9, 0x25, 0x74, 0x30, 0xc3, 0x1c, 0x0b, 0xb5, 0x8b, 0xe4, 0xdc, 0x9c, 0x52,
	0x93, 0x93, 0x3b, 0xcb, 0x04, 0x7b, 0xc9, 0xc5, 0x4f, 0xd0, 0xae, 0x87, 0xe4, 0x33, 0x68, 0x99,
	0x56, 0x1e, 0x66, 0x73, 0xe8, 0xd2, 0xe5, 0x0c, 0x8c, 0x44, 0xa7, 0x5e, 0xea, 0xee, 0x48, 0xaf,
	0x71, 0x90, 0xba, 0xa9, 0x53, 0x50, 0x33, 0xfe, 0x0f, 0xd0, 0x3b, 0x30, 0x12, 0x80, 0x93, 0x9c,
	0x3f, 0xe0, 0x82, 0x0f, 0x1d, 0xfd, 0x9c, 0xb1, 0x42, 0x3f, 0x37, 0xc8, 0x00, 0x7a, 0xbf, 0xad,
	0x69, 0x7c, 0xb3, 0x16, 0x86, 0x6c, 0x92, 0x1e, 0xb4, 0xa3, 0x1a, 0xb4, 0xc8, 0x10, 0x4e, 0xa3,
	0x8c, 0x4b, 0x9c, 0xaf, 0xc3, 0x92, 0xaa, 0x74, 0xe8, 0xfa, 0x7f, 0x38, 0xf0, 0xc1, 0xbe, 0xe4,
	0xb7, 0x2c, 0xd2, 0x5d, 0xa2, 0xa2, 0x22, 0xdf, 0x40, 0x1b, 0x0b, 0x25, 0xd8, 0xbe, 0x09, 0x2f,
	0x6c, 0x13, 0x9e, 0x4a, 0x27, 0x77, 0x85, 0x12, 0x55, 0xb0, 0x93, 0x5f, 0xbc, 0x05, 0xd7, 0x4c,
	0xc8, 0x08, 0x9a, 0x2b, 0xac, 0xcc, 0xf9, 0x7b, 0x57, 0x67, 0xef, 0xdb, 0x03, 0x4d, 0x91, 0x8f,
	0xc1, 0x7d, 0xa0, 0xd9, 0x1a, 0x4d, 0x65, 0x9f, 0x6a, 0x2c, 0xe9, 0xff, 0xd9, 0x84, 0xe1, 0x8c,
	0x4a, 0x85, 0x21, 0xa7, 0x22, 0x7e, 0x1b, 0xfe, 0x8a, 0x91, 0x22, 0x13, 0x00, 0xa9, 0xaa, 0x0c,
	0x65, 0x8a, 0xa8, 0x3c, 0x67, 0xe4, 0x1c, 0xf1, 0x1f, 0x28, 0xc8, 0x97, 0xd0, 0x8d, 0x05, 0xdd,
	0xd0, 0x30, 0xc3, 0x5d, 0xca, 0xff, 0x96, 0x3f, 0x0a, 0xc8, 0xa7, 0x70, 0x62, 0xbd, 0x5e, 0xf3,
	0xa8, 0xb4, 0x66, 0xf5, 0x01, 0x54, 0x8a, 0x39, 0x9a, 0x26, 0x1f, 0x39, 0x80, 0x21, 0xc9, 0x25,
	0xc0, 0xa6, 0x5c, 0x4a, 0xc5, 0x05, 0x4d, 0xd0, 0xd4, 0xfc, 0xc8, 0xe2, 0x9b, 0x72, 0x6e, 0x05,
	0xe4, 0x6b, 0xe8, 0x27, 0x6b, 0x16, 0xe3, 0xde, 0xd1, 0x3d, 0xea, 0x38, 0x35, 0xa2, 0x9d, 0xe9,
	0x1a, 0xce, 0x69, 0x59, 0x2e, 0x0b, 0xaa, 0xd8, 0x03, 0x2e, 0xb9, 0x09, 0xc9, 0xdc, 0xa1, 0xa7,
	0xc6, 0x01, 0x2d, 0xcb, 0xef, 0x8d, 0xae, 0xce, 0xf2, 0x12, 0x06, 0x4c, 0x2e, 0x15, 0x6e, 0xd5,
	0xb2, 0x14, 0x2c, 0xa7, 0xa2, 0x32, 0x97, 0xad, 0x73, 0xed, 0xde, 0xd3, 0x4c, 0x62, 0xd0, 0x67,
	0x72, 0x81, 0x5b, 0x35, 0xb3, 0x1c, 0x19, 0x41, 0x87, 0xc9, 0xa5, 0xcc, 0xa9, 0x50, 0xe6, 0x1a,
	0xee, 0x75, 0x6d, 0x26, 0xe7, 0x7a, 0xea, 0xff, 0x02, 0x03, 0xfb, 0xea, 0x1b, 0x5e, 0x28, 0xca,
	0x0a, 0x14, 0x4f, 0x3e, 0x9f, 0xce, 0xb8, 0xff, 0xde, 0xe7, 0x7c, 0x0c, 0x6d, 0xbb, 0xe9, 0xff,
	0xfa, 0x77, 0x76, 0xf4, 0x77, 0x2f, 0x7f, 0xfe, 0x24, 0x61, 0x2a, 0x5d, 0x87, 0x93, 0x88, 0xe7,
	0xd3, 0x77, 0x2c, 0x0f, 0x69, 0x48, 0xf9, 0x34, 0xe6, 0x51, 0xc4, 0x8b, 0x87, 0x29, 0xfb, 0x91,
	0x8b, 0xd5, 0x74, 0x31, 0x9f, 0xfd, 0x13, 0x00, 0x00, 0xff, 0xff, 0x08, 0x71, 0xe7, 0xda, 0x68,
	0x06, 0x00, 0x00,
}
