// Code generated by protoc-gen-go. DO NOT EDIT.
// source: TSDArchives_sos.proto

package TSD

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	TSS "github.com/zimbabao/docconv/iWork/TSS"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SpecSetFillArchive struct {
	Fill                 *FillArchive `protobuf:"bytes,1,opt,name=fill" json:"fill,omitempty"`
	Unset                *bool        `protobuf:"varint,2,req,name=unset" json:"unset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SpecSetFillArchive) Reset()         { *m = SpecSetFillArchive{} }
func (m *SpecSetFillArchive) String() string { return proto.CompactTextString(m) }
func (*SpecSetFillArchive) ProtoMessage()    {}
func (*SpecSetFillArchive) Descriptor() ([]byte, []int) {
	return fileDescriptor_78ce555c1fe59eaa, []int{0}
}

func (m *SpecSetFillArchive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpecSetFillArchive.Unmarshal(m, b)
}
func (m *SpecSetFillArchive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpecSetFillArchive.Marshal(b, m, deterministic)
}
func (m *SpecSetFillArchive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpecSetFillArchive.Merge(m, src)
}
func (m *SpecSetFillArchive) XXX_Size() int {
	return xxx_messageInfo_SpecSetFillArchive.Size(m)
}
func (m *SpecSetFillArchive) XXX_DiscardUnknown() {
	xxx_messageInfo_SpecSetFillArchive.DiscardUnknown(m)
}

var xxx_messageInfo_SpecSetFillArchive proto.InternalMessageInfo

func (m *SpecSetFillArchive) GetFill() *FillArchive {
	if m != nil {
		return m.Fill
	}
	return nil
}

func (m *SpecSetFillArchive) GetUnset() bool {
	if m != nil && m.Unset != nil {
		return *m.Unset
	}
	return false
}

type SpecSetLineEndArchive struct {
	LineEnd              *LineEndArchive `protobuf:"bytes,1,opt,name=line_end,json=lineEnd" json:"line_end,omitempty"`
	Unset                *bool           `protobuf:"varint,2,req,name=unset" json:"unset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SpecSetLineEndArchive) Reset()         { *m = SpecSetLineEndArchive{} }
func (m *SpecSetLineEndArchive) String() string { return proto.CompactTextString(m) }
func (*SpecSetLineEndArchive) ProtoMessage()    {}
func (*SpecSetLineEndArchive) Descriptor() ([]byte, []int) {
	return fileDescriptor_78ce555c1fe59eaa, []int{1}
}

func (m *SpecSetLineEndArchive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpecSetLineEndArchive.Unmarshal(m, b)
}
func (m *SpecSetLineEndArchive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpecSetLineEndArchive.Marshal(b, m, deterministic)
}
func (m *SpecSetLineEndArchive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpecSetLineEndArchive.Merge(m, src)
}
func (m *SpecSetLineEndArchive) XXX_Size() int {
	return xxx_messageInfo_SpecSetLineEndArchive.Size(m)
}
func (m *SpecSetLineEndArchive) XXX_DiscardUnknown() {
	xxx_messageInfo_SpecSetLineEndArchive.DiscardUnknown(m)
}

var xxx_messageInfo_SpecSetLineEndArchive proto.InternalMessageInfo

func (m *SpecSetLineEndArchive) GetLineEnd() *LineEndArchive {
	if m != nil {
		return m.LineEnd
	}
	return nil
}

func (m *SpecSetLineEndArchive) GetUnset() bool {
	if m != nil && m.Unset != nil {
		return *m.Unset
	}
	return false
}

type SpecSetReflectionArchive struct {
	Reflection           *ReflectionArchive `protobuf:"bytes,1,opt,name=reflection" json:"reflection,omitempty"`
	Unset                *bool              `protobuf:"varint,2,req,name=unset" json:"unset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SpecSetReflectionArchive) Reset()         { *m = SpecSetReflectionArchive{} }
func (m *SpecSetReflectionArchive) String() string { return proto.CompactTextString(m) }
func (*SpecSetReflectionArchive) ProtoMessage()    {}
func (*SpecSetReflectionArchive) Descriptor() ([]byte, []int) {
	return fileDescriptor_78ce555c1fe59eaa, []int{2}
}

func (m *SpecSetReflectionArchive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpecSetReflectionArchive.Unmarshal(m, b)
}
func (m *SpecSetReflectionArchive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpecSetReflectionArchive.Marshal(b, m, deterministic)
}
func (m *SpecSetReflectionArchive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpecSetReflectionArchive.Merge(m, src)
}
func (m *SpecSetReflectionArchive) XXX_Size() int {
	return xxx_messageInfo_SpecSetReflectionArchive.Size(m)
}
func (m *SpecSetReflectionArchive) XXX_DiscardUnknown() {
	xxx_messageInfo_SpecSetReflectionArchive.DiscardUnknown(m)
}

var xxx_messageInfo_SpecSetReflectionArchive proto.InternalMessageInfo

func (m *SpecSetReflectionArchive) GetReflection() *ReflectionArchive {
	if m != nil {
		return m.Reflection
	}
	return nil
}

func (m *SpecSetReflectionArchive) GetUnset() bool {
	if m != nil && m.Unset != nil {
		return *m.Unset
	}
	return false
}

type SpecSetShadowArchive struct {
	Shadow               *ShadowArchive `protobuf:"bytes,1,opt,name=shadow" json:"shadow,omitempty"`
	Unset                *bool          `protobuf:"varint,2,req,name=unset" json:"unset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SpecSetShadowArchive) Reset()         { *m = SpecSetShadowArchive{} }
func (m *SpecSetShadowArchive) String() string { return proto.CompactTextString(m) }
func (*SpecSetShadowArchive) ProtoMessage()    {}
func (*SpecSetShadowArchive) Descriptor() ([]byte, []int) {
	return fileDescriptor_78ce555c1fe59eaa, []int{3}
}

func (m *SpecSetShadowArchive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpecSetShadowArchive.Unmarshal(m, b)
}
func (m *SpecSetShadowArchive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpecSetShadowArchive.Marshal(b, m, deterministic)
}
func (m *SpecSetShadowArchive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpecSetShadowArchive.Merge(m, src)
}
func (m *SpecSetShadowArchive) XXX_Size() int {
	return xxx_messageInfo_SpecSetShadowArchive.Size(m)
}
func (m *SpecSetShadowArchive) XXX_DiscardUnknown() {
	xxx_messageInfo_SpecSetShadowArchive.DiscardUnknown(m)
}

var xxx_messageInfo_SpecSetShadowArchive proto.InternalMessageInfo

func (m *SpecSetShadowArchive) GetShadow() *ShadowArchive {
	if m != nil {
		return m.Shadow
	}
	return nil
}

func (m *SpecSetShadowArchive) GetUnset() bool {
	if m != nil && m.Unset != nil {
		return *m.Unset
	}
	return false
}

type SpecSetStrokeArchive struct {
	Stroke               *StrokeArchive `protobuf:"bytes,1,opt,name=stroke" json:"stroke,omitempty"`
	Unset                *bool          `protobuf:"varint,2,req,name=unset" json:"unset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SpecSetStrokeArchive) Reset()         { *m = SpecSetStrokeArchive{} }
func (m *SpecSetStrokeArchive) String() string { return proto.CompactTextString(m) }
func (*SpecSetStrokeArchive) ProtoMessage()    {}
func (*SpecSetStrokeArchive) Descriptor() ([]byte, []int) {
	return fileDescriptor_78ce555c1fe59eaa, []int{4}
}

func (m *SpecSetStrokeArchive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpecSetStrokeArchive.Unmarshal(m, b)
}
func (m *SpecSetStrokeArchive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpecSetStrokeArchive.Marshal(b, m, deterministic)
}
func (m *SpecSetStrokeArchive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpecSetStrokeArchive.Merge(m, src)
}
func (m *SpecSetStrokeArchive) XXX_Size() int {
	return xxx_messageInfo_SpecSetStrokeArchive.Size(m)
}
func (m *SpecSetStrokeArchive) XXX_DiscardUnknown() {
	xxx_messageInfo_SpecSetStrokeArchive.DiscardUnknown(m)
}

var xxx_messageInfo_SpecSetStrokeArchive proto.InternalMessageInfo

func (m *SpecSetStrokeArchive) GetStroke() *StrokeArchive {
	if m != nil {
		return m.Stroke
	}
	return nil
}

func (m *SpecSetStrokeArchive) GetUnset() bool {
	if m != nil && m.Unset != nil {
		return *m.Unset
	}
	return false
}

type SpecFillArchive struct {
	SpecColorFillSetColor     *SpecColorFillSetColorArchive     `protobuf:"bytes,1,opt,name=spec_color_fill_set_color,json=specColorFillSetColor" json:"spec_color_fill_set_color,omitempty"`
	SpecGradientFillSetAngle  *SpecGradientFillSetAngleArchive  `protobuf:"bytes,2,opt,name=spec_gradient_fill_set_angle,json=specGradientFillSetAngle" json:"spec_gradient_fill_set_angle,omitempty"`
	SpecImageFillSetTechnique *SpecImageFillSetTechniqueArchive `protobuf:"bytes,3,opt,name=spec_image_fill_set_technique,json=specImageFillSetTechnique" json:"spec_image_fill_set_technique,omitempty"`
	SpecSetFill               *SpecSetFillArchive               `protobuf:"bytes,4,opt,name=spec_set_fill,json=specSetFill" json:"spec_set_fill,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}                          `json:"-"`
	XXX_unrecognized          []byte                            `json:"-"`
	XXX_sizecache             int32                             `json:"-"`
}

func (m *SpecFillArchive) Reset()         { *m = SpecFillArchive{} }
func (m *SpecFillArchive) String() string { return proto.CompactTextString(m) }
func (*SpecFillArchive) ProtoMessage()    {}
func (*SpecFillArchive) Descriptor() ([]byte, []int) {
	return fileDescriptor_78ce555c1fe59eaa, []int{5}
}

func (m *SpecFillArchive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpecFillArchive.Unmarshal(m, b)
}
func (m *SpecFillArchive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpecFillArchive.Marshal(b, m, deterministic)
}
func (m *SpecFillArchive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpecFillArchive.Merge(m, src)
}
func (m *SpecFillArchive) XXX_Size() int {
	return xxx_messageInfo_SpecFillArchive.Size(m)
}
func (m *SpecFillArchive) XXX_DiscardUnknown() {
	xxx_messageInfo_SpecFillArchive.DiscardUnknown(m)
}

var xxx_messageInfo_SpecFillArchive proto.InternalMessageInfo

func (m *SpecFillArchive) GetSpecColorFillSetColor() *SpecColorFillSetColorArchive {
	if m != nil {
		return m.SpecColorFillSetColor
	}
	return nil
}

func (m *SpecFillArchive) GetSpecGradientFillSetAngle() *SpecGradientFillSetAngleArchive {
	if m != nil {
		return m.SpecGradientFillSetAngle
	}
	return nil
}

func (m *SpecFillArchive) GetSpecImageFillSetTechnique() *SpecImageFillSetTechniqueArchive {
	if m != nil {
		return m.SpecImageFillSetTechnique
	}
	return nil
}

func (m *SpecFillArchive) GetSpecSetFill() *SpecSetFillArchive {
	if m != nil {
		return m.SpecSetFill
	}
	return nil
}

type SpecLineEndArchive struct {
	SpecSetLineEnd       *SpecSetLineEndArchive `protobuf:"bytes,1,opt,name=spec_set_line_end,json=specSetLineEnd" json:"spec_set_line_end,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *SpecLineEndArchive) Reset()         { *m = SpecLineEndArchive{} }
func (m *SpecLineEndArchive) String() string { return proto.CompactTextString(m) }
func (*SpecLineEndArchive) ProtoMessage()    {}
func (*SpecLineEndArchive) Descriptor() ([]byte, []int) {
	return fileDescriptor_78ce555c1fe59eaa, []int{6}
}

func (m *SpecLineEndArchive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpecLineEndArchive.Unmarshal(m, b)
}
func (m *SpecLineEndArchive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpecLineEndArchive.Marshal(b, m, deterministic)
}
func (m *SpecLineEndArchive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpecLineEndArchive.Merge(m, src)
}
func (m *SpecLineEndArchive) XXX_Size() int {
	return xxx_messageInfo_SpecLineEndArchive.Size(m)
}
func (m *SpecLineEndArchive) XXX_DiscardUnknown() {
	xxx_messageInfo_SpecLineEndArchive.DiscardUnknown(m)
}

var xxx_messageInfo_SpecLineEndArchive proto.InternalMessageInfo

func (m *SpecLineEndArchive) GetSpecSetLineEnd() *SpecSetLineEndArchive {
	if m != nil {
		return m.SpecSetLineEnd
	}
	return nil
}

type SpecReflectionArchive struct {
	SpecReflectionSetOpacity *SpecReflectionSetOpacityArchive `protobuf:"bytes,1,opt,name=spec_reflection_set_opacity,json=specReflectionSetOpacity" json:"spec_reflection_set_opacity,omitempty"`
	SpecSetReflection        *SpecSetReflectionArchive        `protobuf:"bytes,2,opt,name=spec_set_reflection,json=specSetReflection" json:"spec_set_reflection,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}                         `json:"-"`
	XXX_unrecognized         []byte                           `json:"-"`
	XXX_sizecache            int32                            `json:"-"`
}

func (m *SpecReflectionArchive) Reset()         { *m = SpecReflectionArchive{} }
func (m *SpecReflectionArchive) String() string { return proto.CompactTextString(m) }
func (*SpecReflectionArchive) ProtoMessage()    {}
func (*SpecReflectionArchive) Descriptor() ([]byte, []int) {
	return fileDescriptor_78ce555c1fe59eaa, []int{7}
}

func (m *SpecReflectionArchive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpecReflectionArchive.Unmarshal(m, b)
}
func (m *SpecReflectionArchive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpecReflectionArchive.Marshal(b, m, deterministic)
}
func (m *SpecReflectionArchive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpecReflectionArchive.Merge(m, src)
}
func (m *SpecReflectionArchive) XXX_Size() int {
	return xxx_messageInfo_SpecReflectionArchive.Size(m)
}
func (m *SpecReflectionArchive) XXX_DiscardUnknown() {
	xxx_messageInfo_SpecReflectionArchive.DiscardUnknown(m)
}

var xxx_messageInfo_SpecReflectionArchive proto.InternalMessageInfo

func (m *SpecReflectionArchive) GetSpecReflectionSetOpacity() *SpecReflectionSetOpacityArchive {
	if m != nil {
		return m.SpecReflectionSetOpacity
	}
	return nil
}

func (m *SpecReflectionArchive) GetSpecSetReflection() *SpecSetReflectionArchive {
	if m != nil {
		return m.SpecSetReflection
	}
	return nil
}

type SpecShadowArchive struct {
	SpecSetShadow        *SpecSetShadowArchive        `protobuf:"bytes,1,opt,name=spec_set_shadow,json=specSetShadow" json:"spec_set_shadow,omitempty"`
	SpecShadowSetAngle   *SpecShadowSetAngleArchive   `protobuf:"bytes,2,opt,name=spec_shadow_set_angle,json=specShadowSetAngle" json:"spec_shadow_set_angle,omitempty"`
	SpecShadowSetColor   *SpecShadowSetColorArchive   `protobuf:"bytes,3,opt,name=spec_shadow_set_color,json=specShadowSetColor" json:"spec_shadow_set_color,omitempty"`
	SpecShadowSetOffset  *SpecShadowSetOffsetArchive  `protobuf:"bytes,4,opt,name=spec_shadow_set_offset,json=specShadowSetOffset" json:"spec_shadow_set_offset,omitempty"`
	SpecShadowSetOpacity *SpecShadowSetOpacityArchive `protobuf:"bytes,5,opt,name=spec_shadow_set_opacity,json=specShadowSetOpacity" json:"spec_shadow_set_opacity,omitempty"`
	SpecShadowSetRadius  *SpecShadowSetRadiusArchive  `protobuf:"bytes,6,opt,name=spec_shadow_set_radius,json=specShadowSetRadius" json:"spec_shadow_set_radius,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *SpecShadowArchive) Reset()         { *m = SpecShadowArchive{} }
func (m *SpecShadowArchive) String() string { return proto.CompactTextString(m) }
func (*SpecShadowArchive) ProtoMessage()    {}
func (*SpecShadowArchive) Descriptor() ([]byte, []int) {
	return fileDescriptor_78ce555c1fe59eaa, []int{8}
}

func (m *SpecShadowArchive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpecShadowArchive.Unmarshal(m, b)
}
func (m *SpecShadowArchive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpecShadowArchive.Marshal(b, m, deterministic)
}
func (m *SpecShadowArchive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpecShadowArchive.Merge(m, src)
}
func (m *SpecShadowArchive) XXX_Size() int {
	return xxx_messageInfo_SpecShadowArchive.Size(m)
}
func (m *SpecShadowArchive) XXX_DiscardUnknown() {
	xxx_messageInfo_SpecShadowArchive.DiscardUnknown(m)
}

var xxx_messageInfo_SpecShadowArchive proto.InternalMessageInfo

func (m *SpecShadowArchive) GetSpecSetShadow() *SpecSetShadowArchive {
	if m != nil {
		return m.SpecSetShadow
	}
	return nil
}

func (m *SpecShadowArchive) GetSpecShadowSetAngle() *SpecShadowSetAngleArchive {
	if m != nil {
		return m.SpecShadowSetAngle
	}
	return nil
}

func (m *SpecShadowArchive) GetSpecShadowSetColor() *SpecShadowSetColorArchive {
	if m != nil {
		return m.SpecShadowSetColor
	}
	return nil
}

func (m *SpecShadowArchive) GetSpecShadowSetOffset() *SpecShadowSetOffsetArchive {
	if m != nil {
		return m.SpecShadowSetOffset
	}
	return nil
}

func (m *SpecShadowArchive) GetSpecShadowSetOpacity() *SpecShadowSetOpacityArchive {
	if m != nil {
		return m.SpecShadowSetOpacity
	}
	return nil
}

func (m *SpecShadowArchive) GetSpecShadowSetRadius() *SpecShadowSetRadiusArchive {
	if m != nil {
		return m.SpecShadowSetRadius
	}
	return nil
}

type SpecStrokeArchive struct {
	SpecFrameSetAssetScale *SpecFrameSetAssetScaleArchive `protobuf:"bytes,1,opt,name=spec_frame_set_asset_scale,json=specFrameSetAssetScale" json:"spec_frame_set_asset_scale,omitempty"`
	SpecSetStroke          *SpecSetStrokeArchive          `protobuf:"bytes,2,opt,name=spec_set_stroke,json=specSetStroke" json:"spec_set_stroke,omitempty"`
	SpecStrokeSetColor     *SpecStrokeSetColorArchive     `protobuf:"bytes,3,opt,name=spec_stroke_set_color,json=specStrokeSetColor" json:"spec_stroke_set_color,omitempty"`
	SpecStrokeSetPattern   *SpecStrokeSetPatternArchive   `protobuf:"bytes,4,opt,name=spec_stroke_set_pattern,json=specStrokeSetPattern" json:"spec_stroke_set_pattern,omitempty"`
	SpecStrokeSetWidth     *SpecStrokeSetWidthArchive     `protobuf:"bytes,5,opt,name=spec_stroke_set_width,json=specStrokeSetWidth" json:"spec_stroke_set_width,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                       `json:"-"`
	XXX_unrecognized       []byte                         `json:"-"`
	XXX_sizecache          int32                          `json:"-"`
}

func (m *SpecStrokeArchive) Reset()         { *m = SpecStrokeArchive{} }
func (m *SpecStrokeArchive) String() string { return proto.CompactTextString(m) }
func (*SpecStrokeArchive) ProtoMessage()    {}
func (*SpecStrokeArchive) Descriptor() ([]byte, []int) {
	return fileDescriptor_78ce555c1fe59eaa, []int{9}
}

func (m *SpecStrokeArchive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpecStrokeArchive.Unmarshal(m, b)
}
func (m *SpecStrokeArchive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpecStrokeArchive.Marshal(b, m, deterministic)
}
func (m *SpecStrokeArchive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpecStrokeArchive.Merge(m, src)
}
func (m *SpecStrokeArchive) XXX_Size() int {
	return xxx_messageInfo_SpecStrokeArchive.Size(m)
}
func (m *SpecStrokeArchive) XXX_DiscardUnknown() {
	xxx_messageInfo_SpecStrokeArchive.DiscardUnknown(m)
}

var xxx_messageInfo_SpecStrokeArchive proto.InternalMessageInfo

func (m *SpecStrokeArchive) GetSpecFrameSetAssetScale() *SpecFrameSetAssetScaleArchive {
	if m != nil {
		return m.SpecFrameSetAssetScale
	}
	return nil
}

func (m *SpecStrokeArchive) GetSpecSetStroke() *SpecSetStrokeArchive {
	if m != nil {
		return m.SpecSetStroke
	}
	return nil
}

func (m *SpecStrokeArchive) GetSpecStrokeSetColor() *SpecStrokeSetColorArchive {
	if m != nil {
		return m.SpecStrokeSetColor
	}
	return nil
}

func (m *SpecStrokeArchive) GetSpecStrokeSetPattern() *SpecStrokeSetPatternArchive {
	if m != nil {
		return m.SpecStrokeSetPattern
	}
	return nil
}

func (m *SpecStrokeArchive) GetSpecStrokeSetWidth() *SpecStrokeSetWidthArchive {
	if m != nil {
		return m.SpecStrokeSetWidth
	}
	return nil
}

type BaseShapeStylePropertyChangeSetArchive struct {
	Fill                 *SpecFillArchive       `protobuf:"bytes,1,opt,name=fill" json:"fill,omitempty"`
	FillUndefined        *bool                  `protobuf:"varint,2,opt,name=fill_undefined,json=fillUndefined" json:"fill_undefined,omitempty"`
	Stroke               *SpecStrokeArchive     `protobuf:"bytes,3,opt,name=stroke" json:"stroke,omitempty"`
	StrokeUndefined      *bool                  `protobuf:"varint,4,opt,name=stroke_undefined,json=strokeUndefined" json:"stroke_undefined,omitempty"`
	Opacity              *TSS.SpecDoubleArchive `protobuf:"bytes,5,opt,name=opacity" json:"opacity,omitempty"`
	OpacityUndefined     *bool                  `protobuf:"varint,6,opt,name=opacity_undefined,json=opacityUndefined" json:"opacity_undefined,omitempty"`
	Shadow               *SpecShadowArchive     `protobuf:"bytes,7,opt,name=shadow" json:"shadow,omitempty"`
	ShadowUndefined      *bool                  `protobuf:"varint,8,opt,name=shadow_undefined,json=shadowUndefined" json:"shadow_undefined,omitempty"`
	Reflection           *SpecReflectionArchive `protobuf:"bytes,9,opt,name=reflection" json:"reflection,omitempty"`
	ReflectionUndefined  *bool                  `protobuf:"varint,10,opt,name=reflection_undefined,json=reflectionUndefined" json:"reflection_undefined,omitempty"`
	HeadLineEnd          *SpecLineEndArchive    `protobuf:"bytes,11,opt,name=head_line_end,json=headLineEnd" json:"head_line_end,omitempty"`
	HeadLineEndUndefined *bool                  `protobuf:"varint,12,opt,name=head_line_end_undefined,json=headLineEndUndefined" json:"head_line_end_undefined,omitempty"`
	TailLineEnd          *SpecLineEndArchive    `protobuf:"bytes,13,opt,name=tail_line_end,json=tailLineEnd" json:"tail_line_end,omitempty"`
	TailLineEndUndefined *bool                  `protobuf:"varint,14,opt,name=tail_line_end_undefined,json=tailLineEndUndefined" json:"tail_line_end_undefined,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *BaseShapeStylePropertyChangeSetArchive) Reset() {
	*m = BaseShapeStylePropertyChangeSetArchive{}
}
func (m *BaseShapeStylePropertyChangeSetArchive) String() string { return proto.CompactTextString(m) }
func (*BaseShapeStylePropertyChangeSetArchive) ProtoMessage()    {}
func (*BaseShapeStylePropertyChangeSetArchive) Descriptor() ([]byte, []int) {
	return fileDescriptor_78ce555c1fe59eaa, []int{10}
}

func (m *BaseShapeStylePropertyChangeSetArchive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseShapeStylePropertyChangeSetArchive.Unmarshal(m, b)
}
func (m *BaseShapeStylePropertyChangeSetArchive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseShapeStylePropertyChangeSetArchive.Marshal(b, m, deterministic)
}
func (m *BaseShapeStylePropertyChangeSetArchive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseShapeStylePropertyChangeSetArchive.Merge(m, src)
}
func (m *BaseShapeStylePropertyChangeSetArchive) XXX_Size() int {
	return xxx_messageInfo_BaseShapeStylePropertyChangeSetArchive.Size(m)
}
func (m *BaseShapeStylePropertyChangeSetArchive) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseShapeStylePropertyChangeSetArchive.DiscardUnknown(m)
}

var xxx_messageInfo_BaseShapeStylePropertyChangeSetArchive proto.InternalMessageInfo

func (m *BaseShapeStylePropertyChangeSetArchive) GetFill() *SpecFillArchive {
	if m != nil {
		return m.Fill
	}
	return nil
}

func (m *BaseShapeStylePropertyChangeSetArchive) GetFillUndefined() bool {
	if m != nil && m.FillUndefined != nil {
		return *m.FillUndefined
	}
	return false
}

func (m *BaseShapeStylePropertyChangeSetArchive) GetStroke() *SpecStrokeArchive {
	if m != nil {
		return m.Stroke
	}
	return nil
}

func (m *BaseShapeStylePropertyChangeSetArchive) GetStrokeUndefined() bool {
	if m != nil && m.StrokeUndefined != nil {
		return *m.StrokeUndefined
	}
	return false
}

func (m *BaseShapeStylePropertyChangeSetArchive) GetOpacity() *TSS.SpecDoubleArchive {
	if m != nil {
		return m.Opacity
	}
	return nil
}

func (m *BaseShapeStylePropertyChangeSetArchive) GetOpacityUndefined() bool {
	if m != nil && m.OpacityUndefined != nil {
		return *m.OpacityUndefined
	}
	return false
}

func (m *BaseShapeStylePropertyChangeSetArchive) GetShadow() *SpecShadowArchive {
	if m != nil {
		return m.Shadow
	}
	return nil
}

func (m *BaseShapeStylePropertyChangeSetArchive) GetShadowUndefined() bool {
	if m != nil && m.ShadowUndefined != nil {
		return *m.ShadowUndefined
	}
	return false
}

func (m *BaseShapeStylePropertyChangeSetArchive) GetReflection() *SpecReflectionArchive {
	if m != nil {
		return m.Reflection
	}
	return nil
}

func (m *BaseShapeStylePropertyChangeSetArchive) GetReflectionUndefined() bool {
	if m != nil && m.ReflectionUndefined != nil {
		return *m.ReflectionUndefined
	}
	return false
}

func (m *BaseShapeStylePropertyChangeSetArchive) GetHeadLineEnd() *SpecLineEndArchive {
	if m != nil {
		return m.HeadLineEnd
	}
	return nil
}

func (m *BaseShapeStylePropertyChangeSetArchive) GetHeadLineEndUndefined() bool {
	if m != nil && m.HeadLineEndUndefined != nil {
		return *m.HeadLineEndUndefined
	}
	return false
}

func (m *BaseShapeStylePropertyChangeSetArchive) GetTailLineEnd() *SpecLineEndArchive {
	if m != nil {
		return m.TailLineEnd
	}
	return nil
}

func (m *BaseShapeStylePropertyChangeSetArchive) GetTailLineEndUndefined() bool {
	if m != nil && m.TailLineEndUndefined != nil {
		return *m.TailLineEndUndefined
	}
	return false
}

type MediaStylePropertyChangeSetArchive struct {
	Stroke               *SpecStrokeArchive     `protobuf:"bytes,1,opt,name=stroke" json:"stroke,omitempty"`
	StrokeUndefined      *bool                  `protobuf:"varint,2,opt,name=stroke_undefined,json=strokeUndefined" json:"stroke_undefined,omitempty"`
	Opacity              *TSS.SpecDoubleArchive `protobuf:"bytes,3,opt,name=opacity" json:"opacity,omitempty"`
	OpacityUndefined     *bool                  `protobuf:"varint,4,opt,name=opacity_undefined,json=opacityUndefined" json:"opacity_undefined,omitempty"`
	Shadow               *SpecShadowArchive     `protobuf:"bytes,5,opt,name=shadow" json:"shadow,omitempty"`
	ShadowUndefined      *bool                  `protobuf:"varint,6,opt,name=shadow_undefined,json=shadowUndefined" json:"shadow_undefined,omitempty"`
	Reflection           *SpecReflectionArchive `protobuf:"bytes,7,opt,name=reflection" json:"reflection,omitempty"`
	ReflectionUndefined  *bool                  `protobuf:"varint,8,opt,name=reflection_undefined,json=reflectionUndefined" json:"reflection_undefined,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *MediaStylePropertyChangeSetArchive) Reset()         { *m = MediaStylePropertyChangeSetArchive{} }
func (m *MediaStylePropertyChangeSetArchive) String() string { return proto.CompactTextString(m) }
func (*MediaStylePropertyChangeSetArchive) ProtoMessage()    {}
func (*MediaStylePropertyChangeSetArchive) Descriptor() ([]byte, []int) {
	return fileDescriptor_78ce555c1fe59eaa, []int{11}
}

func (m *MediaStylePropertyChangeSetArchive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MediaStylePropertyChangeSetArchive.Unmarshal(m, b)
}
func (m *MediaStylePropertyChangeSetArchive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MediaStylePropertyChangeSetArchive.Marshal(b, m, deterministic)
}
func (m *MediaStylePropertyChangeSetArchive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MediaStylePropertyChangeSetArchive.Merge(m, src)
}
func (m *MediaStylePropertyChangeSetArchive) XXX_Size() int {
	return xxx_messageInfo_MediaStylePropertyChangeSetArchive.Size(m)
}
func (m *MediaStylePropertyChangeSetArchive) XXX_DiscardUnknown() {
	xxx_messageInfo_MediaStylePropertyChangeSetArchive.DiscardUnknown(m)
}

var xxx_messageInfo_MediaStylePropertyChangeSetArchive proto.InternalMessageInfo

func (m *MediaStylePropertyChangeSetArchive) GetStroke() *SpecStrokeArchive {
	if m != nil {
		return m.Stroke
	}
	return nil
}

func (m *MediaStylePropertyChangeSetArchive) GetStrokeUndefined() bool {
	if m != nil && m.StrokeUndefined != nil {
		return *m.StrokeUndefined
	}
	return false
}

func (m *MediaStylePropertyChangeSetArchive) GetOpacity() *TSS.SpecDoubleArchive {
	if m != nil {
		return m.Opacity
	}
	return nil
}

func (m *MediaStylePropertyChangeSetArchive) GetOpacityUndefined() bool {
	if m != nil && m.OpacityUndefined != nil {
		return *m.OpacityUndefined
	}
	return false
}

func (m *MediaStylePropertyChangeSetArchive) GetShadow() *SpecShadowArchive {
	if m != nil {
		return m.Shadow
	}
	return nil
}

func (m *MediaStylePropertyChangeSetArchive) GetShadowUndefined() bool {
	if m != nil && m.ShadowUndefined != nil {
		return *m.ShadowUndefined
	}
	return false
}

func (m *MediaStylePropertyChangeSetArchive) GetReflection() *SpecReflectionArchive {
	if m != nil {
		return m.Reflection
	}
	return nil
}

func (m *MediaStylePropertyChangeSetArchive) GetReflectionUndefined() bool {
	if m != nil && m.ReflectionUndefined != nil {
		return *m.ReflectionUndefined
	}
	return false
}

func init() {
	proto.RegisterType((*SpecSetFillArchive)(nil), "TSD.SpecSetFillArchive")
	proto.RegisterType((*SpecSetLineEndArchive)(nil), "TSD.SpecSetLineEndArchive")
	proto.RegisterType((*SpecSetReflectionArchive)(nil), "TSD.SpecSetReflectionArchive")
	proto.RegisterType((*SpecSetShadowArchive)(nil), "TSD.SpecSetShadowArchive")
	proto.RegisterType((*SpecSetStrokeArchive)(nil), "TSD.SpecSetStrokeArchive")
	proto.RegisterType((*SpecFillArchive)(nil), "TSD.SpecFillArchive")
	proto.RegisterType((*SpecLineEndArchive)(nil), "TSD.SpecLineEndArchive")
	proto.RegisterType((*SpecReflectionArchive)(nil), "TSD.SpecReflectionArchive")
	proto.RegisterType((*SpecShadowArchive)(nil), "TSD.SpecShadowArchive")
	proto.RegisterType((*SpecStrokeArchive)(nil), "TSD.SpecStrokeArchive")
	proto.RegisterType((*BaseShapeStylePropertyChangeSetArchive)(nil), "TSD.BaseShapeStylePropertyChangeSetArchive")
	proto.RegisterType((*MediaStylePropertyChangeSetArchive)(nil), "TSD.MediaStylePropertyChangeSetArchive")
}

func init() { proto.RegisterFile("TSDArchives_sos.proto", fileDescriptor_78ce555c1fe59eaa) }

var fileDescriptor_78ce555c1fe59eaa = []byte{
	// 1002 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x96, 0xdf, 0x6e, 0xe3, 0x44,
	0x14, 0xc6, 0xd5, 0xa4, 0x7f, 0xc2, 0x29, 0x69, 0x1b, 0x37, 0xd9, 0x66, 0x0b, 0x0b, 0xc5, 0xda,
	0x42, 0x01, 0x29, 0x05, 0x24, 0xb8, 0x60, 0xaf, 0xba, 0x9b, 0x5d, 0x84, 0xc4, 0x6a, 0x8b, 0x1d,
	0x54, 0xc4, 0x0a, 0x22, 0xd7, 0x9e, 0xc4, 0xd6, 0xba, 0x9e, 0xe0, 0x99, 0xec, 0xaa, 0xdc, 0xf1,
	0x36, 0xbc, 0x00, 0x4f, 0xc1, 0x73, 0xf0, 0x12, 0x5c, 0xa1, 0x39, 0x33, 0xf6, 0xcc, 0xd8, 0x4e,
	0x8b, 0x96, 0xbd, 0x8b, 0xcf, 0xf9, 0xf2, 0xfb, 0x26, 0x99, 0xef, 0xcc, 0x18, 0x06, 0x13, 0x7f,
	0x7c, 0x96, 0x87, 0x71, 0xf2, 0x92, 0xb0, 0x29, 0xa3, 0x6c, 0xb4, 0xc8, 0x29, 0xa7, 0x4e, 0x7b,
	0xe2, 0x8f, 0x0f, 0x7b, 0x46, 0x4f, 0xd6, 0x0f, 0x07, 0x13, 0xdf, 0xaf, 0xcb, 0xdd, 0x73, 0x70,
	0xfc, 0x05, 0x09, 0x7d, 0xc2, 0x9f, 0x24, 0x69, 0xaa, 0x04, 0xce, 0x7d, 0x58, 0x9f, 0x25, 0x69,
	0x3a, 0x5c, 0x3b, 0x5a, 0x3b, 0xd9, 0xfe, 0x62, 0x6f, 0x34, 0xf1, 0xc7, 0x23, 0xa3, 0xef, 0x61,
	0xd7, 0xe9, 0xc3, 0xc6, 0x32, 0x63, 0x84, 0x0f, 0x5b, 0x47, 0xad, 0x93, 0x8e, 0x27, 0x1f, 0xdc,
	0x9f, 0x61, 0xa0, 0x88, 0xdf, 0x25, 0x19, 0x79, 0x9c, 0x45, 0x05, 0x74, 0x04, 0x9d, 0x34, 0xc9,
	0xc8, 0x94, 0x64, 0x91, 0x02, 0xef, 0x23, 0xd8, 0x96, 0x79, 0x5b, 0xa9, 0x7c, 0x5e, 0x81, 0x8f,
	0x61, 0xa8, 0xf0, 0x1e, 0x99, 0xa5, 0x24, 0xe4, 0x09, 0xcd, 0x0a, 0x87, 0xaf, 0x00, 0xf2, 0xb2,
	0xa8, 0x3c, 0xee, 0xa0, 0x47, 0x4d, 0xeb, 0x19, 0xca, 0x15, 0x4e, 0x3f, 0x42, 0x5f, 0x39, 0xf9,
	0x71, 0x10, 0xd1, 0x57, 0x85, 0xcb, 0x27, 0xb0, 0xc9, 0xb0, 0xa0, 0x1c, 0x1c, 0x74, 0xb0, 0x34,
	0x9e, 0x52, 0xdc, 0x4e, 0xe6, 0x39, 0x7d, 0x41, 0x4c, 0x32, 0x16, 0x6c, 0xb2, 0xa9, 0xf1, 0x94,
	0x62, 0x05, 0xf9, 0x9f, 0x16, 0xec, 0x0a, 0xb4, 0xb9, 0x99, 0xcf, 0xe1, 0x2e, 0x5b, 0x90, 0x70,
	0x1a, 0xd2, 0x94, 0xe6, 0x53, 0xb1, 0x73, 0x53, 0x46, 0xb8, 0x7c, 0x54, 0x46, 0x1f, 0x48, 0xa3,
	0x05, 0x09, 0x1f, 0x89, 0xaa, 0xf8, 0xb6, 0x4f, 0x38, 0x7e, 0x2e, 0x7c, 0x07, 0xac, 0xa9, 0xeb,
	0x44, 0xf0, 0x2e, 0xc2, 0xe7, 0x79, 0x10, 0x25, 0x24, 0xe3, 0x9a, 0x1f, 0x64, 0xf3, 0x94, 0x0c,
	0x5b, 0xc8, 0xbf, 0x5f, 0xf2, 0xbf, 0x51, 0x3a, 0x05, 0x39, 0x13, 0xa2, 0xc2, 0x62, 0xc8, 0x56,
	0x08, 0x9c, 0x39, 0xdc, 0x43, 0x97, 0xe4, 0x2a, 0x98, 0x13, 0x6d, 0xc1, 0x49, 0x18, 0x67, 0xc9,
	0xaf, 0x4b, 0x32, 0x6c, 0xa3, 0xcd, 0x71, 0x69, 0xf3, 0xad, 0x10, 0x2a, 0xc4, 0xa4, 0x50, 0x15,
	0x3e, 0xf8, 0x77, 0x34, 0x2a, 0x9c, 0x07, 0xd0, 0x45, 0x23, 0x41, 0xc7, 0x09, 0x58, 0x47, 0xf0,
	0x41, 0x09, 0xb6, 0x07, 0xc5, 0xdb, 0x66, 0xba, 0xe6, 0x3e, 0x97, 0xb3, 0x54, 0x89, 0xfd, 0x63,
	0xe8, 0x95, 0xc8, 0x4a, 0xfe, 0x0f, 0x4d, 0x6c, 0x65, 0x0c, 0x76, 0x98, 0x55, 0x76, 0xff, 0x5a,
	0x93, 0x73, 0x55, 0x4f, 0x7d, 0x08, 0xef, 0xa0, 0x81, 0x0e, 0x34, 0x7a, 0xd1, 0x45, 0x10, 0x26,
	0xfc, 0x5a, 0x59, 0xe9, 0x1d, 0xd0, 0x00, 0x9f, 0xf0, 0x67, 0x52, 0x64, 0xed, 0x40, 0x93, 0xc0,
	0x79, 0x0a, 0xfb, 0xe5, 0xaf, 0x30, 0x66, 0x4c, 0x6e, 0xef, 0x3d, 0xf3, 0x77, 0xd4, 0x47, 0xad,
	0xc7, 0xaa, 0x1d, 0xf7, 0xf7, 0x75, 0xe8, 0xa1, 0xde, 0x9a, 0xac, 0x33, 0xd8, 0x2d, 0x4d, 0xac,
	0x11, 0xbb, 0x6b, 0x1a, 0xd8, 0x93, 0xd6, 0x65, 0x66, 0xd5, 0xf9, 0x1e, 0x06, 0x12, 0x81, 0x8f,
	0xb5, 0x20, 0xbe, 0xa7, 0x41, 0x28, 0xa8, 0x46, 0xd0, 0x61, 0xb5, 0x56, 0x13, 0x52, 0xce, 0x4e,
	0x7b, 0x15, 0xd2, 0x1a, 0x1c, 0x1b, 0x29, 0xa7, 0x66, 0x02, 0x77, 0xaa, 0x48, 0x3a, 0x9b, 0x89,
	0x69, 0x96, 0x79, 0x7b, 0xbf, 0xce, 0x7c, 0x86, 0xfd, 0x02, 0xba, 0xcf, 0xea, 0x3d, 0xe7, 0x02,
	0x0e, 0x6a, 0x54, 0x15, 0x82, 0x0d, 0xc4, 0x1e, 0x35, 0x60, 0xed, 0x00, 0xf4, 0x59, 0x43, 0xb3,
	0x69, 0xb9, 0x62, 0x4a, 0x97, 0x6c, 0xb8, 0xb9, 0x6a, 0xb9, 0x1e, 0xf6, 0x9b, 0x97, 0x2b, 0x7b,
	0xee, 0x9f, 0x6d, 0x95, 0x01, 0xeb, 0x0c, 0xfc, 0x05, 0x0e, 0xd1, 0x6b, 0x96, 0x07, 0x57, 0x44,
	0xee, 0x1f, 0xc3, 0x3c, 0x84, 0x41, 0x5a, 0x9c, 0x8b, 0x6e, 0xe9, 0xf7, 0x44, 0xa8, 0xc4, 0x4e,
	0x09, 0x8d, 0x2f, 0x24, 0x85, 0x25, 0xae, 0xb8, 0xde, 0xb6, 0x33, 0x26, 0x0f, 0xdb, 0x56, 0x43,
	0xc6, 0xac, 0x33, 0xb7, 0xcc, 0x98, 0x3c, 0x7a, 0xcb, 0x40, 0xe0, 0xe3, 0x4d, 0x81, 0x40, 0x41,
	0x73, 0x20, 0xac, 0x96, 0xde, 0x3a, 0x8d, 0x5c, 0x04, 0x9c, 0x93, 0x3c, 0x53, 0x89, 0x38, 0xaa,
	0x43, 0xcf, 0xa5, 0xc0, 0xde, 0xba, 0x4a, 0xb3, 0x69, 0xad, 0xaf, 0x92, 0x88, 0xc7, 0x2a, 0x11,
	0x0d, 0x6b, 0xbd, 0x10, 0xed, 0xe6, 0xb5, 0x62, 0xcb, 0xfd, 0x7b, 0x03, 0x3e, 0x7c, 0x18, 0x30,
	0xe2, 0xc7, 0xc1, 0x82, 0xf8, 0xfc, 0x3a, 0x25, 0xe7, 0x39, 0x5d, 0x90, 0x9c, 0x5f, 0x3f, 0x8a,
	0x83, 0x6c, 0x8e, 0xff, 0xb7, 0xda, 0xcc, 0x13, 0xeb, 0x3d, 0xa2, 0xaf, 0xb7, 0xad, 0xf6, 0x2e,
	0x71, 0x0c, 0x3b, 0x78, 0xac, 0x2f, 0xb3, 0x88, 0xcc, 0x92, 0x8c, 0x44, 0xb8, 0x2b, 0x1d, 0xaf,
	0x2b, 0xaa, 0x3f, 0x14, 0x45, 0x67, 0x54, 0xde, 0x90, 0x6d, 0xe3, 0x76, 0xaf, 0xa5, 0xa8, 0xbc,
	0x25, 0x3f, 0x86, 0x3d, 0xf5, 0xcb, 0x35, 0x78, 0x1d, 0xc1, 0xbb, 0xb2, 0xae, 0xd1, 0x9f, 0xc1,
	0x96, 0x3d, 0x2d, 0x82, 0xed, 0x23, 0x7b, 0x4c, 0x97, 0x97, 0x3a, 0x59, 0x85, 0xcc, 0xf9, 0x14,
	0x7a, 0xea, 0xa3, 0x41, 0xdf, 0x44, 0xfa, 0x9e, 0x6a, 0xd8, 0x2b, 0x97, 0x47, 0xda, 0x56, 0x75,
	0xe5, 0x8d, 0x6f, 0x0e, 0x62, 0xe5, 0x72, 0xdc, 0x34, 0xbb, 0xa3, 0x56, 0x8e, 0x75, 0x8d, 0xfe,
	0xda, 0x7a, 0xed, 0x79, 0xab, 0x72, 0xb5, 0xdc, 0xfc, 0xea, 0xf3, 0x39, 0xf4, 0x8d, 0x7b, 0x43,
	0x5b, 0x01, 0x5a, 0xed, 0xeb, 0x9e, 0xb6, 0x7b, 0x00, 0xdd, 0x98, 0x04, 0x91, 0xbe, 0xcc, 0xb6,
	0x2b, 0x77, 0x64, 0xe5, 0x26, 0xdb, 0x16, 0x6a, 0x55, 0x73, 0xbe, 0x84, 0x03, 0xeb, 0xcb, 0x86,
	0xe5, 0xdb, 0x68, 0xd9, 0x37, 0xd4, 0x96, 0x27, 0x0f, 0x92, 0x54, 0x7b, 0x76, 0x6f, 0xf1, 0x14,
	0x6a, 0xc3, 0xd3, 0xfa, 0xb2, 0xe1, 0xb9, 0x23, 0x3d, 0x0d, 0x75, 0xe9, 0xe9, 0xfe, 0xd1, 0x06,
	0xf7, 0x29, 0x89, 0x92, 0xe0, 0xe6, 0x8c, 0x8f, 0x2a, 0x2f, 0x6d, 0xaf, 0x13, 0xc9, 0xd6, 0xad,
	0x91, 0x6c, 0xff, 0x8f, 0x48, 0xae, 0xdf, 0x1a, 0xc9, 0x8d, 0xd7, 0x8e, 0xe4, 0xe6, 0x7f, 0x89,
	0xe4, 0xd6, 0x1b, 0x89, 0x64, 0x67, 0x65, 0x24, 0x1f, 0x7e, 0xf4, 0xd3, 0xf1, 0x3c, 0xe1, 0xf1,
	0xf2, 0x72, 0x14, 0xd2, 0xab, 0xd3, 0xdf, 0x92, 0xab, 0xcb, 0xe0, 0x32, 0xa0, 0xa7, 0x11, 0x0d,
	0x43, 0x9a, 0xbd, 0x3c, 0x4d, 0x2e, 0x68, 0xfe, 0xe2, 0x74, 0xe2, 0x8f, 0xff, 0x0d, 0x00, 0x00,
	0xff, 0xff, 0xd2, 0xb8, 0x70, 0xbc, 0x35, 0x0d, 0x00, 0x00,
}
